from data.data_processing.units import (
    praepositionen_grammatik, praepositionen_verben, praepositionen_adjektive, praepositionen_nomen,
    praepositionen_artikel,
    artikel, artikel_genus, pronomen, konnektoren, fragen, adverbien,
    adjektive, adjektivdeklinationen,
    verben, trennbare_verben, nomen_verben_verbindungen,
    praesens, imperativ, partizip_II, praeteritum, praeteritum_partizip_II, konjunktiv_II, konjunktiv_I, partizip_I,
)

DESCRIPTION_FR = {

    praepositionen_grammatik: {
        1: "Prépositions temporelles, en contexte",
        2: "Prépositions locales (Position), en contexte",
        3: "Prépositions locales (Direction), en contexte",
        4: "Prépositions modales et causales, en contexte",

        5: "Prépositions temporelles de base au niveau A2, en contexte",
        6: "Prépositions locales (Position) de base au niveau A2, en contexte",
        7: "Prépositions locales (Direction) de base au niveau A2, en contexte",
        8: "Prépositions modales et causales de base au niveau A2, en contexte",

        9: "Prépositions de base au niveau B1, en contexte",
        10: "Prépositions de base au niveau B1, en contexte",
        11: "Prépositions de niveau B1, en isolation",
        12: "Prépositions de niveau B1, en contexte",

        13: "Prépositions de base au niveau B2, en contexte",
        14: "Prépositions de base au niveau B2, en contexte",
        15: "Prépositions de niveau B2, en isolation",
        16: "Prépositions de niveau B2, en contexte",

        17: "Prépositions de base au niveau C1, en contexte",
        18: "Prépositions de base au niveau C1, en contexte",
        19: "Prépositions de niveau C1, en isolation",
        20: "Prépositions de niveau C1, en contexte",
        21: "Prépositions de niveau C1, en isolation",
        22: "Prépositions de niveau C1, en contexte",
        23: "Groupe prépositionel de niveau C1, en isolation",
        24: "Groupe prépositionel de niveau C1, en contexte",
        25: "Postpositions de niveau C1, en isolation",
        26: "Postpositions de niveau C1, en contexte",
    },

    praepositionen_verben: {
        1: "Paires Verbe-Préposition de niveau A1, en isolation",
        2: "Paires Verbe-Préposition de niveau A1, en contexte",
        3: "Paires Verbe-Préposition de niveau A1, en isolation",
        4: "Paires Verbe-Préposition de niveau A1, en contexte",

        5: "Paires Verbe-Préposition de niveau A2, en isolation",
        6: "Paires Verbe-Préposition de niveau A2, en contexte",
        7: "Paires Verbe-Préposition de niveau A2, en isolation",
        8: "Paires Verbe-Préposition de niveau A2, en contexte",
        9: "Adverbes pronominal en Da-, en contexte",
        10: "Adverbes pronominal en Wo-, en contexte",

        11: "Paires Verbe-Préposition de niveau B1, en isolation",
        12: "Paires Verbe-Préposition de niveau B1, en contexte",
        13: "Paires Verbe-Préposition de niveau B1, en isolation",
        14: "Paires Verbe-Préposition de niveau B1, en contexte",
        15: "Paires Verbe-Préposition de niveau B1, en isolation",
        16: "Paires Verbe-Préposition de niveau B1, en contexte",
        17: "Paires Verbe-Préposition de niveau B1, en isolation",
        18: "Paires Verbe-Préposition de niveau B1, en contexte",

        19: "Paires Verbe-Préposition de niveau B2, en isolation",
        20: "Paires Verbe-Préposition de niveau B2, en contexte",
        21: "Paires Verbe-Préposition de niveau B2, en isolation",
        22: "Paires Verbe-Préposition de niveau B2, en contexte",
        23: "Paires Verbe-Préposition de niveau B2, en isolation",
        24: "Paires Verbe-Préposition de niveau B2, en contexte",
        25: "Paires Verbe-Préposition de niveau B2, en isolation",
        26: "Paires Verbe-Préposition de niveau B2, en contexte",

        27: "Paires Verbe-Préposition de niveau C1, en isolation",
        28: "Paires Verbe-Préposition de niveau C1, en contexte",
        29: "Paires Verbe-Préposition de niveau C1, en isolation",
        30: "Paires Verbe-Préposition de niveau C1, en contexte",
        31: "Paires Verbe-Préposition de niveau C1, en isolation",
        32: "Paires Verbe-Préposition de niveau C1, en contexte",
    },

    praepositionen_adjektive: {
        1: "Paires Adjectif-Préposition jusqu'au niveau B1, en isolation",
        2: "Paires Adjectif-Préposition jusqu'au niveau B1, en contexte",
        3: "Paires Adjectif-Préposition jusqu'au niveau B1, en isolation",
        4: "Paires Adjectif-Préposition jusqu'au niveau B1, en contexte",

        5: "Paires Adjectif-Préposition de niveau B2, en isolation",
        6: "Paires Adjectif-Préposition de niveau B2, en contexte",
        7: "Paires Adjectif-Préposition de niveau B2, en isolation",
        8: "Paires Adjectif-Préposition de niveau B2, en contexte",
        9: "Paires Adjectif-Préposition de niveau B2, en isolation",
        10: "Paires Adjectif-Préposition de niveau B2, en contexte",

        11: "Paires Adjectif-Préposition de niveau C1, en isolation",
        12: "Paires Adjectif-Préposition de niveau C1, en contexte",
        13: "Paires Adjectif-Préposition de niveau C1, en isolation",
        14: "Paires Adjectif-Préposition de niveau C1, en contexte",
        15: "Paires Adjectif-Préposition de niveau C1, en isolation",
        16: "Paires Adjectif-Préposition de niveau C1, en contexte",
    },

    praepositionen_nomen: {
        1: "Paires Nom-Préposition jusqu'au niveau B1, en isolation",
        2: "Paires Nom-Préposition jusqu'au niveau B1, en contexte",
        3: "Paires Nom-Préposition jusqu'au niveau B1, en isolation",
        4: "Paires Nom-Préposition jusqu'au niveau B1, en contexte",
        5: "Paires Nom-Préposition jusqu'au niveau B1, en isolation",
        6: "Paires Nom-Préposition jusqu'au niveau B1, en contexte",

        7: "Paires Nom-Préposition de niveau B2, en isolation",
        8: "Paires Nom-Préposition de niveau B2, en contexte",
        9: "Paires Nom-Préposition de niveau B2, en isolation",
        10: "Paires Nom-Préposition de niveau B2, en contexte",
        11: "Paires Nom-Préposition de niveau B2, en isolation",
        12: "Paires Nom-Préposition de niveau B2, en contexte",
        13: "Paires Nom-Préposition de niveau B2, en isolation",
        14: "Paires Nom-Préposition de niveau B2, en contexte",
        15: "Paires Nom-Préposition de niveau B2, en isolation",
        16: "Paires Nom-Préposition de niveau B2, en contexte",

        17: "Paires Nom-Préposition de niveau C1, en isolation",
        18: "Paires Nom-Préposition de niveau C1, en contexte",
        19: "Paires Nom-Préposition de niveau C1, en isolation",
        20: "Paires Nom-Préposition de niveau C1, en contexte",
        21: "Paires Nom-Préposition de niveau C1, en isolation",
        22: "Paires Nom-Préposition de niveau C1, en contexte",
        23: "Paires Nom-Préposition de niveau C1, en isolation",
        24: "Paires Nom-Préposition de niveau C1, en contexte",
        25: "Paires Nom-Préposition de niveau C1, en isolation",
        26: "Paires Nom-Préposition de niveau C1, en contexte",
    },

    praepositionen_artikel: {
        1: "Articles et Pronoms à la suite de Prépositions, en contexte",
        2: "Articles et Pronoms à la suite de Prépositions, en contexte",
        3: "Articles et Pronoms à la suite de Prépositions, en contexte",
        4: "Articles et Pronoms à la suite de Paires Verbe-Préposition, en contexte",
        5: "Articles et Pronoms à la suite de Paires Verbe-Préposition, en contexte",
        6: "Articles et Pronoms à la suite de Prépositions, en contexte",
        7: "Articles et Pronoms à la suite de Prépositions, en contexte",
        8: "Articles et Pronoms à la suite de Paires Verbe-Préposition, en contexte",
        9: "Articles et Pronoms à la suite de Paires Verbe-Préposition, en contexte",
    },

    artikel: {
        1: "Articles Définis <i>Der Die Das</i>, en isolation",
        2: "Articles Définis dans le cas Nominatif, en contexte",
        3: "Articles Définis dans le cas Accusatif, en contexte",
        4: "Articles Définis dans le cas Datif, en contexte",
        5: "Articles Définis Féminins, en contexte",
        6: "Articles Définis Masculins, en contexte",
        7: "Articles Définis Neutres, en contexte",
        8: "Articles Définis Pluriels, en contexte",
        9: "Articles Définis dans les cas Nominatif, Accusatif et Datif, en contexte",
        10: "Articles Définis dans les cas Nominatif, Accusatif et Datif, en contexte",
        11: "Articles Indéfinis <i>Ein</i>, en isolation",
        12: "Articles Indéfinis dans le cas Nominatif, en contexte",
        13: "Articles Indéfinis dans le cas Accusatif, en contexte",
        14: "Articles Indéfinis dans le cas Datif, en contexte",
        15: "Articles Indéfinis Féminins, en contexte",
        16: "Articles Indéfinis Masculins, en contexte",
        17: "Articles Indéfinis Neutres, en contexte",
        18: "Articles Indéfinis dans les cas Nominatif, Accusatif et Datif, en contexte",
        19: "Articles Indéfinis dans les cas Nominatif, Accusatif et Datif, en contexte",
        20: "Articles Négatifs <i>Kein</i>, en isolation",
        21: "Articles Négatifs <i>Kein</i>, en contexte",
        22: "Articles Posséssifs des Pronoms Singuliers (Ich, Du, Er, Sie, Es), en isolation",
        23: "Articles Posséssifs des Pronoms Singuliers (Ich, Du, Er, Sie, Es), en contexte",
        24: "Articles Posséssifs des Pronoms Pluriels (Wir, Ihr, Sie) et du Pronom Formel, en isolation",
        25: "Articles Posséssifs des Pronoms Pluriels (Wir, Ihr, Sie) et du Pronom Formel, en contexte",

        26: "Articles Démonstratifs <em>Diese</em>, en isolation",
        27: "Articles Démonstratifs <em>Diese</em>, en contexte",
        28: "Articles <em>Jede</em>, en isolation",
        29: "Articles <em>Jede</em>, en contexte",
        30: "Articles Définis à la suite de Prépositions dans les cas Accusatif et Datif, en contexte",
        31: "Articles Définis à la suite de Prépositions dans les cas Accusatif et Datif, en contexte",
        32: "Articles de niveau A2, en isolation",
        33: "Articles de niveau A2, en contexte",

        34: "Articles Définis, Indéfinis et Négatifs dans le cas Génitif, en isolation",
        35: "Articles Définis, Indéfinis et Négatifs dans le cas Génitif, en contexte",
        36: "Articles <em>Diese</em> et <em>Jede</em> dans le cas Génitif, en isolation",
        37: "Articles <em>Diese</em> et <em>Jede</em> dans le cas Génitif, en contexte",
        38: "Articles Posséssifs dans le cas Génitif, en isolation",
        39: "Articles Posséssifs dans le cas Génitif, en contexte",

        40: "Articles <em>Jene</em>, <em>Eine der</em> et <em>Irgendeine</em>, en isolation",
        41: "Articles <em>Jene</em>, <em>Eine der</em> et <em>Irgendeine</em>, en contexte",

        42: "Articles <em>Diejenige</em> et <em>Dieselbe</em>, en isolation",
        43: "Articles <em>Diejenige</em> et <em>Dieselbe</em>, en contexte",
    },

    artikel_genus: {
        1: "Articles Définis, en isolation",
        2: "Articles Définis, en isolation",
        3: "Articles Définis, en isolation",
        4: "Articles Définis, en isolation",
        5: "Articles Définis, en isolation",
        6: "Articles Définis, en isolation",
        7: "Articles Définis, en isolation",
        8: "Articles Définis, en isolation",
        9: "Articles Définis, en isolation",
        10: "Articles Définis, en isolation",
        11: "Articles Définis, en isolation",
        12: "Articles Définis, en isolation",
        13: "Articles Définis, en isolation",
        14: "Articles Définis, en isolation",
        15: "Articles Définis, en isolation",
        16: "Articles Définis, en isolation",
        17: "Articles Définis, en isolation",
        18: "Articles Définis, en isolation",
        19: "Articles Définis, en isolation",
        20: "Articles Définis, en isolation",

        21: "Articles Définis, en isolation",
        22: "Articles Définis, en isolation",
        23: "Articles Définis, en isolation",
        24: "Articles Définis, en isolation",
        25: "Articles Définis, en isolation",
        26: "Articles Définis, en isolation",
        27: "Articles Définis, en isolation",
        28: "Articles Définis, en isolation",
        29: "Articles Définis, en isolation",
        30: "Articles Définis, en isolation",
        31: "Articles Définis, en isolation",
        32: "Articles Définis, en isolation",
        33: "Articles Définis, en isolation",
        34: "Articles Définis, en isolation",
        35: "Articles Définis, en isolation",

        36: "Articles Définis, en isolation",
        37: "Articles Définis, en isolation",
        38: "Articles Définis, en isolation",
        39: "Articles Définis, en isolation",
        40: "Articles Définis, en isolation",
        41: "Articles Définis, en isolation",
        42: "Articles Définis, en isolation",
        43: "Articles Définis, en isolation",
        44: "Articles Définis, en isolation",
        45: "Articles Définis, en isolation",
        46: "Articles Définis, en isolation",
        47: "Articles Définis, en isolation",
        48: "Articles Définis, en isolation",
        49: "Articles Définis, en isolation",
        50: "Articles Définis, en isolation",
        51: "Articles Définis, en isolation",
        52: "Articles Définis, en isolation",
        53: "Articles Définis, en isolation",
        54: "Articles Définis, en isolation",
        55: "Articles Définis, en isolation",
        56: "Articles Définis, en isolation",
        57: "Articles Définis, en isolation",
        58: "Articles Définis, en isolation",
        59: "Articles Définis, en isolation",
        60: "Articles Définis, en isolation",
        61: "Articles Définis, en isolation",
        62: "Articles Définis, en isolation",
        63: "Articles Définis, en isolation",
        64: "Articles Définis, en isolation",
        65: "Articles Définis, en isolation",
        66: "Articles Définis, en isolation",
        67: "Articles Définis, en isolation",
        68: "Articles Définis, en isolation",
        69: "Articles Définis, en isolation",
        70: "Articles Définis, en isolation",
        71: "Articles Définis, en isolation",
        72: "Articles Définis, en isolation",
        73: "Articles Définis, en isolation",
        74: "Articles Définis, en isolation",
        75: "Articles Définis, en isolation",
        76: "Articles Définis, en isolation",
        77: "Articles Définis, en isolation",
        78: "Articles Définis, en isolation",
        79: "Articles Définis, en isolation",
        80: "Articles Définis, en isolation",
        81: "Articles Définis, en isolation",
        82: "Articles Définis, en isolation",
        83: "Articles Définis, en isolation",
        84: "Articles Définis, en isolation",
        85: "Articles Définis, en isolation",
        86: "Articles Définis, en isolation",
        87: "Articles Définis, en isolation",
    },

    pronomen: {
        1: "Pronoms Nominatifs, en isolation",
        2: "Pronoms Nominatifs, en contexte",
        3: "Pronoms Accusatifs, en isolation",
        4: "Pronoms Accusatifs, en contexte",
        5: "Pronoms Datifs, en isolation",
        6: "Pronoms Datifs, en contexte",
        7: "Pronoms Accusatifs et Datifs, en contexte",
        8: "Pronoms Accusatifs et Datifs, en contexte",
        9: "Remplacer les objets accusatifs et datifs par des pronoms, en contexte",
        10: "Remplacer les objets accusatifs et datifs par des pronoms, en contexte",

        11: "Pronoms Réfléchis, en isolation",
        12: "Pronoms Réfléchis, en contexte",
        13: "Pronoms Accusatifs, Datifs et Réfléchis, en contexte",
        14: "Pronoms Accusatifs, Datifs et Réfléchis, en contexte",
        15: "Pronoms Posséssifs des Pronoms Singuliers (Ich, Du, Er, Sie, Es), en isolation",
        16: "Possessive Pronouns des Pronoms Singuliers (Ich, Du, Er, Sie, Es), en contexte",
        17: "Possessive Pronouns des Pronoms Pluriels (Wir, Ihr, Sie) et Formel, en isolation",
        18: "Possessive Pronouns des Pronoms Pluriels (Wir, Ihr, Sie) et Formel, en contexte",

        19: "Pronoms de niveau B1 <em>Nichts</em>, <em>Man</em>, <em>Jemand</em> etc., en isolation",
        20: "Pronoms de niveau B1 <em>Nichts</em>, <em>Man</em>, <em>Jemand</em> etc., en contexte",
        21: "Pronoms Relatifs Nominatifs, en contexte",
        22: "Pronoms Relatifs Accusatifs, en contexte",
        23: "Pronoms Relatifs Datifs, en contexte",
        24: "Pronoms Relatifs Genitifs, en contexte",
        25: "Pronoms Relatifs, en contexte",
        26: "Pronoms Relatifs, en contexte",

        27: "Pronoms Relatifs, en contexte",
        28: "Pronoms Relatifs, en contexte",
        29: "Pronoms Relatifs locaux (Position et Direction), en contexte",
    },

    konnektoren: {
        1: "Connecteurs de niveau A1, en isolation",
        2: "Connecteurs de niveau A1, en contexte",

        3: "Connecteurs de niveau A2, en isolation",
        4: "Connecteurs de niveau A2, en contexte",

        5: "Connecteurs de niveau B1, en isolation",
        6: "Connecteurs de niveau B1, en contexte",
        7: "Synonymes de Connecteurs de niveau B1, en isolation",

        8: "Connecteurs de niveau B2, en isolation",
        9: "Connecteurs de niveau B2, en contexte",
        10: "Connecteurs de niveau B2, en isolation",
        11: "Connecteurs de niveau B2, en contexte",
        12: "Synonymes de Connecteurs de niveau B2, en isolation",

        13: "Connecteurs de niveau C1, en isolation",
        14: "Connecteurs de niveau C1, en contexte",
        15: "Synonymes de Connecteurs de niveau C1, en isolation",
    },

    fragen: {
        1: 'Mots Interrogatifs de niveau A1, en isolation',
        2: 'Mots Interrogatifs de niveau A1, en contexte',

        3: 'Mots Interrogatifs de niveau A2, en isolation',
        4: 'Mots Interrogatifs de niveau A2, en contexte',

        5: 'Mots Interrogatifs de niveau B1, en isolation',
        6: 'Mots Interrogatifs de niveau B1, en contexte',

        7: 'Mots Interrogatifs de niveau B2, en isolation',
        8: 'Mots Interrogatifs de niveau B2, en contexte',
        9: 'Mots Interrogatifs de niveau B2, en isolation (Beaucoup de Welch)',
        10: 'Mots Interrogatifs de niveau B2, en contexte (Beaucoup de Welch)',

        11: 'Mots Interrogatifs de niveau C1, en isolation',
        12: 'Mots Interrogatifs de niveau C1, en contexte',
    },

    adverbien: {
        1: "Adverbes de niveau A1, en isolation",
        2: "Adverbes de niveau A1, en contexte",
        3: "Adverbes de niveau A1, en isolation",
        4: "Adverbes de niveau A1, en contexte",

        5: "Adverbes de niveau A2, en isolation",
        6: "Adverbes de niveau A2, en contexte",
        7: "Adverbes de niveau A2, en isolation",
        8: "Adverbes de niveau A2, en contexte",
        9: "Adverbes de niveau A2, en isolation",
        10: "Adverbes de niveau A2, en contexte",

        11: "Adverbes de niveau B1, en isolation",
        12: "Adverbes de niveau B1, en contexte",
        13: "Adverbes de niveau B1, en isolation",
        14: "Adverbes de niveau B1, en contexte",
        15: "Adverbes de niveau B1, en isolation",
        16: "Adverbes de niveau B1, en contexte",
        17: "Adverbes de niveau B1, en isolation",
        18: "Adverbes de niveau B1, en contexte",

        19: "Adverbes de niveau B2, en isolation",
        20: "Adverbes de niveau B2, en contexte",
        21: "Adverbes de niveau B2, en isolation",
        22: "Adverbes de niveau B2, en contexte",
        23: "Adverbes de niveau B2, en isolation",
        24: "Adverbes de niveau B2, en contexte",
        25: "Adverbes de niveau B2, en isolation",
        26: "Adverbes de niveau B2, en contexte",
        27: "Adverbes de niveau B2, en isolation",
        28: "Adverbes de niveau B2, en contexte",

        29: "Adverbes en Her- et Hin-, en isolation",
        30: "Adverbes en Her- et Hin-, en contexte",
        31: "Adverbes en -einander, en isolation",
        32: "Adverbes en -einander, en contexte",
        33: "Traductions d'Adverbes de niveau C1 du Français vers l'Allemand (Choix Multiple)",
        34: "Traductions d'Adverbes de niveau C1 de l'Allemand vers le Français (Choix Multiple)",
        35: "Traductions d'Adverbes de niveau C1 du Français vers l'Allemand (Choix Multiple)",
        36: "Traductions d'Adverbes de niveau C1 de l'Allemand vers le Français (Choix Multiple)",
        37: "Traductions d'Adverbes de niveau C1 du Français vers l'Allemand (Choix Multiple)",
        38: "Traductions d'Adverbes de niveau C1 de l'Allemand vers le Français (Choix Multiple)",
        39: "Traductions d'Adverbes de niveau C1 du Français vers l'Allemand (Choix Multiple)",
        40: "Traductions d'Adverbes de niveau C1 de l'Allemand vers le Français (Choix Multiple)",
        41: "Traductions d'Adverbes de niveau C1 du Français vers l'Allemand (Choix Multiple)",
        42: "Traductions d'Adverbes de niveau C1 de l'Allemand vers le Français (Choix Multiple)",
    },

    adjektive: {
        1: "Adjectifs de niveau A1, en isolation",
        2: "Adjectifs de niveau A1, en isolation",
        3: "Adjectifs de niveau A1, en isolation",
        4: "Antonymes d'Adjectifs de niveau A1, en isolation",
        5: "Antonymes d'Adjectifs de niveau A1, en isolation",
        6: "Comparatifs d'Adjectifs de niveau A1, en isolation",
        7: "Comparatifs d'Adjectifs de niveau A1, en isolation",
        8: "Comparatifs d'Adjectifs de niveau A1, en isolation",
        9: "Superlatifs d'Adjectifs de niveau A1, en isolation",
        10: "Superlatifs d'Adjectifs de niveau A1, en isolation",
        11: "Superlatifs d'Adjectifs de niveau A1, en isolation",
        12: "Conjonctions comparatives, en contexte",

        13: "Adjectifs de niveau A2, en isolation",
        14: "Adjectifs de niveau A2, en isolation",
        15: "Adjectifs de niveau A2, en isolation",
        16: "Antonymes d'Adjectifs de niveau A2, en isolation",
        17: "Antonymes d'Adjectifs de niveau A2, en isolation",
        18: "Comparatifs d'Adjectifs de niveau A2, en isolation",
        19: "Comparatifs d'Adjectifs de niveau A2, en isolation",
        20: "Comparatifs d'Adjectifs de niveau A2, en isolation",
        21: "Superlatifs d'Adjectifs de niveau A2, en isolation",
        22: "Superlatifs d'Adjectifs de niveau A2, en isolation",
        23: "Superlatifs d'Adjectifs de niveau A2, en isolation",

        24: "Traductions d'Adjectifs de niveau B1 de l'Allemand vers le Français (Choix Multiple)",
        25: "Traductions d'Adjectifs de niveau B1 de l'Allemand vers le Français (Choix Multiple)",
        26: "Traductions d'Adjectifs de niveau B1 de l'Allemand vers le Français (Choix Multiple)",
        27: "Traductions d'Adjectifs de niveau B1 du Français vers l'Allemand (Choix Multiple)",
        28: "Traductions d'Adjectifs de niveau B1 du Français vers l'Allemand (Choix Multiple)",
        29: "Traductions d'Adjectifs de niveau B1 du Français vers l'Allemand (Choix Multiple)",

        30: "Traductions d'Adjectifs de niveau B2 de l'Allemand vers le Français (Choix Multiple)",
        31: "Traductions d'Adjectifs de niveau B2 de l'Allemand vers le Français (Choix Multiple)",
        32: "Traductions d'Adjectifs de niveau B2 de l'Allemand vers le Français (Choix Multiple)",
        33: "Traductions d'Adjectifs de niveau B2 du Français vers l'Allemand (Choix Multiple)",
        34: "Traductions d'Adjectifs de niveau B2 du Français vers l'Allemand (Choix Multiple)",
        35: "Traductions d'Adjectifs de niveau B2 du Français vers l'Allemand (Choix Multiple)",
    },

    adjektivdeklinationen: {
        1: "Déclinations d'Adjectifs dans le cas Nominatif, en isolation",
        2: "Déclinations d'Adjectifs dans le cas Nominatif, en contexte",
        3: "Déclinations d'Adjectifs dans le cas Accusatif, en isolation",
        4: "Déclinations d'Adjectifs dans le cas Accusatif, en contexte",
        5: "Déclinations d'Adjectifs dans le cas Datif, en isolation",
        6: "Déclinations d'Adjectifs dans le cas Datif, en contexte",
        7: "Déclinations d'Adjectifs à la suite d'Articles Définis, en isolation",
        8: "Déclinations d'Adjectifs à la suite d'Articles Définis, en contexte",
        9: "Déclinations d'Adjectifs à la suite d'Articles Indéfinis, en isolation",
        10: "Déclinations d'Adjectifs à la suite d'Articles Indéfinis, en contexte",
        11: "Déclinations d'Adjectifs dans les cas Nominatif, Accusatif et Datif, en contexte",
        12: "Déclinations d'Adjectifs dans les cas Nominatif, Accusatif et Datif, en contexte",

        13: "Déclinations d'Adjectifs dans le cas Génitif, en isolation",
        14: "Déclinations d'Adjectifs dans le cas Génitif, en contexte",
        15: "Déclinations d'Adjectifs sans Article, en isolation",
        16: "Déclinations d'Adjectifs sans Article, en contexte",
        17: "Déclinations d'Adjectifs à la suite de l'Article Négatif \"Kein\", en isolation",
        18: "Déclinations d'Adjectifs à la suite de l'Article Négatif \"Kein\", en contexte",

        19: "Déclinations d'Adjectifs à la suite d'Articles Posséssifs, en isolation",
        20: "Déclinations d'Adjectifs à la suite d'Articles Posséssifs, en contexte",
        21: "Déclinations d'Adjectifs à la suite d'Articles Démonstratifs, en isolation",
        22: "Déclinations d'Adjectifs à la suite d'Articles Démonstratifs, en contexte",

        23: "Déclinations d'Adjectifs à la suite d'Articles singuliers \"etwas\", \"viel\", \"mehr\", en isolation",
        24: "Déclinations d'Adjectifs à la suite d'Articles singuliers \"etwas\", \"viel\", \"mehr\", en contexte",
        25: "Déclinations d'Adjectifs à la suite d'Articles pluriels \"alle\", \"viele\", en isolation",
        26: "Déclinations d'Adjectifs à la suite d'Articles pluriels \"alle\", \"viele\", en contexte",
        27: "Déclinations d'Adjectifs Comparatifs, en isolation",
        28: "Déclinations d'Adjectifs Comparatifs, en contexte",
        29: "Déclinations d'Adjectifs Superlatifs, en isolation",
        30: "Déclinations d'Adjectifs Superlatifs, en contexte",
    },

    verben: {
        1: "Traductions de Verbes de niveau A1 du Français vers l'Allemand",
        2: "Traductions de Verbes de niveau A1 du Français vers l'Allemand",
        3: "Traductions de Verbes de niveau A1 du Français vers l'Allemand",
        4: "Traductions de Verbes de niveau A1 du Français vers l'Allemand",
        5: "Traductions de Verbes de niveau A1 du Français vers l'Allemand",

        6: "Traductions de Verbes de niveau A2 du Français vers l'Allemand",
        7: "Traductions de Verbes de niveau A2 du Français vers l'Allemand",
        8: "Traductions de Verbes de niveau A2 du Français vers l'Allemand",
        9: "Traductions de Verbes de niveau A2 du Français vers l'Allemand",
        10: "Traductions de Verbes de niveau A2 du Français vers l'Allemand",

        11: "Traductions de Verbes de niveau B1 du Français vers l'Allemand (Choix Multiple)",
        12: "Traductions de Verbes de niveau B1 du Français vers l'Allemand (Choix Multiple)",
        13: "Traductions de Verbes de niveau B1 du Français vers l'Allemand (Choix Multiple)",
        14: "Traductions de Verbes de niveau B1 du Français vers l'Allemand (Choix Multiple)",
        15: "Traductions de Verbes de niveau B1 du Français vers l'Allemand (Choix Multiple)",
        16: "Traductions de Verbes de niveau B1 de l'Allemand vers le Français (Choix Multiple)",
        17: "Traductions de Verbes de niveau B1 de l'Allemand vers le Français (Choix Multiple)",
        18: "Traductions de Verbes de niveau B1 de l'Allemand vers le Français (Choix Multiple)",
        19: "Traductions de Verbes de niveau B1 de l'Allemand vers le Français (Choix Multiple)",
        20: "Traductions de Verbes de niveau B1 de l'Allemand vers le Français (Choix Multiple)",

        21: "Traductions de Verbes de niveau B2 du Français vers l'Allemand (Choix Multiple)",
        22: "Traductions de Verbes de niveau B2 du Français vers l'Allemand (Choix Multiple)",
        23: "Traductions de Verbes de niveau B2 du Français vers l'Allemand (Choix Multiple)",
        24: "Traductions de Verbes de niveau B2 du Français vers l'Allemand (Choix Multiple)",
        25: "Traductions de Verbes de niveau B2 du Français vers l'Allemand (Choix Multiple)",
        26: "Traductions de Verbes de niveau B2 de l'Allemand vers le Français (Choix Multiple)",
        27: "Traductions de Verbes de niveau B2 de l'Allemand vers le Français (Choix Multiple)",
        28: "Traductions de Verbes de niveau B2 de l'Allemand vers le Français (Choix Multiple)",
        29: "Traductions de Verbes de niveau B2 de l'Allemand vers le Français (Choix Multiple)",
        30: "Traductions de Verbes de niveau B2 de l'Allemand vers le Français (Choix Multiple)",

        31: "Traductions de Verbes de niveau C1 du Français vers l'Allemand (Choix Multiple)",
        32: "Traductions de Verbes de niveau C1 du Français vers l'Allemand (Choix Multiple)",
        33: "Traductions de Verbes de niveau C1 du Français vers l'Allemand (Choix Multiple)",
        34: "Traductions de Verbes de niveau C1 du Français vers l'Allemand (Choix Multiple)",
        35: "Traductions de Verbes de niveau C1 du Français vers l'Allemand (Choix Multiple)",
        36: "Traductions de Verbes de niveau C1 de l'Allemand vers le Français (Choix Multiple)",
        37: "Traductions de Verbes de niveau C1 de l'Allemand vers le Français (Choix Multiple)",
        38: "Traductions de Verbes de niveau C1 de l'Allemand vers le Français (Choix Multiple)",
        39: "Traductions de Verbes de niveau C1 de l'Allemand vers le Français (Choix Multiple)",
        40: "Traductions de Verbes de niveau C1 de l'Allemand vers le Français (Choix Multiple)",
    },

    trennbare_verben: {
        1: "Verbes (un)trennbare de niveau A1 aidé de la racine",
        2: "Verbes (un)trennbare de niveau A1 aidé du préfixe",
        3: "Verbes (un)trennbare de niveau A1 sans aide",

        4: "Verbes (un)trennbare de niveau A2 aidé de la racine",
        5: "Verbes (un)trennbare de niveau A2 aidé du préfixe",
        6: "Verbes (un)trennbare de niveau A2 sans aide",

        7: "Verbes (un)trennbare de niveau B1 aidé de la racine",
        8: "Verbes (un)trennbare de niveau B1 aidé de la racine",
        9: "Verbes (un)trennbare de niveau B1 aidé de la racine",
        10: "Verbes (un)trennbare de niveau B1 aidé de la racine",
        11: "Verbes (un)trennbare de niveau B1 aidé du préfixe",
        12: "Verbes (un)trennbare de niveau B1 aidé du préfixe",
        13: "Verbes (un)trennbare de niveau B1 aidé du préfixe",
        14: "Verbes (un)trennbare de niveau B1 aidé du préfixe",
        15: "Verbes (un)trennbare de niveau B1 sans aide",
        16: "Verbes (un)trennbare de niveau B1 sans aide",
        17: "Verbes (un)trennbare de niveau B1 sans aide",
        18: "Verbes (un)trennbare de niveau B1 sans aide",

        19: "Verbes (un)trennbare de niveau B2 aidé de la racine",
        20: "Verbes (un)trennbare de niveau B2 aidé de la racine",
        21: "Verbes (un)trennbare de niveau B2 aidé de la racine",
        22: "Verbes (un)trennbare de niveau B2 aidé de la racine",
        23: "Verbes (un)trennbare de niveau B2 aidé du préfixe",
        24: "Verbes (un)trennbare de niveau B2 aidé du préfixe",
        25: "Verbes (un)trennbare de niveau B2 aidé du préfixe",
        26: "Verbes (un)trennbare de niveau B2 aidé du préfixe",
        27: "Verbes (un)trennbare de niveau B2 sans aide",
        28: "Verbes (un)trennbare de niveau B2 sans aide",
        29: "Verbes (un)trennbare de niveau B2 sans aide",
        30: "Verbes (un)trennbare de niveau B2 sans aide",
    },

    nomen_verben_verbindungen: {
        1: "Combinaisons Nom-Verbe de niveau B1 sans le Nom, en isolation",
        2: "Combinaisons Nom-Verbe de niveau B1 sans le Verbe, en isolation",
        3: "Combinaisons Nom-Verbe de niveau B1 sans le Nom, en contexte",
        4: "Combinaisons Nom-Verbe de niveau B1 sans le Verbe, en contexte",

        5: "Combinaisons Nom-Verbe de niveau B2 sans le Nom, en isolation",
        6: "Combinaisons Nom-Verbe de niveau B2 sans le Verbe, en isolation",
        7: "Combinaisons Nom-Verbe de niveau B2 sans le Nom, en contexte",
        8: "Combinaisons Nom-Verbe de niveau B2 sans le Verbe, en contexte",
    },

    praesens: {
        1: "Présent de Verbes de niveau A1, en isolation",
        2: "Présent de Verbes de niveau A1, en isolation",
        3: "Présent de Verbes de niveau A1, en isolation",
        4: "Présent de Verbes de niveau A1, en isolation",
        5: "Présent de Verbes de niveau A1, en isolation",
        6: "Présent de Verbes de niveau A1, en isolation",
        7: "Présent de Verbes de niveau A1, en isolation",
        8: "Présent de Verbes de niveau A1, en isolation",
        9: "Présent de Verbes de niveau A1, en isolation",
        10: "Présent de Verbes de niveau A1, en isolation",
        11: "Présent de Verbes de niveau A1, en isolation",
        12: "Présent de Verbes de niveau A1, en isolation",
        13: "Présent de Verbes de niveau A1, en isolation",
        14: "Présent de Verbes de niveau A1, en isolation",
        15: "Présent de Verbes de niveau A1, en isolation",
        16: "Présent de Verbes de niveau A1, en isolation",
        17: "Présent de Verbes de niveau A1, en isolation",
        18: "Présent de Verbes de niveau A1, en isolation",
        19: "Présent de Verbes de niveau A1, en isolation",
        20: "Présent de Verbes de niveau A1, en isolation",

        21: "Présent de Verbes de niveau A2, en isolation",
        22: "Présent de Verbes de niveau A2, en isolation",
        23: "Présent de Verbes de niveau A2, en isolation",
        24: "Présent de Verbes de niveau A2, en isolation",
        25: "Présent de Verbes de niveau A2, en isolation",
        26: "Présent de Verbes de niveau A2, en isolation",
        27: "Présent de Verbes de niveau A2, en isolation",
        28: "Présent de Verbes de niveau A2, en isolation",
        29: "Présent de Verbes de niveau A2, en isolation",
        30: "Présent de Verbes de niveau A2, en isolation",
        31: "Présent de Verbes de niveau A2, en isolation",
        32: "Présent de Verbes de niveau A2, en isolation",
        33: "Présent de Verbes de niveau A2, en isolation",
        34: "Présent de Verbes de niveau A2, en isolation",
        35: "Présent de Verbes de niveau A2, en isolation",
        36: "Présent de Verbes de niveau A2, en isolation",
        37: "Présent de Verbes de niveau A2, en isolation",
        38: "Présent de Verbes de niveau A2, en isolation",
        39: "Présent de Verbes de niveau A2, en isolation",
        40: "Présent de Verbes de niveau A2, en isolation",
    },

    partizip_II: {
        1: "Participe Passé (Partizip II) de Verbes de niveau A1",
        2: "Participe Passé (Partizip II) de Verbes de niveau A1",
        3: "Participe Passé (Partizip II) de Verbes de niveau A1",
        4: "Participe Passé (Partizip II) de Verbes de niveau A1",
        5: "Participe Passé (Partizip II) de Verbes de niveau A1",

        6: "Participe Passé (Partizip II) de Verbes de niveau A2",
        7: "Participe Passé (Partizip II) de Verbes de niveau A2",
        8: "Participe Passé (Partizip II) de Verbes de niveau A2",
        9: "Participe Passé (Partizip II) de Verbes de niveau A2",
        10: "Participe Passé (Partizip II) de Verbes de niveau A2",

        11: "Participe Passé (Partizip II) de Verbes de niveau B1",
        12: "Participe Passé (Partizip II) de Verbes de niveau B1",
        13: "Participe Passé (Partizip II) de Verbes de niveau B1",
        14: "Participe Passé (Partizip II) de Verbes de niveau B1",
        15: "Participe Passé (Partizip II) de Verbes de niveau B1",
        16: "Participe Passé (Partizip II) de Verbes de niveau B1",
        17: "Participe Passé (Partizip II) de Verbes de niveau B1",
        18: "Participe Passé (Partizip II) de Verbes de niveau B1",
        19: "Participe Passé (Partizip II) de Verbes de niveau B1",
        20: "Participe Passé (Partizip II) de Verbes de niveau B1",

        21: "Participe Passé (Partizip II) de Verbes de niveau B2",
        22: "Participe Passé (Partizip II) de Verbes de niveau B2",
        23: "Participe Passé (Partizip II) de Verbes de niveau B2",
        24: "Participe Passé (Partizip II) de Verbes de niveau B2",
        25: "Participe Passé (Partizip II) de Verbes de niveau B2",
        26: "Participe Passé (Partizip II) de Verbes de niveau B2",
        27: "Participe Passé (Partizip II) de Verbes de niveau B2",
        28: "Participe Passé (Partizip II) de Verbes de niveau B2",
        29: "Participe Passé (Partizip II) de Verbes de niveau B2",
        30: "Participe Passé (Partizip II) de Verbes de niveau B2",

        31: "Participe Passé (Partizip II) de Verbes de niveau C1",
        32: "Participe Passé (Partizip II) de Verbes de niveau C1",
        33: "Participe Passé (Partizip II) de Verbes de niveau C1",
        34: "Participe Passé (Partizip II) de Verbes de niveau C1",
        35: "Participe Passé (Partizip II) de Verbes de niveau C1",
        36: "Participe Passé (Partizip II) de Verbes de niveau C1",
        37: "Participe Passé (Partizip II) de Verbes de niveau C1",
        38: "Participe Passé (Partizip II) de Verbes de niveau C1",
        39: "Participe Passé (Partizip II) de Verbes de niveau C1",
        40: "Participe Passé (Partizip II) de Verbes de niveau C1",
    },

    praeteritum: {
        1: "Préterit (Präteritum) des Verbes les plus importants",

        2: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau A1",
        3: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau A1",
        4: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau A1",
        5: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau A1",
        6: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau A1",
        7: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau A2",
        8: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau A2",
        9: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau A2",
        10: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau A2",
        11: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau A2",

        12: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B1",
        13: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B1",
        14: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B1",
        15: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B1",
        16: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B1",
        17: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B1",
        18: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B1",
        19: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B1",
        20: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B1",
        21: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B1",

        22: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B2",
        23: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B2",
        24: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B2",
        25: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B2",
        26: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B2",
        27: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B2",
        28: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B2",
        29: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B2",
        30: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B2",
        31: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau B2",

        32: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau C1",
        33: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau C1",
        34: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau C1",
        35: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau C1",
        36: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau C1",
        37: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau C1",
        38: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau C1",
        39: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau C1",
        40: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau C1",
        41: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) de Verbes de niveau C1",
    },

    praeteritum_partizip_II: {
        1: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) des Verbes les plus importants",

        2: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau A1",
        3: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau A1",
        4: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau A1",
        5: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau A1",
        6: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau A1",
        7: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau A2",
        8: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau A2",
        9: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau A2",
        10: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau A2",
        11: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau A2",

        12: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B1",
        13: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B1",
        14: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B1",
        15: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B1",
        16: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B1",
        17: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B1",
        18: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B1",
        19: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B1",
        20: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B1",
        21: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B1",

        22: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B2",
        23: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B2",
        24: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B2",
        25: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B2",
        26: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B2",
        27: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B2",
        28: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B2",
        29: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B2",
        30: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B2",
        31: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau B2",

        32: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau C1",
        33: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau C1",
        34: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau C1",
        35: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau C1",
        36: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau C1",
        37: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau C1",
        38: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau C1",
        39: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau C1",
        40: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau C1",
        41: "Préterit (Präteritum) (3<sup>rd</sup> Personne du Singulier) et Participe Passé (Partizip II) de Verbes de niveau C1",
    },

    imperativ: {
        1: "Imperatif de Verbes de niveau A1",
        2: "Imperatif de Verbes de niveau A1",
        3: "Imperatif de Verbes de niveau A1",
        4: "Imperatif de Verbes de niveau A1",
        5: "Imperatif de Verbes de niveau A1",
        6: "Imperatif de Verbes de niveau A1",

        7: "Imperatif de Verbes de niveau A2",
        8: "Imperatif de Verbes de niveau A2",
        9: "Imperatif de Verbes de niveau A2",
        10: "Imperatif de Verbes de niveau A2",
        11: "Imperatif de Verbes de niveau A2",
        12: "Imperatif de Verbes de niveau A2",
    },

    konjunktiv_II: {
        1: "Subjonctif II (Konjunktiv II) des Verbes les plus importants",
    },

    konjunktiv_I: {
        1: "Subjonctif I (Konjunktiv I) de Verbes de niveau A1",
        2: "Subjonctif I (Konjunktiv I) de Verbes de niveau A1",
        3: "Subjonctif I (Konjunktiv I) de Verbes de niveau A1",
        4: "Subjonctif I (Konjunktiv I) de Verbes de niveau A1",
        5: "Subjonctif I (Konjunktiv I) de Verbes de niveau A1",
        6: "Subjonctif I (Konjunktiv I) de Verbes de niveau A1",
    },

    partizip_I: {
        1: "Participe Présent (Partizip I) de Verbes de niveau A1",
        2: "Participe Présent (Partizip I) de Verbes de niveau A1",
        3: "Participe Présent (Partizip I) de Verbes de niveau A1",
        4: "Participe Présent (Partizip I) de Verbes de niveau A1",
        5: "Participe Présent (Partizip I) de Verbes de niveau A1",
    },
}
