from data.data_processing.units import (
    praepositionen_grammatik, praepositionen_verben, praepositionen_adjektive, praepositionen_nomen,
    praepositionen_artikel, praepositionen_adverbien,
    artikel, artikel_genus, pronomen, konnektoren, fragen, adverbien, wortstellung,
    adjektive, adjektivdeklinationen,
    verben, trennbare_verben, nomen_verben_verbindungen,
    praesens, imperativ, partizip_II, praeteritum, praeteritum_partizip_II, konjunktiv_II, konjunktiv_I, partizip_I,
)

# bullet point \u25CF

INSTRUCTION_FR = {

    praepositionen_grammatik: {
        1: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        2: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        3: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        4: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        5: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        6: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        7: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        8: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        9: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        10: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        11: "Traduisez la préposition ci-dessous :",
        12: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        13: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        14: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        15: "Traduisez la préposition ci-dessous :",
        16: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        17: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        18: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        19: "Traduisez la préposition ci-dessous :",
        20: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        21: "Traduisez la préposition ci-dessous :",
        22: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        23: "Traduisez le groupe prépositionel ci-dessous :",
        24: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        25: "Traduisez la postposition ou la circumposition ci-dessous :",
        26: "Complétez la phrase ci-dessous avec la postposition ou la circumposition qui convient :",
    },

    praepositionen_verben: {
        1: "Écrivez la préposition qui correspond au verbe suivant :",
        2: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        3: "Écrivez la préposition qui correspond au verbe suivant :",
        4: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        5: "Écrivez la préposition qui correspond au verbe suivant :",
        6: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        7: "Écrivez la préposition qui correspond au verbe suivant :",
        8: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        9: "Complétez la phrase suivante avec l'Adverbe Pronominal en Da- qui convient :",
        10: "Complétez la phrase suivante avec l'Adverbe Pronominal en Da- qui convient :",

        11: "Écrivez la préposition qui correspond au verbe suivant :",
        12: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        13: "Écrivez la préposition qui correspond au verbe suivant :",
        14: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        15: "Écrivez la préposition qui correspond au verbe suivant :",
        16: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        17: "Écrivez la préposition qui correspond au verbe suivant :",
        18: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        19: "Écrivez la préposition qui correspond au verbe suivant :",
        20: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        21: "Écrivez la préposition qui correspond au verbe suivant :",
        22: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        23: "Écrivez la préposition qui correspond au verbe suivant :",
        24: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        25: "Écrivez la préposition qui correspond au verbe suivant :",
        26: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        27: "Écrivez la préposition qui correspond au verbe suivant :",
        28: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        29: "Écrivez la préposition qui correspond au verbe suivant :",
        30: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        31: "Écrivez la préposition qui correspond au verbe suivant :",
        32: "Complétez la phrase ci-dessous avec la préposition qui convient :",
    },

    praepositionen_adjektive: {
        1: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        2: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        3: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        4: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        5: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        6: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        7: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        8: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        9: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        10: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        11: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        12: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        13: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        14: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        15: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        16: "Complétez la phrase ci-dessous avec la préposition qui convient :",
    },

    praepositionen_nomen: {
        1: "Écrivez la préposition qui correspond au nom suivant :",
        2: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        3: "Écrivez la préposition qui correspond au nom suivant :",
        4: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        5: "Écrivez la préposition qui correspond au nom suivant :",
        6: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        7: "Écrivez la préposition qui correspond au nom suivant :",
        8: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        9: "Écrivez la préposition qui correspond au nom suivant :",
        10: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        11: "Écrivez la préposition qui correspond au nom suivant :",
        12: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        13: "Écrivez la préposition qui correspond au nom suivant :",
        14: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        15: "Écrivez la préposition qui correspond au nom suivant :",
        16: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        17: "Écrivez la préposition qui correspond au nom suivant :",
        18: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        19: "Écrivez la préposition qui correspond au nom suivant :",
        20: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        21: "Écrivez la préposition qui correspond au nom suivant :",
        22: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        23: "Écrivez la préposition qui correspond au nom suivant :",
        24: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        25: "Écrivez la préposition qui correspond au nom suivant :",
        26: "Complétez la phrase ci-dessous avec la préposition qui convient :",
    },

    praepositionen_artikel: {
        1: "Complétez la phrase suivante avec l'article ou le pronom qui convient :",
        2: "Complétez la phrase suivante avec l'article ou le pronom qui convient :",
        3: "Complétez la phrase suivante avec l'article ou le pronom qui convient :",
        4: "Complétez la phrase suivante avec l'article ou le pronom qui convient :",
        5: "Complétez la phrase suivante avec l'article ou le pronom qui convient :",
        6: "Complétez la phrase suivante avec l'article ou le pronom qui convient :",
        7: "Complétez la phrase suivante avec l'article ou le pronom qui convient :",
        8: "Complétez la phrase suivante avec l'article ou le pronom qui convient :",
        9: "Complétez la phrase suivante avec l'article ou le pronom qui convient :",
    },

    praepositionen_adverbien: {
        1: "Something"
    },

    artikel: {
        1: "Écrivez l'article défini qui correspond au cas et au genre fournis :",
        2: "Complétez la phrase suivante avec l'article défini nominatif qui convient :",
        3: "Complétez la phrase suivante avec l'article défini accusatif qui convient :",
        4: "Complétez la phrase suivante avec l'article défini datif qui convient :",
        5: "Complétez la phrase suivante avec l'article défini féminin qui convient :",
        6: "Complétez la phrase suivante avec l'article défini masculin qui convient :",
        7: "Complétez la phrase suivante avec l'article défini neutre qui convient :",
        8: "Complétez la phrase suivante avec l'article défini pluriel qui convient :",
        9: "Complétez la phrase suivante avec l'article défini qui convient :",
        10: "Complétez la phrase suivante avec l'article défini qui convient :",
        11: "Écrivez l'article indéfini qui correspond au cas et au genre fournis :",
        12: "Complétez la phrase suivante avec l'article indéfini nominatif qui convient :",
        13: "Complétez la phrase suivante avec l'article indéfini accusatif qui convient :",
        14: "Complétez la phrase suivante avec l'article indéfini datif qui convient :",
        15: "Complétez la phrase suivante avec l'article indéfini féminin qui convient :",
        16: "Complétez la phrase suivante avec l'article indéfini masculin qui convient :",
        17: "Complétez la phrase suivante avec l'article indéfini neutre qui convient :",
        18: "Complétez la phrase suivante avec l'article indéfini qui convient :",
        19: "Complétez la phrase suivante avec l'article indéfini qui convient :",
        20: "Écrivez le mot-clé qui correspond au cas et au genre fournis :",
        21: "Complétez la phrase suivante avec le mot Kein qui convient :",
        22: "Écrivez l'article possessif qui correspond au cas et au genre fournis :",
        23: "Complétez la phrase suivante avec l'article possessif qui convient."
            "<br><br>Tous les articles possessifs sont basés sur des pronoms singuliers (Ich, Du, Er, Sie, Es).",
        24: "Écrivez l'article possessif qui correspond au cas et au genre fournis.",
        25: "Complétez la phrase suivante avec l'article possessif qui convient."
            "<br><br>Tous les articles possessifs sont basés sur des pronoms pluriels (Wir, Ihr, Sie) ou formels.",

        26: "Rédigez l'article démonstratif qui correspond au cas et au genre fournis :",
        27: "Complétez la phrase suivante avec l'article démonstratif qui convient :",
        28: "Écrivez le mot \"jede\" qui correspond au cas et au genre fournis :",
        29: "Complétez la phrase suivante avec le mot \"jede\" qui convient :",
        30: "Complétez la phrase suivante avec l'article qui convient :",
        31: "Complétez la phrase suivante avec l'article qui convient :",
        32: "Traduisez l'article suivant :",
        33: "Complétez la phrase suivante avec l'article qui convient :",

        34: "Rédigez l'article qui correspond au cas et au genre fournis :",
        35: "Complétez la phrase suivante avec l'article génitif qui convient :",
        36: "Rédigez l'article qui correspond au cas et au genre fournis :",
        37: "Complétez la phrase suivante avec l'article génitif qui convient :",
        38: "Écrivez l'article possessif qui correspond au cas et au genre fournis :",
        39: "Complétez la phrase suivante avec l'article possessif qui convient :",

        40: "Traduisez l'article suivant en fonction du cas et du genre fournis :",
        41: "Complétez la phrase suivante avec l'article qui convient :",

        42: "Traduisez l'article suivant en fonction du cas et du genre fournis :",
        43: "Complétez la phrase suivante avec l'article qui convient :",
    },

    artikel_genus: {
        1: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        2: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        3: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        4: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        5: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        6: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        7: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        8: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        9: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        10: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        11: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        12: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        13: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        14: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        15: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        16: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        17: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        18: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        19: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        20: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",

        21: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        22: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        23: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        24: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        25: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        26: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        27: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        28: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        29: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        30: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        31: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        32: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        33: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        34: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        35: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",

        36: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        37: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        38: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        39: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        40: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        41: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        42: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        43: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        44: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        45: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        46: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        47: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        48: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        49: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        50: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        51: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        52: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        53: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        54: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        55: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        56: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        57: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        58: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        59: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        60: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        61: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        62: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        63: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        64: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        65: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        66: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        67: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        68: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        69: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        70: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        71: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        72: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        73: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        74: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        75: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        76: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        77: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        78: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        79: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        80: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        81: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        82: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        83: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        84: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        85: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        86: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        87: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
    },

    pronomen: {
        1: "Écrivez le pronom nominatif qui correspond à la personne donnée :",
        2: "Complétez la phrase suivante avec le pronom nominatif qui convient :",
        3: "Écrivez le pronom accusatif qui correspond à la personne donnée :",
        4: "Complétez la phrase suivante avec le pronom accusatif qui convient :",
        5: "Écrivez le pronom datif qui correspond à la personne donnée :",
        6: "Complétez la phrase suivante avec le pronom datif qui convient :",
        7: "Complétez la phrase suivante avec le pronom qui convient :",
        8: "Complétez la phrase suivante avec le pronom qui convient :",
        9: "Remplacez l'objet indiqué par le pronom approprié :",
        10: "Remplacez l'objet indiqué par le pronom approprié :",

        11: "Écrivez le pronom réfléchi qui correspond à la personne et au cas donnés :",
        12: "Complétez la phrase suivante avec le pronom réfléchi qui convient :",
        13: "Complétez la phrase suivante avec le pronom qui convient :",
        14: "Complétez la phrase suivante avec le pronom qui convient :",
        15: "Fournissez la traduction du pronom possessif qui correspond au cas et au genre fournis :",
        16: "Complétez la phrase suivante avec le pronom possessif qui convient :",
        17: "Fournissez la traduction du pronom possessif qui correspond au cas et au genre fournis :",
        18: "Complétez la phrase suivante avec le pronom possessif qui convient :",

        19: "Traduisez le pronom suivant :",
        20: "Complétez la phrase suivante avec le pronom qui convient :",
        21: "Complétez la phrase suivante avec le pronom relatif nominatif qui convient :",
        22: "Complétez la phrase suivante avec le pronom relatif accusatif qui convient :",
        23: "Complétez la phrase suivante avec le pronom relatif datif qui convient :",
        24: "Complétez la phrase suivante avec le pronom relatif génitif qui convient :",
        25: "Complétez la phrase suivante avec le pronom relatif qui convient :",
        26: "Complétez la phrase suivante avec le pronom relatif qui convient :",

        27: "Complétez la phrase suivante avec le pronom relatif qui convient :",
        28: "Complétez la phrase suivante avec le pronom relatif qui convient :",
        29: "Complétez la phrase suivante avec le pronom relatif qui convient – il peut y avoir plusieurs options :",
    },

    konnektoren: {
        1: "Traduisez le connecteur suivant :",
        2: "Complétez la phrase suivante avec le connecteur qui convient :",

        3: "Traduisez le connecteur suivant :",
        4: "Complétez la phrase suivante avec le connecteur qui convient :",

        5: "Traduisez le connecteur suivant :",
        6: "Complétez la phrase suivante avec le connecteur qui convient :",
        7: "Traduisez le connecteur suivant :",
        8: "Complétez la phrase suivante avec le connecteur qui convient :",
        9: "Traduisez le connecteur suivant :",
        10: "Complétez la phrase suivante avec le connecteur qui convient :",
        11: "Trouvez un synonyme pour le connecteur suivant :",

        12: "Traduisez le connecteur suivant :",
        13: "Complétez la phrase suivante avec le connecteur qui convient :",
        14: "Traduisez le connecteur suivant :",
        15: "Complétez la phrase suivante avec le connecteur qui convient :",
        16: "Traduisez le connecteur suivant :",
        17: "Complétez la phrase suivante avec le connecteur qui convient :",
        18: "Trouvez un synonyme pour le connecteur suivant :",

        19: "Traduisez le connecteur suivant :",
        20: "Complétez la phrase suivante avec le connecteur qui convient :",
        21: "Traduisez le connecteur suivant :",
        22: "Complétez la phrase suivante avec le connecteur qui convient :",
        23: "Traduisez le connecteur suivant :",
        24: "Complétez la phrase suivante avec le connecteur qui convient :",
        25: "Trouvez un synonyme pour le connecteur suivant :",
        26: "Trouvez un synonyme pour le connecteur suivant :",
    },

    fragen: {
        1: "Traduisez le mot interrogatif suivant :",
        2: "Complétez la phrase suivante avec le mot interrogatif qui convient :",

        3: "Traduisez le mot interrogatif suivant :",
        4: "Complétez la phrase suivante avec le mot interrogatif qui convient :",

        5: "Traduisez le mot interrogatif suivant :",
        6: "Complétez la phrase suivante avec le mot interrogatif qui convient :",

        7: "Traduisez le mot interrogatif suivant :",
        8: "Complétez la phrase suivante avec le mot interrogatif qui convient :",
        9: "Traduisez le mot interrogatif suivant :",
        10: "Complétez la phrase suivante avec le mot interrogatif qui convient :",

        11: "Traduisez le mot interrogatif suivant :",
        12: "Complétez la phrase suivante avec le mot interrogatif qui convient :",
    },

    adverbien: {
        1: "Traduisez l'adverbe suivant :",
        2: "Complétez la phrase suivante avec l'adverbe qui convient :",
        3: "Traduisez l'adverbe suivant :",
        4: "Complétez la phrase suivante avec l'adverbe qui convient :",

        5: "Traduisez l'adverbe suivant :",
        6: "Complétez la phrase suivante avec l'adverbe qui convient :",
        7: "Traduisez l'adverbe suivant :",
        8: "Complétez la phrase suivante avec l'adverbe qui convient :",
        9: "Trouvez un synonyme pour l'adverbe suivant :",
        10: "Écrivez l'antonyme de l'adverbe suivant :",

        11: "Traduisez l'adverbe suivant :",
        12: "Complétez la phrase suivante avec l'adverbe qui convient :",
        13: "Traduisez l'adverbe suivant :",
        14: "Complétez la phrase suivante avec l'adverbe qui convient :",
        15: "Traduisez l'adverbe suivant :",
        16: "Complétez la phrase suivante avec l'adverbe qui convient :",
        17: "Traduisez l'adverbe suivant :",
        18: "Complétez la phrase suivante avec l'adverbe qui convient :",
        19: "Trouvez un synonyme pour l'adverbe suivant :",
        20: "Écrivez l'antonyme de l'adverbe suivant :",

        21: "Traduisez l'adverbe suivant :",
        22: "Complétez la phrase suivante avec l'adverbe qui convient :",
        23: "Traduisez l'adverbe suivant :",
        24: "Complétez la phrase suivante avec l'adverbe qui convient :",
        25: "Traduisez l'adverbe suivant :",
        26: "Complétez la phrase suivante avec l'adverbe qui convient :",
        27: "Traduisez l'adverbe suivant :",
        28: "Complétez la phrase suivante avec l'adverbe qui convient :",
        29: "Trouvez un synonyme pour l'adverbe suivant :",
        30: "Écrivez l'antonyme de l'adverbe suivant :",

        31: "Traduisez l'adverbe suivant :",
        32: "Complétez la phrase suivante avec l'adverbe qui convient :",
        33: "Traduisez l'adverbe suivant :",
        34: "Complétez la phrase suivante avec l'adverbe qui convient :",
        35: "Traduisez l'adverbe suivant :",
        36: "Complétez la phrase suivante avec l'adverbe qui convient :",
        37: "Traduisez l'adverbe suivant :",
        38: "Complétez la phrase suivante avec l'adverbe qui convient :",
        39: "Trouvez un synonyme pour l'adverbe suivant :",
        40: "Écrivez l'antonyme de l'adverbe suivant :",

        41: "Traduisez l'adverbe suivant :",
        42: "Complétez la phrase suivante avec l'adverbe qui convient :",
        43: "Traduisez l'adverbe suivant :",
        44: "Complétez la phrase suivante avec l'adverbe qui convient :",
        45: "Traduisez l'adverbe suivant :",
        46: "Complétez la phrase suivante avec l'adverbe qui convient :",
        47: "Traduisez l'adverbe suivant :",
        48: "Complétez la phrase suivante avec l'adverbe qui convient :",
        49: "Trouvez un synonyme pour l'adverbe suivant :",
        50: "Écrivez l'antonyme de l'adverbe suivant :",

        51: "Traduisez l'adverbe suivant :",
        52: "Complétez la phrase suivante avec l'adverbe qui convient :",
        53: "Traduisez l'adverbe suivant :",
        54: "Complétez la phrase suivante avec l'adverbe qui convient :",
        55: "Traduisez l'adverbe suivant :",
        56: "Complétez la phrase suivante avec l'adverbe qui convient :",
        57: "Traduisez l'adverbe suivant :",
        58: "Complétez la phrase suivante avec l'adverbe qui convient :",
        59: "Trouvez un synonyme pour l'adverbe suivant :",
        60: "Écrivez l'antonyme de l'adverbe suivant :",
    },

    wortstellung: {
        1: "",
    },

    adjektive: {
        1: "Traduisez l'adjectif suivant :",
        2: "Traduisez l'adjectif suivant :",
        3: "Traduisez l'adjectif suivant :",
        4: "Écrivez l'antonyme de l'adjectif suivant :",
        5: "Écrivez l'antonyme de l'adjectif suivant :",
        6: "Écrivez le comparatif de l'adjectif suivant :",
        7: "Écrivez le comparatif de l'adjectif suivant :",
        8: "Écrivez le comparatif de l'adjectif suivant :",
        9: "Écrivez le superlatif de l'adjectif suivant :",
        10: "Écrivez le superlatif de l'adjectif suivant :",
        11: "Écrivez le superlatif de l'adjectif suivant :",
        12: "Complétez la phrase suivante avec la conjonction comparative qui convient :",

        13: "Traduisez l'adjectif suivant :",
        14: "Traduisez l'adjectif suivant :",
        15: "Traduisez l'adjectif suivant :",
        16: "Écrivez l'antonyme de l'adjectif suivant :",
        17: "Écrivez l'antonyme de l'adjectif suivant :",
        18: "Écrivez le comparatif de l'adjectif suivant :",
        19: "Écrivez le comparatif de l'adjectif suivant :",
        20: "Écrivez le comparatif de l'adjectif suivant :",
        21: "Écrivez le superlatif de l'adjectif suivant :",
        22: "Écrivez le superlatif de l'adjectif suivant :",
        23: "Écrivez le superlatif de l'adjectif suivant :",

        24: "Traduisez l'adjectif suivant :",
        25: "Traduisez l'adjectif suivant :",
        26: "Traduisez l'adjectif suivant :",
        27: "Traduisez l'adjectif suivant :",
        28: "Traduisez l'adjectif suivant :",
        29: "Traduisez l'adjectif suivant :",

        30: "Traduisez l'adjectif suivant :",
        31: "Traduisez l'adjectif suivant :",
        32: "Traduisez l'adjectif suivant :",
        33: "Traduisez l'adjectif suivant :",
        34: "Traduisez l'adjectif suivant :",
        35: "Traduisez l'adjectif suivant :",
    },

    adjektivdeklinationen: {
        1: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        2: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        3: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        4: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        5: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        6: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        7: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        8: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        9: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        10: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        11: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        12: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",

        13: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        14: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        15: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        16: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        17: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        18: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",

        19: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        20: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        21: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        22: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",

        23: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        24: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        25: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        26: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        27: "Complétez la phrase avec la forme comparative correcte de l'adjectif spécifié :",
        28: "Complétez la phrase avec la forme comparative correcte de l'adjectif spécifié :",
        29: "Complétez la phrase avec la forme superlative correcte de l'adjectif spécifié :",
        30: "Complétez la phrase avec la forme superlative correcte de l'adjectif spécifié :",
    },

    verben: {
        1: "Traduisez le verbe suivant :",
        2: "Traduisez le verbe suivant :",
        3: "Traduisez le verbe suivant :",
        4: "Traduisez le verbe suivant :",
        5: "Traduisez le verbe suivant :",

        6: "Traduisez le verbe suivant :",
        7: "Traduisez le verbe suivant :",
        8: "Traduisez le verbe suivant :",
        9: "Traduisez le verbe suivant :",
        10: "Traduisez le verbe suivant :",

        11: "Traduisez le verbe suivant :",
        12: "Traduisez le verbe suivant :",
        13: "Traduisez le verbe suivant :",
        14: "Traduisez le verbe suivant :",
        15: "Traduisez le verbe suivant :",
        16: "Traduisez le verbe suivant :",
        17: "Traduisez le verbe suivant :",
        18: "Traduisez le verbe suivant :",
        19: "Traduisez le verbe suivant :",
        20: "Traduisez le verbe suivant :",

        21: "Traduisez le verbe suivant :",
        22: "Traduisez le verbe suivant :",
        23: "Traduisez le verbe suivant :",
        24: "Traduisez le verbe suivant :",
        25: "Traduisez le verbe suivant :",
        26: "Traduisez le verbe suivant :",
        27: "Traduisez le verbe suivant :",
        28: "Traduisez le verbe suivant :",
        29: "Traduisez le verbe suivant :",
        30: "Traduisez le verbe suivant :",

        31: "Traduisez le verbe suivant :",
        32: "Traduisez le verbe suivant :",
        33: "Traduisez le verbe suivant :",
        34: "Traduisez le verbe suivant :",
        35: "Traduisez le verbe suivant :",
        36: "Traduisez le verbe suivant :",
        37: "Traduisez le verbe suivant :",
        38: "Traduisez le verbe suivant :",
        39: "Traduisez le verbe suivant :",
        40: "Traduisez le verbe suivant :",
        41: "Traduisez le verbe suivant :",
        42: "Traduisez le verbe suivant :",
        43: "Traduisez le verbe suivant :",
        44: "Traduisez le verbe suivant :",
        45: "Traduisez le verbe suivant :",
        46: "Traduisez le verbe suivant :",
        47: "Traduisez le verbe suivant :",
        48: "Traduisez le verbe suivant :",
        49: "Traduisez le verbe suivant :",
        50: "Traduisez le verbe suivant :",
    },

    trennbare_verben: {
        1: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        2: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        3: "Traduisez le verbe (un)trennbare suivant :",

        4: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        5: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        6: "Traduisez le verbe (un)trennbare suivant :",

        7: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        8: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        9: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        10: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        11: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        12: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        13: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        14: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        15: "Traduisez le verbe (un)trennbare suivant :",
        16: "Traduisez le verbe (un)trennbare suivant :",
        17: "Traduisez le verbe (un)trennbare suivant :",
        18: "Traduisez le verbe (un)trennbare suivant :",

        19: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        20: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        21: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        22: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        23: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        24: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        25: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        26: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        27: "Traduisez le verbe (un)trennbare suivant :",
        28: "Traduisez le verbe (un)trennbare suivant :",
        29: "Traduisez le verbe (un)trennbare suivant :",
        30: "Traduisez le verbe (un)trennbare suivant :",
    },

    nomen_verben_verbindungen: {
        1: "Trouvez le nom manquant dans la Combinaison Nom-Verbe suivante :",
        2: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        3: "Trouvez le nom manquant dans la phrase suivante :",
        4: "Trouvez le verbe manquant dans la phrase suivante :",

        5: "Trouvez le nom manquant dans la Combinaison Nom-Verbe suivante :",
        6: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        7: "Trouvez le nom manquant dans la phrase suivante :",
        8: "Trouvez le verbe manquant dans la phrase suivante :",
        9: "Trouvez le nom manquant dans la Combinaison Nom-Verbe suivante :",
        10: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        11: "Trouvez le nom manquant dans la phrase suivante :",
        12: "Trouvez le verbe manquant dans la phrase suivante :",

        13: "Trouvez le nom manquant dans la Combinaison Nom-Verbe suivante :",
        14: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        15: "Trouvez le nom manquant dans la phrase suivante :",
        16: "Trouvez le verbe manquant dans la phrase suivante :",
        17: "Trouvez le nom manquant dans la Combinaison Nom-Verbe suivante :",
        18: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        19: "Trouvez le nom manquant dans la phrase suivante :",
        20: "Trouvez le verbe manquant dans la phrase suivante :",
        21: "Trouvez le nom manquant dans la Combinaison Nom-Verbe suivante :",
        22: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        23: "Trouvez le nom manquant dans la phrase suivante :",
        24: "Trouvez le verbe manquant dans la phrase suivante :",
    },

    praesens: {
        1: "Conjuguez le verbe suivant au présent :",
        2: "Conjuguez le verbe suivant au présent :",
        3: "Conjuguez le verbe suivant au présent :",
        4: "Conjuguez le verbe suivant au présent :",
        5: "Conjuguez le verbe suivant au présent :",
        6: "Conjuguez le verbe suivant au présent :",
        7: "Conjuguez le verbe suivant au présent :",
        8: "Conjuguez le verbe suivant au présent :",
        9: "Conjuguez le verbe suivant au présent :",
        10: "Conjuguez le verbe suivant au présent :",
        11: "Conjuguez le verbe suivant au présent :",
        12: "Conjuguez le verbe suivant au présent :",
        13: "Conjuguez le verbe suivant au présent :",
        14: "Conjuguez le verbe suivant au présent :",
        15: "Conjuguez le verbe suivant au présent :",
        16: "Conjuguez le verbe suivant au présent :",
        17: "Conjuguez le verbe suivant au présent :",
        18: "Conjuguez le verbe suivant au présent :",
        19: "Conjuguez le verbe suivant au présent :",
        20: "Conjuguez le verbe suivant au présent :",

        21: "Conjuguez le verbe suivant au présent :",
        22: "Conjuguez le verbe suivant au présent :",
        23: "Conjuguez le verbe suivant au présent :",
        24: "Conjuguez le verbe suivant au présent :",
        25: "Conjuguez le verbe suivant au présent :",
        26: "Conjuguez le verbe suivant au présent :",
        27: "Conjuguez le verbe suivant au présent :",
        28: "Conjuguez le verbe suivant au présent :",
        29: "Conjuguez le verbe suivant au présent :",
        30: "Conjuguez le verbe suivant au présent :",
        31: "Conjuguez le verbe suivant au présent :",
        32: "Conjuguez le verbe suivant au présent :",
        33: "Conjuguez le verbe suivant au présent :",
        34: "Conjuguez le verbe suivant au présent :",
        35: "Conjuguez le verbe suivant au présent :",
        36: "Conjuguez le verbe suivant au présent :",
        37: "Conjuguez le verbe suivant au présent :",
        38: "Conjuguez le verbe suivant au présent :",
        39: "Conjuguez le verbe suivant au présent :",
        40: "Conjuguez le verbe suivant au présent :",
    },

    partizip_II: {
        1: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        2: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        3: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        4: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        5: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",

        6: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        7: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        8: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        9: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        10: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",

        11: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        12: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        13: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        14: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        15: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        16: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        17: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        18: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        19: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        20: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",

        21: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        22: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        23: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        24: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        25: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        26: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        27: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        28: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        29: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        30: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",

        31: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        32: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        33: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        34: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        35: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        36: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        37: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        38: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        39: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        40: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        41: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        42: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        43: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        44: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        45: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        46: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        47: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        48: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        49: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        50: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
    },

    praeteritum: {
        1: "Conjuguez le verbe suivant au Préterit (Präteritum) :",

        2: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        3: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        4: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        5: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        6: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        7: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        8: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        9: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        10: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        11: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",

        12: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        13: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        14: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        15: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        16: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        17: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        18: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        19: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        20: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        21: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",

        22: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        23: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        24: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        25: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        26: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        27: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        28: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        29: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        30: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        31: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",

        32: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        33: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        34: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        35: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        36: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        37: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        38: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        39: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        40: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        41: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        42: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        43: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        44: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        45: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        46: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        47: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        48: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        49: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        50: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        51: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
    },

    praeteritum_partizip_II: {
        1: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",

        2: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        3: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        4: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        5: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        6: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        7: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        8: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        9: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        10: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        11: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",

        12: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        13: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        14: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        15: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        16: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        17: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        18: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        19: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        20: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        21: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
           "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",

        22: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        23: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        24: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        25: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        26: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        27: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        28: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        29: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        30: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        31: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",

        32: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        33: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        34: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        35: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        36: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        37: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        38: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        39: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        40: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        41: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        42: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        43: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        44: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        45: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        46: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        47: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        48: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        49: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        50: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
        51: "Écrivez le Préerit (Präteritum) – 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant."
            "<br><br>Utilisez les formats \"spielte gespielt\" ou \"spielte, gespielt\".",
    },

    imperativ: {
        1: "Conjuguez le verbe suivant à l'impératif :",
        2: "Conjuguez le verbe suivant à l'impératif :",
        3: "Conjuguez le verbe suivant à l'impératif :",
        4: "Conjuguez le verbe suivant à l'impératif :",
        5: "Conjuguez le verbe suivant à l'impératif :",
        6: "Conjuguez le verbe suivant à l'impératif :",

        7: "Conjuguez le verbe suivant à l'impératif :",
        8: "Conjuguez le verbe suivant à l'impératif :",
        9: "Conjuguez le verbe suivant à l'impératif :",
        10: "Conjuguez le verbe suivant à l'impératif :",
        11: "Conjuguez le verbe suivant à l'impératif :",
        12: "Conjuguez le verbe suivant à l'impératif :",
    },

    konjunktiv_II: {
        1: "Conjuguez le verbe suivant au Subjonctif II (Konjunktiv II) :",
    },

    konjunktiv_I: {
        1: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
        2: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
        3: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
        4: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
        5: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
        6: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
    },

    partizip_I: {
        1: "Écrivez le Participe Présent (Partizip I) du verbe suivant :",
        2: "Écrivez le Participe Présent (Partizip I) du verbe suivant :",
        3: "Écrivez le Participe Présent (Partizip I) du verbe suivant :",
        4: "Écrivez le Participe Présent (Partizip I) du verbe suivant :",
        5: "Écrivez le Participe Présent (Partizip I) du verbe suivant :",
    },

}
# arrow &#8594

