from data.data_processing.units import (
    praepositionen_grammatik, praepositionen_verben, praepositionen_adjektive, praepositionen_nomen,
    praepositionen_artikel, praepositionen_adverbien,
    artikel, pronomen, konnektoren, fragen, adverbien, wortstellung,
    adjektive, adjektivdeklinationen, adjektive_konjunktionen,
    verben, trennbare_verben, nomen_verben_verbindungen, nomen_verben_wortstaemme,
    praesens, imperativ, partizip_II, praeteritum, praeteritum_partizip_II, konjunktiv_II, konjunktiv_I, partizip_I,
    genus_regeln, genus_routledge, genus_goethe,
    zahlen,
)

# bullet point \u25CF

INSTRUCTION_FR = {

    praepositionen_grammatik: {
        1: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        2: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        3: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        4: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        5: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        6: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        7: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        8: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        9: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        10: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        11: "Traduisez la préposition ci-dessous :",
        12: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        13: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        14: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        15: "Traduisez la préposition ci-dessous :",
        16: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        17: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        18: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        19: "Traduisez la préposition ci-dessous :",
        20: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        21: "Traduisez la préposition ci-dessous :",
        22: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        23: "Traduisez le groupe prépositionel ci-dessous :",
        24: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        25: "Traduisez la postposition ci-dessous :",
        26: "Complétez la phrase ci-dessous avec la postposition qui convient :",
        27: "Trouvez un synonyme pour la préposition suivant :",
        28: "Trouvez un antonyme pour la préposition suivant :",

        29: "Complétez la phrase ci-dessous avec la préposition qui convient :",
    },

    praepositionen_verben: {
        1: "Écrivez la préposition qui correspond au verbe suivant :",
        2: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        3: "Écrivez la préposition qui correspond au verbe suivant :",
        4: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        5: "Écrivez la préposition qui correspond au verbe suivant :",
        6: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        7: "Écrivez la préposition qui correspond au verbe suivant :",
        8: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        9: "Complétez la phrase suivante avec l'Adverbe Pronominal en Da- qui convient :",
        10: "Complétez la phrase suivante avec l'Adverbe Pronominal en Da- qui convient :",

        11: "Écrivez la préposition qui correspond au verbe suivant :",
        12: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        13: "Écrivez la préposition qui correspond au verbe suivant :",
        14: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        15: "Écrivez la préposition qui correspond au verbe suivant :",
        16: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        17: "Écrivez la préposition qui correspond au verbe suivant :",
        18: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        19: "Écrivez la préposition qui correspond au verbe suivant :",
        20: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        21: "Écrivez la préposition qui correspond au verbe suivant :",
        22: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        23: "Écrivez la préposition qui correspond au verbe suivant :",
        24: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        25: "Écrivez la préposition qui correspond au verbe suivant :",
        26: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        27: "Écrivez la préposition qui correspond au verbe suivant :",
        28: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        29: "Écrivez la préposition qui correspond au verbe suivant :",
        30: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        31: "Écrivez la préposition qui correspond au verbe suivant :",
        32: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        33: "Écrivez la préposition qui correspond au verbe suivant :",
        34: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        35: "Écrivez la préposition qui correspond au verbe suivant :",
        36: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        37: "Écrivez la préposition qui correspond au verbe suivant :",
        38: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        39: "Écrivez la préposition qui correspond au verbe suivant :",
        40: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        41: "Écrivez la préposition qui correspond au verbe suivant :",
        42: "Complétez la phrase ci-dessous avec la préposition qui convient :",
    },

    praepositionen_adjektive: {
        1: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        2: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        3: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        4: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        5: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        6: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        7: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        8: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        9: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        10: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        11: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        12: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        13: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        14: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        15: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        16: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        17: "Écrivez la préposition qui correspond à l'adjectif suivant :",
        18: "Complétez la phrase ci-dessous avec la préposition qui convient :",
    },

    praepositionen_nomen: {
        1: "Écrivez la préposition qui correspond au nom suivant :",
        2: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        3: "Écrivez la préposition qui correspond au nom suivant :",
        4: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        5: "Écrivez la préposition qui correspond au nom suivant :",
        6: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        7: "Écrivez la préposition qui correspond au nom suivant :",
        8: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        9: "Écrivez la préposition qui correspond au nom suivant :",
        10: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        11: "Écrivez la préposition qui correspond au nom suivant :",
        12: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        13: "Écrivez la préposition qui correspond au nom suivant :",
        14: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        15: "Écrivez la préposition qui correspond au nom suivant :",
        16: "Complétez la phrase ci-dessous avec la préposition qui convient :",

        17: "Écrivez la préposition qui correspond au nom suivant :",
        18: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        19: "Écrivez la préposition qui correspond au nom suivant :",
        20: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        21: "Écrivez la préposition qui correspond au nom suivant :",
        22: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        23: "Écrivez la préposition qui correspond au nom suivant :",
        24: "Complétez la phrase ci-dessous avec la préposition qui convient :",
        25: "Écrivez la préposition qui correspond au nom suivant :",
        26: "Complétez la phrase ci-dessous avec la préposition qui convient :",
    },

    praepositionen_artikel: {
        1: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        2: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        3: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        4: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        5: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        6: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",

        7: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        8: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        9: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        10: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",

        11: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        12: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        13: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        14: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        15: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        16: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        17: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        18: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        19: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        20: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        21: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
        22: "Complétez la phrase suivante avec la préposition indiquée et l'article ou le pronom qui convient :",
    },

    praepositionen_adverbien: {
        1: "Something",
        2: "Something",
        3: "Something",
        4: "Something",
    },

    artikel: {
        1: "Écrivez l'article défini qui correspond au cas et au genre fournis :",
        2: "Complétez la phrase suivante avec l'article défini nominatif qui convient :",
        3: "Complétez la phrase suivante avec l'article défini accusatif qui convient :",
        4: "Complétez la phrase suivante avec l'article défini datif qui convient :",
        5: "Complétez la phrase suivante avec l'article défini féminin qui convient :",
        6: "Complétez la phrase suivante avec l'article défini masculin qui convient :",
        7: "Complétez la phrase suivante avec l'article défini neutre qui convient :",
        8: "Complétez la phrase suivante avec l'article défini pluriel qui convient :",
        9: "Complétez la phrase suivante avec l'article défini qui convient :",
        10: "Complétez la phrase suivante avec l'article défini qui convient :",
        11: "Écrivez l'article indéfini qui correspond au cas et au genre fournis :",
        12: "Complétez la phrase suivante avec l'article indéfini nominatif qui convient :",
        13: "Complétez la phrase suivante avec l'article indéfini accusatif qui convient :",
        14: "Complétez la phrase suivante avec l'article indéfini datif qui convient :",
        15: "Complétez la phrase suivante avec l'article indéfini féminin qui convient :",
        16: "Complétez la phrase suivante avec l'article indéfini masculin qui convient :",
        17: "Complétez la phrase suivante avec l'article indéfini neutre qui convient :",
        18: "Complétez la phrase suivante avec l'article indéfini qui convient :",
        19: "Complétez la phrase suivante avec l'article indéfini qui convient :",
        20: "Écrivez le mot-clé qui correspond au cas et au genre fournis :",
        21: "Complétez la phrase suivante avec le mot Kein qui convient :",
        22: "Écrivez l'article possessif qui correspond au cas et au genre fournis :",
        23: "Complétez la phrase suivante avec l'article possessif qui convient."
            "<br><br>Tous les articles possessifs sont basés sur des pronoms singuliers (<i>Ich</i>, <i>Du</i>, <i>Er</i>, <i>Sie</i>, <i>Es</i>).",
        24: "Écrivez l'article possessif qui correspond au cas et au genre fournis.",
        25: "Complétez la phrase suivante avec l'article possessif qui convient."
            "<br><br>Tous les articles possessifs sont basés sur des pronoms pluriels (<i>Wir</i>, <i>Ihr</i>, <i>Sie</i>) ou formels.",

        26: "Rédigez l'article démonstratif qui correspond au cas et au genre fournis :",
        27: "Complétez la phrase suivante avec l'article démonstratif qui convient :",
        28: "Écrivez le mot \"jede\" qui correspond au cas et au genre fournis :",
        29: "Complétez la phrase suivante avec le mot \"jede\" qui convient :",
        30: "Traduisez l'article suivant :",
        31: "Complétez la phrase suivante avec l'article qui convient :",

        32: "Rédigez l'article qui correspond au cas et au genre fournis :",
        33: "Complétez la phrase suivante avec l'article génitif qui convient :",
        34: "Rédigez l'article qui correspond au cas et au genre fournis :",
        35: "Complétez la phrase suivante avec l'article génitif qui convient :",
        36: "Écrivez l'article possessif qui correspond au cas et au genre fournis :",
        37: "Complétez la phrase suivante avec l'article possessif qui convient :",

        38: "Traduisez l'article suivant en fonction du cas et du genre fournis :",
        39: "Complétez la phrase suivante avec l'article qui convient :",

        40: "Traduisez l'article suivant en fonction du cas et du genre fournis :",
        41: "Complétez la phrase suivante avec l'article qui convient :",
        42: "Complétez la phrase suivante avec l'article qui convient :",
        43: "Complétez la phrase suivante avec l'article qui convient :",
    },

    pronomen: {
        1: "Écrivez le pronom nominatif qui correspond à la personne donnée :",
        2: "Complétez la phrase suivante avec le pronom nominatif qui convient :",
        3: "Écrivez le pronom accusatif qui correspond à la personne donnée :",
        4: "Complétez la phrase suivante avec le pronom accusatif qui convient :",
        5: "Écrivez le pronom datif qui correspond à la personne donnée :",
        6: "Complétez la phrase suivante avec le pronom datif qui convient :",
        7: "Complétez la phrase suivante avec le pronom qui convient :",
        8: "Complétez la phrase suivante avec le pronom qui convient :",
        9: "Remplacez l'objet indiqué par le pronom approprié :",
        10: "Remplacez l'objet indiqué par le pronom approprié :",

        11: "Écrivez le pronom réfléchi qui correspond à la personne et au cas donnés :",
        12: "Complétez la phrase suivante avec le pronom réfléchi qui convient :",
        13: "Complétez la phrase suivante avec le pronom qui convient :",
        14: "Complétez la phrase suivante avec le pronom qui convient :",

        15: "Traduisez le pronom suivant :",
        16: "Complétez la phrase suivante avec le pronom qui convient :",
        17: "Complétez la phrase suivante avec le pronom relatif nominatif qui convient :",
        18: "Complétez la phrase suivante avec le pronom relatif accusatif qui convient :",
        19: "Complétez la phrase suivante avec le pronom relatif datif qui convient :",
        20: "Complétez la phrase suivante avec le pronom relatif génitif qui convient :",
        21: "Complétez la phrase suivante avec le pronom relatif qui convient :",
        22: "Complétez la phrase suivante avec le pronom relatif qui convient :",

        23: "Complétez la phrase suivante avec le pronom relatif qui convient :",
        24: "Complétez la phrase suivante avec le pronom relatif qui convient :",
        25: "Complétez la phrase suivante avec le pronom relatif qui convient – il peut y avoir plusieurs options :",
        26: "Fournissez la traduction du pronom possessif qui correspond au cas et au genre fournis :",
        27: "Complétez la phrase suivante avec le pronom possessif qui convient :",
        28: "Fournissez la traduction du pronom possessif qui correspond au cas et au genre fournis :",
        29: "Complétez la phrase suivante avec le pronom possessif qui convient :",

        30: "Complétez la phrase suivante avec le pronom relatif qui convient :",
    },

    konnektoren: {
        1: "Traduisez le connecteur suivant :",
        2: "Complétez la phrase suivante avec le connecteur qui convient :",

        3: "Traduisez le connecteur suivant :",
        4: "Complétez la phrase suivante avec le connecteur qui convient :",

        5: "Traduisez le connecteur suivant :",
        6: "Complétez la phrase suivante avec le connecteur qui convient :",
        7: "Traduisez le connecteur suivant :",
        8: "Complétez la phrase suivante avec le connecteur qui convient :",
        9: "Traduisez le connecteur suivant :",
        10: "Complétez la phrase suivante avec le connecteur qui convient :",
        11: "Trouvez un synonyme pour le connecteur suivant :",

        12: "Traduisez le connecteur suivant :",
        13: "Complétez la phrase suivante avec le connecteur qui convient :",
        14: "Traduisez le connecteur suivant :",
        15: "Complétez la phrase suivante avec le connecteur qui convient :",
        16: "Traduisez le connecteur suivant :",
        17: "Complétez la phrase suivante avec le connecteur qui convient :",
        18: "Trouvez un synonyme pour le connecteur suivant :",

        19: "Traduisez le connecteur suivant :",
        20: "Complétez la phrase suivante avec le connecteur qui convient :",
        21: "Traduisez le connecteur suivant :",
        22: "Complétez la phrase suivante avec le connecteur qui convient :",
        23: "Traduisez le connecteur suivant :",
        24: "Complétez la phrase suivante avec le connecteur qui convient :",
        25: "Traduisez le connecteur suivant :",
        26: "Complétez la phrase suivante avec le connecteur qui convient :",
        27: "Traduisez le connecteur suivant :",
        28: "Complétez la phrase suivante avec le connecteur qui convient :",
        29: "Trouvez un synonyme pour le connecteur suivant :",
        30: "Trouvez un synonyme pour le connecteur suivant :",
        31: "Trouvez un synonyme pour le connecteur suivant :",
        32: "Trouvez un synonyme pour le connecteur suivant :",
    },

    fragen: {
        1: "Traduisez le mot interrogatif suivant :",
        2: "Complétez la phrase suivante avec le mot interrogatif qui convient :",

        3: "Traduisez le mot interrogatif suivant :",
        4: "Complétez la phrase suivante avec le mot interrogatif qui convient :",

        5: "Traduisez le mot interrogatif suivant :",
        6: "Complétez la phrase suivante avec le mot interrogatif qui convient :",

        7: "Traduisez le mot interrogatif suivant :",
        8: "Complétez la phrase suivante avec le mot interrogatif qui convient :",
        9: "Traduisez le mot interrogatif suivant :",
        10: "Complétez la phrase suivante avec le mot interrogatif qui convient :",

        11: "Traduisez le mot interrogatif suivant :",
        12: "Complétez la phrase suivante avec le mot interrogatif qui convient :",

        13: "Traduisez le mot interrogatif suivant :",
        14: "Complétez la phrase suivante avec le mot interrogatif qui convient :",
    },

    adverbien: {
        1: "Traduisez l'adverbe suivant :",
        2: "Complétez la phrase suivante avec l'adverbe qui convient :",
        3: "Traduisez l'adverbe suivant :",
        4: "Complétez la phrase suivante avec l'adverbe qui convient :",

        5: "Traduisez l'adverbe suivant :",
        6: "Complétez la phrase suivante avec l'adverbe qui convient :",
        7: "Traduisez l'adverbe suivant :",
        8: "Complétez la phrase suivante avec l'adverbe qui convient :",
        9: "Trouvez un synonyme pour l'adverbe suivant :",
        10: "Écrivez l'antonyme de l'adverbe suivant :",

        11: "Traduisez l'adverbe suivant :",
        12: "Complétez la phrase suivante avec l'adverbe qui convient :",
        13: "Traduisez l'adverbe suivant :",
        14: "Complétez la phrase suivante avec l'adverbe qui convient :",
        15: "Traduisez l'adverbe suivant :",
        16: "Complétez la phrase suivante avec l'adverbe qui convient :",
        17: "Traduisez l'adverbe suivant :",
        18: "Complétez la phrase suivante avec l'adverbe qui convient :",
        19: "Trouvez un synonyme pour l'adverbe suivant :",
        20: "Écrivez l'antonyme de l'adverbe suivant :",

        21: "Traduisez l'adverbe suivant :",
        22: "Complétez la phrase suivante avec l'adverbe qui convient :",
        23: "Traduisez l'adverbe suivant :",
        24: "Complétez la phrase suivante avec l'adverbe qui convient :",
        25: "Traduisez l'adverbe suivant :",
        26: "Complétez la phrase suivante avec l'adverbe qui convient :",
        27: "Traduisez l'adverbe suivant :",
        28: "Complétez la phrase suivante avec l'adverbe qui convient :",
        29: "Trouvez un synonyme pour l'adverbe suivant :",
        30: "Écrivez l'antonyme de l'adverbe suivant :",

        31: "Traduisez l'adverbe suivant :",
        32: "Complétez la phrase suivante avec l'adverbe qui convient :",
        33: "Traduisez l'adverbe suivant :",
        34: "Complétez la phrase suivante avec l'adverbe qui convient :",
        35: "Traduisez l'adverbe suivant :",
        36: "Complétez la phrase suivante avec l'adverbe qui convient :",
        37: "Traduisez l'adverbe suivant :",
        38: "Complétez la phrase suivante avec l'adverbe qui convient :",
        39: "Trouvez un synonyme pour l'adverbe suivant :",
        40: "Écrivez l'antonyme de l'adverbe suivant :",

        41: "Traduisez l'adverbe suivant :",
        42: "Complétez la phrase suivante avec l'adverbe qui convient :",
        43: "Traduisez l'adverbe suivant :",
        44: "Complétez la phrase suivante avec l'adverbe qui convient :",
        45: "Traduisez l'adverbe suivant :",
        46: "Complétez la phrase suivante avec l'adverbe qui convient :",
        47: "Traduisez l'adverbe suivant :",
        48: "Complétez la phrase suivante avec l'adverbe qui convient :",
        49: "Trouvez un synonyme pour l'adverbe suivant :",
        50: "Écrivez l'antonyme de l'adverbe suivant :",

        51: "Traduisez l'adverbe suivant :",
        52: "Complétez la phrase suivante avec l'adverbe qui convient :",
        53: "Traduisez l'adverbe suivant :",
        54: "Complétez la phrase suivante avec l'adverbe qui convient :",
        55: "Traduisez l'adverbe suivant :",
        56: "Complétez la phrase suivante avec l'adverbe qui convient :",
        57: "Traduisez l'adverbe suivant :",
        58: "Complétez la phrase suivante avec l'adverbe qui convient :",
        59: "Trouvez un synonyme pour l'adverbe suivant :",
        60: "Écrivez l'antonyme de l'adverbe suivant :",

        61: "Traduisez l'adverbe suivant :",
        62: "Complétez la phrase suivante avec l'adverbe qui convient :",
        63: "Traduisez l'adverbe suivant :",
        64: "Complétez la phrase suivante avec l'adverbe qui convient :",
        65: "Traduisez l'adverbe suivant :",
        66: "Complétez la phrase suivante avec l'adverbe qui convient :",
        67: "Traduisez l'adverbe suivant :",
        68: "Complétez la phrase suivante avec l'adverbe qui convient :",
        69: "Trouvez un synonyme pour l'adverbe suivant :",
        70: "Écrivez l'antonyme de l'adverbe suivant :",

        71: "Traduisez l'adverbe suivant :",
        72: "Complétez la phrase suivante avec l'adverbe qui convient :",
        73: "Traduisez l'adverbe suivant :",
        74: "Complétez la phrase suivante avec l'adverbe qui convient :",
        75: "Traduisez l'adverbe suivant :",
        76: "Complétez la phrase suivante avec l'adverbe qui convient :",
        77: "Traduisez l'adverbe suivant :",
        78: "Complétez la phrase suivante avec l'adverbe qui convient :",
        79: "Trouvez un synonyme pour l'adverbe suivant :",
        80: "Écrivez l'antonyme de l'adverbe suivant :",
    },

    wortstellung: {
        1: "Placeholder",
    },

    adjektive: {
        1: "Traduisez l'adjectif suivant :",
        2: "Traduisez l'adjectif suivant :",
        3: "Traduisez l'adjectif suivant :",
        4: "Écrivez l'antonyme de l'adjectif suivant :",
        5: "Écrivez l'antonyme de l'adjectif suivant :",
        6: "Écrivez le comparatif de l'adjectif suivant :",
        7: "Écrivez le comparatif de l'adjectif suivant :",
        8: "Écrivez le comparatif de l'adjectif suivant :",
        9: "Écrivez le superlatif de l'adjectif suivant :",
        10: "Écrivez le superlatif de l'adjectif suivant :",
        11: "Écrivez le superlatif de l'adjectif suivant :",

        12: "Traduisez l'adjectif suivant :",
        13: "Traduisez l'adjectif suivant :",
        14: "Traduisez l'adjectif suivant :",
        15: "Écrivez l'antonyme de l'adjectif suivant :",
        16: "Écrivez l'antonyme de l'adjectif suivant :",
        17: "Écrivez le comparatif de l'adjectif suivant :",
        18: "Écrivez le comparatif de l'adjectif suivant :",
        19: "Écrivez le comparatif de l'adjectif suivant :",
        20: "Écrivez le superlatif de l'adjectif suivant :",
        21: "Écrivez le superlatif de l'adjectif suivant :",
        22: "Écrivez le superlatif de l'adjectif suivant :",

        23: "Traduisez l'adjectif suivant :",
        24: "Traduisez l'adjectif suivant :",
        25: "Traduisez l'adjectif suivant :",
        26: "Traduisez l'adjectif suivant :",
        27: "Traduisez l'adjectif suivant :",
        28: "Traduisez l'adjectif suivant :",

        29: "Traduisez l'adjectif suivant :",
        30: "Traduisez l'adjectif suivant :",
        31: "Traduisez l'adjectif suivant :",
        32: "Traduisez l'adjectif suivant :",
        33: "Traduisez l'adjectif suivant :",
        34: "Traduisez l'adjectif suivant :",
    },

    adjektivdeklinationen: {
        1: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        2: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        3: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        4: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        5: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        6: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        7: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        8: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        9: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        10: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        11: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        12: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        13: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        14: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",

        15: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        16: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        17: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        18: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        19: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        20: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        21: "Complétez la phrase avec la forme comparative correcte de l'adjectif spécifié :",
        22: "Complétez la phrase avec la forme comparative correcte de l'adjectif spécifié :",
        23: "Complétez la phrase avec la forme superlative correcte de l'adjectif spécifié :",
        24: "Complétez la phrase avec la forme superlative correcte de l'adjectif spécifié :",

        25: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        26: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",

        27: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        28: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        29: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
        30: "Complétez la phrase avec la forme correcte de l'adjectif spécifié :",
    },

    adjektive_konjunktionen: {
        1: "Complétez la phrase suivante avec la conjonction ou la préposition qui convient :",

        2: "Complétez la phrase suivante avec la conjonction qui convient :",

        3: "Complétez la phrase suivante avec la conjonction qui convient :",

        4: "Complétez la phrase suivante avec la conjonction ou la préposition qui convient :",
    },

    verben: {
        1: "Traduisez le verbe suivant :",
        2: "Traduisez le verbe suivant :",
        3: "Traduisez le verbe suivant :",
        4: "Traduisez le verbe suivant :",
        5: "Traduisez le verbe suivant :",

        6: "Traduisez le verbe suivant :",
        7: "Traduisez le verbe suivant :",
        8: "Traduisez le verbe suivant :",
        9: "Traduisez le verbe suivant :",
        10: "Traduisez le verbe suivant :",

        11: "Traduisez le verbe suivant :",
        12: "Traduisez le verbe suivant :",
        13: "Traduisez le verbe suivant :",
        14: "Traduisez le verbe suivant :",
        15: "Traduisez le verbe suivant :",
        16: "Traduisez le verbe suivant :",
        17: "Traduisez le verbe suivant :",
        18: "Traduisez le verbe suivant :",
        19: "Traduisez le verbe suivant :",
        20: "Traduisez le verbe suivant :",

        21: "Traduisez le verbe suivant :",
        22: "Traduisez le verbe suivant :",
        23: "Traduisez le verbe suivant :",
        24: "Traduisez le verbe suivant :",
        25: "Traduisez le verbe suivant :",
        26: "Traduisez le verbe suivant :",
        27: "Traduisez le verbe suivant :",
        28: "Traduisez le verbe suivant :",
        29: "Traduisez le verbe suivant :",
        30: "Traduisez le verbe suivant :",

        31: "Traduisez le verbe suivant :",
        32: "Traduisez le verbe suivant :",
        33: "Traduisez le verbe suivant :",
        34: "Traduisez le verbe suivant :",
        35: "Traduisez le verbe suivant :",
        36: "Traduisez le verbe suivant :",
        37: "Traduisez le verbe suivant :",
        38: "Traduisez le verbe suivant :",
        39: "Traduisez le verbe suivant :",
        40: "Traduisez le verbe suivant :",
        41: "Traduisez le verbe suivant :",
        42: "Traduisez le verbe suivant :",
        43: "Traduisez le verbe suivant :",
        44: "Traduisez le verbe suivant :",
        45: "Traduisez le verbe suivant :",
        46: "Traduisez le verbe suivant :",
        47: "Traduisez le verbe suivant :",
        48: "Traduisez le verbe suivant :",
        49: "Traduisez le verbe suivant :",
        50: "Traduisez le verbe suivant :",
    },

    trennbare_verben: {
        1: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        2: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        3: "Traduisez le verbe (un)trennbare suivant :",

        4: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        5: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        6: "Traduisez le verbe (un)trennbare suivant :",

        7: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        8: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        9: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        10: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        11: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        12: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        13: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        14: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        15: "Traduisez le verbe (un)trennbare suivant :",
        16: "Traduisez le verbe (un)trennbare suivant :",
        17: "Traduisez le verbe (un)trennbare suivant :",
        18: "Traduisez le verbe (un)trennbare suivant :",

        19: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        20: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        21: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        22: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        23: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        24: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        25: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        26: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        27: "Traduisez le verbe (un)trennbare suivant :",
        28: "Traduisez le verbe (un)trennbare suivant :",
        29: "Traduisez le verbe (un)trennbare suivant :",
        30: "Traduisez le verbe (un)trennbare suivant :",

        31: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        32: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        33: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        34: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        35: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        36: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        37: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        38: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        39: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        40: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        41: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        42: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        43: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        44: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        45: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        46: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        47: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        48: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        49: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        50: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        51: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        52: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        53: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        54: "Traduisez le verbe (un)trennbare suivant en vous basant sur la racine spécifiée :",
        55: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        56: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        57: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        58: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        59: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        60: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        61: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        62: "Traduisez le verbe (un)trennbare suivant en vous basant sur le préfixe spécifié :",
        63: "Traduisez le verbe (un)trennbare suivant :",
        64: "Traduisez le verbe (un)trennbare suivant :",
        65: "Traduisez le verbe (un)trennbare suivant :",
        66: "Traduisez le verbe (un)trennbare suivant :",
        67: "Traduisez le verbe (un)trennbare suivant :",
        68: "Traduisez le verbe (un)trennbare suivant :",
        69: "Traduisez le verbe (un)trennbare suivant :",
        70: "Traduisez le verbe (un)trennbare suivant :",
    },

    nomen_verben_verbindungen: {
        1: "Trouvez le nom commun manquant dans la Combinaison Nom-Verbe suivante :",
        2: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        3: "Trouvez le nom commun manquant dans la phrase suivante :",
        4: "Trouvez le verbe manquant dans la phrase suivante :",

        5: "Trouvez le nom commun manquant dans la Combinaison Nom-Verbe suivante :",
        6: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        7: "Trouvez le nom commun manquant dans la phrase suivante :",
        8: "Trouvez le verbe manquant dans la phrase suivante :",
        9: "Trouvez le nom commun manquant dans la Combinaison Nom-Verbe suivante :",
        10: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        11: "Trouvez le nom commun manquant dans la phrase suivante :",
        12: "Trouvez le verbe manquant dans la phrase suivante :",
        13: "Trouvez le nom commun manquant dans la Combinaison Nom-Verbe suivante :",
        14: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        15: "Trouvez le nom commun manquant dans la phrase suivante :",
        16: "Trouvez le verbe manquant dans la phrase suivante :",

        17: "Trouvez le nom commun manquant dans la Combinaison Nom-Verbe suivante :",
        18: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        19: "Trouvez le nom commun manquant dans la phrase suivante :",
        20: "Trouvez le verbe manquant dans la phrase suivante :",
        21: "Trouvez le nom commun manquant dans la Combinaison Nom-Verbe suivante :",
        22: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        23: "Trouvez le nom commun manquant dans la phrase suivante :",
        24: "Trouvez le verbe manquant dans la phrase suivante :",
        25: "Trouvez le nom commun manquant dans la Combinaison Nom-Verbe suivante :",
        26: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        27: "Trouvez le nom commun manquant dans la phrase suivante :",
        28: "Trouvez le verbe manquant dans la phrase suivante :",
        29: "Trouvez le nom commun manquant dans la Combinaison Nom-Verbe suivante :",
        30: "Trouvez le verbe manquant dans la Combinaison Nom-Verbe suivante :",
        31: "Trouvez le nom commun manquant dans la phrase suivante :",
        32: "Trouvez le verbe manquant dans la phrase suivante :",
    },

    nomen_verben_wortstaemme: {
        1: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        2: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",

        3: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        4: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        5: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        6: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        7: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        8: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",

        9: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        10: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        11: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        12: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        13: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        14: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        15: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        16: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        17: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        18: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        19: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        20: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        21: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        22: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        23: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        24: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        25: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        26: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        27: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        28: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",

        29: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        30: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        31: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        32: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        33: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        34: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        35: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        36: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        37: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        38: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        39: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        40: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        41: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        42: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        43: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        44: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        45: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        46: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        47: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        48: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        49: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        50: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        51: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        52: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        53: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        54: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        55: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        56: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        57: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        58: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",

        59: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        60: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        61: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        62: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        63: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        64: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        65: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        66: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        67: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        68: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        69: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        70: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        71: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        72: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        73: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        74: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        75: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        76: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        77: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        78: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        79: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        80: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        81: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        82: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        83: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        84: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        85: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        86: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        87: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        88: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        89: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        90: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
        91: "Trouvez le verbe manquant dans la paire Nom-Verbe suivante :",
        92: "Trouvez le nom commun manquant dans la paire Nom-Verbe suivante :",
    },

    praesens: {
        1: "Conjuguez le verbe suivant au présent :",
        2: "Conjuguez le verbe suivant au présent :",
        3: "Conjuguez le verbe suivant au présent :",
        4: "Conjuguez le verbe suivant au présent :",
        5: "Conjuguez le verbe suivant au présent :",
        6: "Conjuguez le verbe suivant au présent :",
        7: "Conjuguez le verbe suivant au présent :",
        8: "Conjuguez le verbe suivant au présent :",
        9: "Conjuguez le verbe suivant au présent :",
        10: "Conjuguez le verbe suivant au présent :",
        11: "Conjuguez le verbe suivant au présent :",
        12: "Conjuguez le verbe suivant au présent :",
        13: "Conjuguez le verbe suivant au présent :",
        14: "Conjuguez le verbe suivant au présent :",
        15: "Conjuguez le verbe suivant au présent :",
        16: "Conjuguez le verbe suivant au présent :",
        17: "Conjuguez le verbe suivant au présent :",
        18: "Conjuguez le verbe suivant au présent :",
        19: "Conjuguez le verbe suivant au présent :",
        20: "Conjuguez le verbe suivant au présent :",

        21: "Conjuguez le verbe suivant au présent :",
        22: "Conjuguez le verbe suivant au présent :",
        23: "Conjuguez le verbe suivant au présent :",
        24: "Conjuguez le verbe suivant au présent :",
        25: "Conjuguez le verbe suivant au présent :",
        26: "Conjuguez le verbe suivant au présent :",
        27: "Conjuguez le verbe suivant au présent :",
        28: "Conjuguez le verbe suivant au présent :",
        29: "Conjuguez le verbe suivant au présent :",
        30: "Conjuguez le verbe suivant au présent :",
        31: "Conjuguez le verbe suivant au présent :",
        32: "Conjuguez le verbe suivant au présent :",
        33: "Conjuguez le verbe suivant au présent :",
        34: "Conjuguez le verbe suivant au présent :",
        35: "Conjuguez le verbe suivant au présent :",
        36: "Conjuguez le verbe suivant au présent :",
        37: "Conjuguez le verbe suivant au présent :",
        38: "Conjuguez le verbe suivant au présent :",
        39: "Conjuguez le verbe suivant au présent :",
        40: "Conjuguez le verbe suivant au présent :",
    },

    partizip_II: {
        1: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        2: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        3: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        4: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        5: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        6: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        7: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",

        8: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        9: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        10: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        11: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        12: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        13: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        14: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",

        15: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        16: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        17: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        18: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        19: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        20: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        21: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        22: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        23: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        24: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        25: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        26: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        27: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",

        28: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        29: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        30: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        31: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        32: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        33: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        34: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        35: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        36: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        37: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        38: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        39: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        40: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",

        41: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        42: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        43: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        44: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        45: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        46: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        47: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        48: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        49: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        50: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        51: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        52: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        53: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        54: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        55: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        56: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        57: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        58: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        59: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        60: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        61: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        62: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        63: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        64: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        65: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
        66: "Écrivez le Participe Passé (Partizip II) du verbe suivant :",
    },

    praeteritum: {
        1: "Conjuguez le verbe suivant au Préterit (Präteritum) :",

        2: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        3: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        4: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        5: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        6: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        7: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        8: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        9: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        10: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        11: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        12: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        13: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        14: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        15: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",

        16: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        17: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        18: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        19: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        20: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        21: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        22: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        23: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        24: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        25: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        26: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        27: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        28: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",

        29: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        30: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        31: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        32: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        33: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        34: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        35: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        36: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        37: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        38: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        39: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        40: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        41: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",

        42: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        43: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        44: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        45: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        46: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        47: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        48: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        49: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        50: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        51: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        52: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        53: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        54: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        55: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        56: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        57: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        58: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        59: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        60: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        61: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        62: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        63: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        64: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        65: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        66: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
        67: "Conjuguez le verbe suivant au Préterit (Präteritum) à la 3<sup>ème</sup> personne du singulier :",
    },

    praeteritum_partizip_II: {
        1: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        2: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        3: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        4: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        5: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        6: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        7: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        8: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        9: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        10: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        11: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        12: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        13: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        14: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",

        15: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        16: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        17: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        18: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        19: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        20: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        21: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        22: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        23: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        24: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        25: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        26: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        27: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",

        28: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        29: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        30: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        31: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        32: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        33: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        34: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        35: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        36: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        37: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        38: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        39: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        40: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",

        41: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        42: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        43: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        44: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        45: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        46: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        47: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        48: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        49: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        50: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        51: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        52: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        53: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        54: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        55: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        56: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        57: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        58: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        59: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        60: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        61: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        62: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        63: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        64: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        65: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
        66: "Écrivez le Préterit (Präteritum, 3<sup>ème</sup> personne du singulier) et le Participe Passé (Partizip II) du verbe suivant :",
    },

    imperativ: {
        1: "Conjuguez le verbe suivant à l'impératif :",
        2: "Conjuguez le verbe suivant à l'impératif :",
        3: "Conjuguez le verbe suivant à l'impératif :",
        4: "Conjuguez le verbe suivant à l'impératif :",
        5: "Conjuguez le verbe suivant à l'impératif :",
        6: "Conjuguez le verbe suivant à l'impératif :",

        7: "Conjuguez le verbe suivant à l'impératif :",
        8: "Conjuguez le verbe suivant à l'impératif :",
        9: "Conjuguez le verbe suivant à l'impératif :",
        10: "Conjuguez le verbe suivant à l'impératif :",
        11: "Conjuguez le verbe suivant à l'impératif :",
        12: "Conjuguez le verbe suivant à l'impératif :",
    },

    konjunktiv_II: {
        1: "Conjuguez le verbe suivant au Subjonctif II (Konjunktiv II) :",
    },

    konjunktiv_I: {
        1: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
        2: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
        3: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
        4: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
        5: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
        6: "Conjuguez le verbe suivant au Subjonctif I (Konjunktiv I) :",
    },

    partizip_I: {
        1: "Écrivez le Participe Présent (Partizip I) du verbe suivant :",
        2: "Écrivez le Participe Présent (Partizip I) du verbe suivant :",
        3: "Écrivez le Participe Présent (Partizip I) du verbe suivant :",
        4: "Écrivez le Participe Présent (Partizip I) du verbe suivant :",
        5: "Écrivez le Participe Présent (Partizip I) du verbe suivant :",
    },

    genus_regeln: {
        1: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        2: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        3: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        4: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        5: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",

        6: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        7: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        8: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        9: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        10: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",

        11: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        12: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        13: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        14: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        15: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",

        16: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        17: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        18: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        19: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        20: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",

        21: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        22: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        23: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        24: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        25: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        26: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        27: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
    },

    genus_routledge: {
        1: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        2: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        3: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        4: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        5: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        6: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        7: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        8: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        9: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        10: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        11: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        12: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        13: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        14: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        15: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        16: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        17: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        18: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        19: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        20: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        21: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        22: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        23: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        24: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        25: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",

        26: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        27: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        28: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        29: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        30: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        31: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        32: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        33: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        34: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        35: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        36: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        37: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        38: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        39: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        40: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        41: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        42: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        43: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        44: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        45: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        46: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        47: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        48: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        49: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        50: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",

        51: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        52: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        53: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        54: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        55: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        56: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        57: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        58: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        59: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        60: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        61: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        62: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        63: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        64: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        65: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        66: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        67: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        68: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        69: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        70: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        71: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        72: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        73: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        74: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        75: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        76: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        77: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        78: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        79: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        80: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        81: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        82: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        83: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        84: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        85: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        86: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        87: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        88: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        89: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
    },

    genus_goethe: {
        1: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        2: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        3: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        4: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        5: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        6: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        7: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        8: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        9: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        10: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        11: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        12: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        13: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        14: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        15: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        16: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        17: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        18: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        19: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        20: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",

        21: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        22: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        23: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        24: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        25: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        26: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        27: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        28: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        29: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        30: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        31: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        32: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        33: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        34: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        35: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",

        36: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        37: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        38: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        39: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        40: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        41: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        42: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        43: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        44: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        45: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        46: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        47: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        48: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        49: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        50: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        51: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        52: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        53: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        54: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        55: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        56: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        57: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        58: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        59: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        60: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        61: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        62: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        63: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        64: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        65: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        66: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        67: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        68: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        69: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        70: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        71: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        72: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        73: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        74: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        75: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        76: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        77: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        78: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        79: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        80: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        81: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        82: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        83: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        84: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        85: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        86: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
        87: "Écrivez l'article défini (Der, Die ou Das) qui correspond au nom fourni :",
    },

    zahlen: {
        1: "Écrivez la forme écrite du nombre suivant :",
        2: "Écrivez la forme écrite du nombre suivant :",
        3: "Écrivez la forme écrite du nombre suivant :",
        4: "Écrivez la forme écrite du nombre suivant :",
        5: "Écrivez la forme écrite du nombre suivant :",
        6: "Écrivez la forme écrite du nombre suivant :",
        7: "Écrivez la forme écrite du nombre suivant :",
        8: "Écrivez la forme écrite du nombre suivant :",
        9: "Écrivez la forme écrite de l'heure suivante :",
        10: "Écrivez la forme écrite de l'heure suivante :",

        11: "Écrivez la forme écrite du nombre suivant :",
        12: "Écrivez la forme écrite du nombre suivant :",
        13: "Traduisez le nombre ordinal suivant :",
        14: "Traduisez le nombre ordinal suivant :",
        15: "Traduisez le nombre ordinal suivant :",
        16: "Complétez la phrase suivante avec le nombre ordinal qui convient :",

        17: "Traduisez l'adverbe de séquence suivant :",
        18: "Complétez la phrase suivante avec l'adverbe de séquence qui convient :",
        19: "Traduisez l'adverbe de fréquence suivant :",
        20: "Complétez la phrase suivante avec l'adverbe de fréquence qui convient :",

        21: "Traduisez la fraction suivante :",
        22: "Complétez la phrase suivante avec la fraction qui convient :",

        23: "Donnez la forme génitive du nombre suivant :",
        24: "Complétez la phrase suivante avec la forme génitive du nombre qui convient :",
    },

}
# arrow &#8594

