from data.data_processing.units import (
    praepositionen_grammatik, praepositionen_verben, praepositionen_adjektive, praepositionen_nomen,
    praepositionen_artikel, praepositionen_adverbien,
    artikel, pronomen, konnektoren, fragen, adverbien, wortstellung,
    adjektive, adjektivdeklinationen, adjektive_konjunktionen,
    verben, trennbare_verben, nomen_verben_verbindungen, nomen_verben_wortstaemme,
    praesens, imperativ, partizip_II, praeteritum, praeteritum_partizip_II, konjunktiv_II, konjunktiv_I, partizip_I,
    genus_regeln, genus_routledge, genus_goethe,
)

DESCRIPTION_EN = {

    praepositionen_grammatik: {
        1: "Temporal Prepositions, in sentences",
        2: "Local (Position) Prepositions, in sentences",
        3: "Local (Direction) Prepositions, in sentences",
        4: "Modal and Causal Prepositions, in sentences",

        5: "A1 Prepositions at A2 level in Temporal contexts, in sentences",
        6: "A1 Prepositions at A2 level in Local (Position) contexts, in sentences",
        7: "A1 Prepositions at A2 level in Local (Direction) contexts, in sentences",
        8: "A1 Prepositions at A2 level in Modal and Causal contexts, in sentences",

        9: "A1 Prepositions at B1 level, in sentences",
        10: "A1 Prepositions at B1 level, in sentences",
        11: "B1 Prepositions, in isolation",
        12: "B1 Prepositions, in sentences",

        13: "A1 Prepositions at B2 level, in sentences",
        14: "A1 Prepositions at B2 level, in sentences",
        15: "B2 Prepositions, in isolation",
        16: "B2 Prepositions, in sentences",

        17: "A1 Prepositions at C1 level, in sentences",
        18: "A1 Prepositions at C1 level, in sentences",
        19: "C1 Prepositions, in isolation",
        20: "C1 Prepositions, in sentences",
        21: "C1 Prepositions, in isolation",
        22: "C1 Prepositions, in sentences",
        23: "C1 Prepositional phrases, in isolation",
        24: "C1 Prepositional phrases, in sentences",
        25: "C1 Postpositions, in isolation",
        26: "C1 Postpositions, in sentences",
        27: "Synonyms of Prepositions, in isolation",
        28: "Antonyms of Prepositions, in isolation",

        29: "A1 Prepositions at C2 level, in sentences",
    },

    praepositionen_verben: {
        1: "A1 Verb-Preposition pairs, in isolation",
        2: "A1 Verb-Preposition pairs, in sentences",
        3: "A1 Verb-Preposition pairs, in isolation",
        4: "A1 Verb-Preposition pairs, in sentences",

        5: "A2 Verb-Preposition pairs, in isolation",
        6: "A2 Verb-Preposition pairs, in sentences",
        7: "A2 Verb-Preposition pairs, in isolation",
        8: "A2 Verb-Preposition pairs, in sentences",
        9: "Da-Words, in sentences",
        10: "Wo-Words, in sentences",

        11: "B1 Verb-Preposition pairs, in isolation",
        12: "B1 Verb-Preposition pairs, in sentences",
        13: "B1 Verb-Preposition pairs, in isolation",
        14: "B1 Verb-Preposition pairs, in sentences",
        15: "B1 Verb-Preposition pairs, in isolation",
        16: "B1 Verb-Preposition pairs, in sentences",
        17: "B1 Verb-Preposition pairs, in isolation",
        18: "B1 Verb-Preposition pairs, in sentences",

        19: "B2 Verb-Preposition pairs, in isolation",
        20: "B2 Verb-Preposition pairs, in sentences",
        21: "B2 Verb-Preposition pairs, in isolation",
        22: "B2 Verb-Preposition pairs, in sentences",
        23: "B2 Verb-Preposition pairs, in isolation",
        24: "B2 Verb-Preposition pairs, in sentences",
        25: "B2 Verb-Preposition pairs, in isolation",
        26: "B2 Verb-Preposition pairs, in sentences",

        27: "C1 Verb-Preposition pairs, in isolation",
        28: "C1 Verb-Preposition pairs, in sentences",
        29: "C1 Verb-Preposition pairs, in isolation",
        30: "C1 Verb-Preposition pairs, in sentences",
        31: "C1 Verb-Preposition pairs, in isolation",
        32: "C1 Verb-Preposition pairs, in sentences",
        33: "C1 Verb-Preposition pairs, in isolation",
        34: "C1 Verb-Preposition pairs, in sentences",

        35: "C2 Verb-Preposition pairs, in isolation",
        36: "C2 Verb-Preposition pairs, in sentences",
        37: "C2 Verb-Preposition pairs, in isolation",
        38: "C2 Verb-Preposition pairs, in sentences",
        39: "C2 Verb-Preposition pairs, in isolation",
        40: "C2 Verb-Preposition pairs, in sentences",
        41: "C2 Verb-Preposition pairs, in isolation",
        42: "C2 Verb-Preposition pairs, in sentences",
    },

    praepositionen_adjektive: {
        1: "Up to B1 Adjective-Preposition pairs, in isolation",
        2: "Up to B1 Adjective-Preposition pairs, in sentences",
        3: "Up to B1 Adjective-Preposition pairs, in isolation",
        4: "Up to B1 Adjective-Preposition pairs, in sentences",

        5: "B2 Adjective-Preposition pairs, in isolation",
        6: "B2 Adjective-Preposition pairs, in sentences",
        7: "B2 Adjective-Preposition pairs, in isolation",
        8: "B2 Adjective-Preposition pairs, in sentences",
        9: "B2 Adjective-Preposition pairs, in isolation",
        10: "B2 Adjective-Preposition pairs, in sentences",

        11: "C1 Adjective-Preposition pairs, in isolation",
        12: "C1 Adjective-Preposition pairs, in sentences",
        13: "C1 Adjective-Preposition pairs, in isolation",
        14: "C1 Adjective-Preposition pairs, in sentences",
        15: "C1 Adjective-Preposition pairs, in isolation",
        16: "C1 Adjective-Preposition pairs, in sentences",
        17: "C1 Adjective-Preposition pairs, in isolation",
        18: "C1 Adjective-Preposition pairs, in sentences",
    },

    praepositionen_nomen: {
        1: "Up to B1 Noun-Preposition pairs, in isolation",
        2: "Up to B1 Noun-Preposition pairs, in sentences",
        3: "Up to B1 Noun-Preposition pairs, in isolation",
        4: "Up to B1 Noun-Preposition pairs, in sentences",
        5: "Up to B1 Noun-Preposition pairs, in isolation",
        6: "Up to B1 Noun-Preposition pairs, in sentences",

        7: "B2 Noun-Preposition pairs, in isolation",
        8: "B2 Noun-Preposition pairs, in sentences",
        9: "B2 Noun-Preposition pairs, in isolation",
        10: "B2 Noun-Preposition pairs, in sentences",
        11: "B2 Noun-Preposition pairs, in isolation",
        12: "B2 Noun-Preposition pairs, in sentences",
        13: "B2 Noun-Preposition pairs, in isolation",
        14: "B2 Noun-Preposition pairs, in sentences",
        15: "B2 Noun-Preposition pairs, in isolation",
        16: "B2 Noun-Preposition pairs, in sentences",

        17: "C1 Noun-Preposition pairs, in isolation",
        18: "C1 Noun-Preposition pairs, in sentences",
        19: "C1 Noun-Preposition pairs, in isolation",
        20: "C1 Noun-Preposition pairs, in sentences",
        21: "C1 Noun-Preposition pairs, in isolation",
        22: "C1 Noun-Preposition pairs, in sentences",
        23: "C1 Noun-Preposition pairs, in isolation",
        24: "C1 Noun-Preposition pairs, in sentences",
        25: "C1 Noun-Preposition pairs, in isolation",
        26: "C1 Noun-Preposition pairs, in sentences",
    },

    praepositionen_artikel: {
        1: "Articles and Pronouns following Prepositions, in sentences",
        2: "Articles and Pronouns following Prepositions, in sentences",
        3: "Articles and Pronouns following Prepositions, in sentences",
        4: "Articles and Pronouns following Verb-Preposition pairs, in sentences",
        5: "Articles and Pronouns following Verb-Preposition pairs, in sentences",

        6: "Articles and Pronouns following Prepositions, in sentences",
        7: "Articles and Pronouns following Prepositions, in sentences",
        8: "Articles and Pronouns following Verb-Preposition pairs, in sentences",
        9: "Articles and Pronouns following Verb-Preposition pairs, in sentences",
    },

    praepositionen_adverbien: {
        1: "Something",
        2: "Something",
        3: "Something",
        4: "Something",
    },

    artikel: {
        1: "Definite articles <i>Der Die Das</i>, in isolation",
        2: "Definite articles in the Nominative case, in sentences",
        3: "Definite articles in the Accusative case, in sentences",
        4: "Definite articles in the Dative case, in sentences",
        5: "Definite Feminine articles, in sentences",
        6: "Definite Masculine articles, in sentences",
        7: "Definite Neuter articles, in sentences",
        8: "Definite Plural articles, in sentences",
        9: "Mix of Definite articles in the Nominative, Accusative and Dative cases, in sentences",
        10: "Mix of Definite articles in the Nominative, Accusative and Dative cases, in sentences",
        11: "Indefinite articles <i>Ein</i>, in isolation",
        12: "Indefinite articles in the Nominative case, in sentences",
        13: "Indefinite articles in the Accusative case, in sentences",
        14: "Indefinite articles in the Dative case, in sentences",
        15: "Indefinite Feminine articles, in sentences",
        16: "Indefinite Masculine articles, in sentences",
        17: "Indefinite Neuter articles, in sentences",
        18: "Mix of Indefinite articles in the Nominative, Accusative and Dative cases, in sentences",
        19: "Mix of Indefinite articles in the Nominative, Accusative and Dative cases, in sentences",
        20: "Negative articles <i>Kein</i>, in isolation",
        21: "Negative articles <i>Kein</i>, in sentences",
        22: "Possessive articles linked to Singular pronouns (<i>Ich</i>, <i>Du</i>, <i>Er</i>, <i>Sie</i>, <i>Es</i>), in isolation",
        23: "Possessive articles linked to Singular pronouns (<i>Ich</i>, <i>Du</i>, <i>Er</i>, <i>Sie</i>, <i>Es</i>), in sentences",
        24: "Possessive articles linked to Plural (<i>Wir</i>, <i>Ihr</i>, <i>Sie</i>) and Formal pronouns, in isolation",
        25: "Possessive articles linked to Plural (<i>Wir</i>, <i>Ihr</i>, <i>Sie</i>) and Formal pronouns, in sentences",

        26: "Demonstrative articles <em>Diese</em>, in isolation",
        27: "Demonstrative articles <em>Diese</em>, in sentences",
        28: "Articles <em>Jede</em>, in isolation",
        29: "Articles <em>Jede</em>, in sentences",
        30: "Definite articles with prepositions in the Accusative and Dative cases, in sentences",
        31: "Definite articles with prepositions in the Accusative and Dative cases, in sentences",
        32: "A2 articles, in isolation",
        33: "A2 articles, in sentences",

        34: "Definite, Indefinite and Negative articles in the Genitive case, in isolation",
        35: "Definite, Indefinite and Negative articles in the Genitive case, in sentences",
        36: "<em>Diese</em> and <em>Jede</em> in the Genitive case, in isolation",
        37: "<em>Diese</em> and <em>Jede</em> in the Genitive case, in sentences",
        38: "Possessive articles in the Genitive case, in isolation",
        39: "Possessive articles in the Genitive case, in sentences",

        40: "<em>Jene</em>, <em>Eine der</em> and <em>Irgendeine</em> articles, in isolation",
        41: "<em>Jene</em>, <em>Eine der</em> and <em>Irgendeine</em> articles, in sentences",

        42: "<em>Diejenige</em> and <em>Dieselbe</em> articles, in isolation",
        43: "<em>Diejenige</em> and <em>Dieselbe</em> articles, in sentences",
        44: "Articles in Appositions, in sentences",
        45: "Articles in Appositions, in sentences",
    },

    pronomen: {
        1: "Nominative Pronouns, in isolation",
        2: "Nominative Pronouns, in sentences",
        3: "Accusative Pronouns , in isolation",
        4: "Accusative Pronouns, in sentences",
        5: "Dative Pronouns, in isolation",
        6: "Dative Pronouns, in sentences",
        7: "Mix of Accusative and Dative Pronouns, in sentences",
        8: "Mix of Accusative and Dative Pronouns, in sentences",
        9: "Replacing Accusative and Dative nouns with pronouns, in sentences",
        10: "Replacing Accusative and Dative nouns with pronouns, in sentences",

        11: "Reflexive Pronouns, in isolation",
        12: "Reflexive Pronouns, in sentences",
        13: "Mix of Accusative, Dative, and Reflexive Pronouns, in sentences",
        14: "Mix of Accusative, Dative, and Reflexive Pronouns, in sentences",

        15: "B1 Pronouns <em>Nichts</em>, <em>Man</em>, <em>Jemand</em> etc., in isolation",
        16: "B1 Pronouns <em>Nichts</em>, <em>Man</em>, <em>Jemand</em> etc., in sentences",
        17: "Relative Nominative Pronouns, in sentences",
        18: "Relative Accusative Pronouns, in sentences",
        19: "Relative Dative Pronouns, in sentences",
        20: "Relative Genitive Pronouns, in sentences",
        21: "Mix of Relative Pronouns, in sentences",
        22: "Mix of Relative Pronouns, in sentences",

        23: "Mix of Relative Pronouns, in sentences",
        24: "Mix of Relative Pronouns, in sentences",
        25: "Relative Pronouns for locations and directions, in sentences",
        26: "Possessive Pronouns linked to Singular pronouns (<i>Ich</i>, <i>Du</i>, <i>Er</i>, <i>Sie</i>, <i>Es</i>), in isolation",
        27: "Possessive Pronouns linked to Singular pronouns (<i>Ich</i>, <i>Du</i>, <i>Er</i>, <i>Sie</i>, <i>Es</i>), in sentences",
        28: "Possessive Pronouns linked to Plural (<i>Wir</i>, <i>Ihr</i>, <i>Sie</i>) and Formal pronouns, in isolation",
        29: "Possessive Pronouns linked to Plural (<i>Wir</i>, <i>Ihr</i>, <i>Sie</i>) and Formal pronouns, in sentences",

        30: "Relative Pronouns Was und Wer, in sentences",
    },

    konnektoren: {
        1: "A1 Connectors, in isolation",
        2: "A1 Connectors, in sentences",

        3: "A2 Connectors, in isolation",
        4: "A2 Connectors, in sentences",

        5: "B1 Connectors, in isolation",
        6: "B1 Connectors, in sentences",
        7: "B1 Connectors, in isolation",
        8: "B1 Connectors, in sentences",
        9: "B1 Connectors, in isolation",
        10: "B1 Connectors, in sentences",
        11: "Synonyms of Connectors at B1 level, in isolation",

        12: "B2 Connectors, in isolation",
        13: "B2 Connectors, in sentences",
        14: "B2 Connectors, in isolation",
        15: "B2 Connectors, in sentences",
        16: "B2 Connectors, in isolation",
        17: "B2 Connectors, in sentences",
        18: "Synonyms of Connectors at B2 level, in isolation",

        19: "C1 Connectors, in isolation",
        20: "C1 Connectors, in sentences",
        21: "C1 Connectors, in isolation",
        22: "C1 Connectors, in sentences",
        23: "C1 Connectors, in isolation",
        24: "C1 Connectors, in sentences",
        25: "C1 Connectors, in isolation",
        26: "C1 Connectors, in sentences",
        27: "C1 Connectors, in isolation",
        28: "C1 Connectors, in sentences",
        29: "Synonyms of Connectors at C1 level, in isolation",
        30: "Synonyms of Connectors at C1 level, in isolation",
        31: "Synonyms of Connectors at C1 level, in isolation",
        32: "Synonyms of Connectors at C1 level, in isolation",
    },

    fragen: {
        1: 'A1 Question Words, in isolation',
        2: 'A1 Question Words, in sentences',

        3: 'A2 Question Words, in isolation',
        4: 'A2 Question Words, in sentences',

        5: 'B1 Question Words, in isolation',
        6: 'B1 Question Words, in sentences',

        7: 'B2 Question Words, in isolation',
        8: 'B2 Question Words, in sentences',
        9: 'B2 Question Words, in isolation (Welch-Party)',
        10: 'B2 Question Words, in sentences (Welch-Party)',

        11: 'C1 Question Words, in isolation',
        12: 'C1 Question Words, in sentences',
    },

    adverbien: {
        1: "A1 Adverbs, in isolation",
        2: "A1 Adverbs, in sentences",
        3: "A1 Adverbs, in isolation",
        4: "A1 Adverbs, in sentences",

        5: "A2 Adverbs, in isolation",
        6: "A2 Adverbs, in sentences",
        7: "A2 Adverbs, in isolation",
        8: "A2 Adverbs, in sentences",
        9: "Synonyms of A1 and A2 Adverbs, in isolation",
        10: "Antonyms of A1 and A2 Adverbs, in isolation",

        11: "B1 Adverbs, in isolation",
        12: "B1 Adverbs, in sentences",
        13: "B1 Adverbs, in isolation",
        14: "B1 Adverbs, in sentences",
        15: "B1 Adverbs, in isolation",
        16: "B1 Adverbs, in sentences",
        17: "B1 Adverbs, in isolation",
        18: "B1 Adverbs, in sentences",
        19: "Synonyms of B1 Adverbs, in isolation",
        20: "Antonyms of B1 Adverbs, in isolation",

        21: "B2 Adverbs, in isolation",
        22: "B2 Adverbs, in sentences",
        23: "B2 Adverbs, in isolation",
        24: "B2 Adverbs, in sentences",
        25: "B2 Adverbs, in isolation",
        26: "B2 Adverbs, in sentences",
        27: "B2 Adverbs, in isolation",
        28: "B2 Adverbs, in sentences",
        29: "Synonyms of B2 Adverbs, in isolation",
        30: "Antonyms of B2 Adverbs, in isolation",

        31: "B2 Adverbs, in isolation",
        32: "B2 Adverbs, in sentences",
        33: "B2 Adverbs, in isolation",
        34: "B2 Adverbs, in sentences",
        35: "B2 Adverbs, in isolation",
        36: "B2 Adverbs, in sentences",
        37: "B2 Adverbs, in isolation",
        38: "B2 Adverbs, in sentences",
        39: "Synonyms of B2 Adverbs, in isolation",
        40: "Antonyms of B2 Adverbs, in isolation",

        41: "Temporal Adverbs, in isolation",
        42: "Temporal Adverbs, in isolation",
        43: "Local Adverbs, in isolation",
        44: "Local Adverbs, in sentences",
        45: "Modal Adverbs, in isolation",
        46: "Modal Adverbs, in sentences",
        47: "Adverbs in <i>-einander</i>, in isolation",
        48: "Adverbs in <i>-einander</i>, in sentences",
        49: "Synonyms of C1 Adverbs, in isolation",
        50: "Antonyms of C1 Adverbs, in isolation",

        51: "Temporal Adverbs in <i>-mals</i>, <i>-falls</i> and <i>-mal</i>, in isolation",
        52: "Temporal Adverbs in <i>-mals</i>, <i>-falls</i> and <i>-mal</i>, in sentences",
        53: "Local Adverbs in <i>-wärts</i>, in isolation",
        54: "Local Adverbs in <i>-wärts</i>, in sentences",
        55: "Modal Adverbs, in isolation",
        56: "Modal Adverbs, in sentences",
        57: "Adverbial phrases made of prepositions, in isolation",
        58: "Adverbial phrases made of prepositions, in sentences",
        59: "Synonyms of C1 Adverbs, in isolation",
        60: "Antonyms of C1 Adverbs, in isolation",

        61: "Temporal Adverbs, in isolation",
        62: "Temporal Adverbs, in sentences",
        63: "Local Adverbs in <i>Hin</i> and <i>Her</i>, in isolation",
        64: "Local Adverbs in <i>Hin</i> and <i>Her</i>, in sentences",
        65: "Modal Adverbs in <i>-weise</i>, in isolation",
        66: "Modal Adverbs in <i>-weise</i>, in sentences",
        67: "Other Adverbs, in isolation",
        68: "Other Adverbs, in sentences",
        69: "Synonyms of C1 Adverbs, in isolation",
        70: "Antonyms of C1 Adverbs, in isolation",

        71: "Temporal Adverbs, in isolation",
        72: "Temporal Adverbs, in sentences",
        73: "Other Adverbs, in isolation",
        74: "Other Adverbs, in sentences",
        75: "Other Adverbs, in isolation",
        76: "Other Adverbs, in sentences",
        77: "Other Adverbs, in isolation",
        78: "Other Adverbs, in sentences",
        79: "Synonyms of C1 Adverbs, in isolation",
        80: "Synonyms of C1 Adverbs, in isolation",
    },

    wortstellung: {
        1: "Placeholder",
    },

    adjektive: {
        1: "A1 Adjectives, in isolation",
        2: "A1 Adjectives, in isolation",
        3: "A1 Adjectives, in isolation",
        4: "Antonyms of A1 Adjectives, in isolation",
        5: "Antonyms of A1 Adjectives, in isolation",
        6: "A1 Comparatives, in isolation",
        7: "A1 Comparatives, in isolation",
        8: "A1 Comparatives, in isolation",
        9: "A1 Superlatives, in isolation",
        10: "A1 Superlatives, in isolation",
        11: "A1 Superlatives, in isolation",

        12: "A2 Adjectives, in isolation",
        13: "A2 Adjectives, in isolation",
        14: "A2 Adjectives, in isolation",
        15: "Antonyms of A2 Adjectives, in isolation",
        16: "Antonyms of A2 Adjectives, in isolation",
        17: "A2 Comparatives, in isolation",
        18: "A2 Comparatives, in isolation",
        19: "A2 Comparatives, in isolation",
        20: "A2 Superlatives, in isolation",
        21: "A2 Superlatives, in isolation",
        22: "A2 Superlatives, in isolation",

        23: "B1 German to English Adjectives translations (Multiple choice)",
        24: "B1 German to English Adjectives translations (Multiple choice)",
        25: "B1 German to English Adjectives translations (Multiple choice)",
        26: "B1 English to German Adjectives translations (Multiple choice)",
        27: "B1 English to German Adjectives translations (Multiple choice)",
        28: "B1 English to German Adjectives translations (Multiple choice)",

        29: "B2 German to English Adjectives translations (Multiple choice)",
        30: "B2 German to English Adjectives translations (Multiple choice)",
        31: "B2 German to English Adjectives translations (Multiple choice)",
        32: "B2 English to German Adjectives translations (Multiple choice)",
        33: "B2 English to German Adjectives translations (Multiple choice)",
        34: "B2 English to German Adjectives translations (Multiple choice)",
    },

    adjektivdeklinationen: {
        1: "Nominative Adjective Declensions, in isolation",
        2: "Nominative Adjective Declensions, in sentences",
        3: "Accusative Adjective Declensions, in isolation",
        4: "Accusative Adjective Declensions, in sentences",
        5: "Dative Adjective Declensions, in isolation",
        6: "Dative Adjective Declensions, in sentences",
        7: "Definite Articles' Adjective Declensions, in isolation",
        8: "Definite Articles' Adjective Declensions, in sentences",
        9: "Indefinite Articles' Adjective Declensions, in isolation",
        10: "Indefinite Articles' Adjective Declensions, in sentences",
        11: "Mix of Nominative, Accusative, and Dative Adjective Declensions, in sentences",
        12: "Mix of Nominative, Accusative, and Dative Adjective Declensions, in sentences",
        13: "Possessive Adjective Declensions, in isolation",
        14: "Possessive Adjective Declensions, in sentences",

        15: "Genitive Adjective Declensions, in isolation",
        16: "Genitive Adjective Declensions, in sentences",
        17: "Null Article's Adjective Declensions, in isolation",
        18: "Null Article's Adjective Declensions, in sentences",
        19: "Negative Adjective Declensions, in isolation",
        20: "Negative Adjective Declensions, in sentences",
        21: "Comparative Adjective Declensions, in isolation",
        22: "Comparative Adjective Declensions, in sentences",
        23: "Superlative Adjective Declensions, in isolation",
        24: "Superlative Adjective Declensions, in sentences",

        25: "Demonstrative Adjective Declensions, in isolation",
        26: "Demonstrative Adjective Declensions, in sentences",

        27: "Adjective Declensions of Singular Articles <i>etwas</i>, <i>viel</i>, <i>mehr</i>, in isolation",
        28: "Adjective Declensions of Singular Articles <i>etwas</i>, <i>viel</i>, <i>mehr</i>, in sentences",
        29: "Adjective Declensions of Plural Articles <i>alle</i>, <i>viele</i>, and Numeral Articles, in isolation",
        30: "Adjective Declensions of Plural Articles <i>alle</i>, <i>viele</i>, and Numeral Articles, in sentences",
    },

    adjektive_konjunktionen: {
        1: "Adjective Conjunctions, in sentences",

        2: "Adjective Conjunctions, in sentences",

        3: "Adjective Conjunctions, in sentences",

        4: "Adjective Conjunctions, in sentences",
    },

    verben: {
        1: "English to German translation of A1 Verbs",
        2: "English to German translation of A1 Verbs",
        3: "English to German translation of A1 Verbs",
        4: "English to German translation of A1 Verbs",
        5: "English to German translation of A1 Verbs",

        6: "English to German translation of A2 Verbs",
        7: "English to German translation of A2 Verbs",
        8: "English to German translation of A2 Verbs",
        9: "English to German translation of A2 Verbs",
        10: "English to German translation of A2 Verbs",

        11: "English to German translation of B1 Verbs (Multiple choice)",
        12: "English to German translation of B1 Verbs (Multiple choice)",
        13: "English to German translation of B1 Verbs (Multiple choice)",
        14: "English to German translation of B1 Verbs (Multiple choice)",
        15: "English to German translation of B1 Verbs (Multiple choice)",
        16: "German to English translation of B1 Verbs (Multiple choice)",
        17: "German to English translation of B1 Verbs (Multiple choice)",
        18: "German to English translation of B1 Verbs (Multiple choice)",
        19: "German to English translation of B1 Verbs (Multiple choice)",
        20: "German to English translation of B1 Verbs (Multiple choice)",

        21: "English to German translation of B2 Verbs (Multiple choice)",
        22: "English to German translation of B2 Verbs (Multiple choice)",
        23: "English to German translation of B2 Verbs (Multiple choice)",
        24: "English to German translation of B2 Verbs (Multiple choice)",
        25: "English to German translation of B2 Verbs (Multiple choice)",
        26: "German to English translation of B2 Verbs (Multiple choice)",
        27: "German to English translation of B2 Verbs (Multiple choice)",
        28: "German to English translation of B2 Verbs (Multiple choice)",
        29: "German to English translation of B2 Verbs (Multiple choice)",
        30: "German to English translation of B2 Verbs (Multiple choice)",

        31: "English to German translation of C1 Verbs (Multiple choice)",
        32: "English to German translation of C1 Verbs (Multiple choice)",
        33: "English to German translation of C1 Verbs (Multiple choice)",
        34: "English to German translation of C1 Verbs (Multiple choice)",
        35: "English to German translation of C1 Verbs (Multiple choice)",
        36: "English to German translation of C1 Verbs (Multiple choice)",
        37: "English to German translation of C1 Verbs (Multiple choice)",
        38: "English to German translation of C1 Verbs (Multiple choice)",
        39: "English to German translation of C1 Verbs (Multiple choice)",
        40: "English to German translation of C1 Verbs (Multiple choice)",
        41: "German to English translation of C1 Verbs (Multiple choice)",
        42: "German to English translation of C1 Verbs (Multiple choice)",
        43: "German to English translation of C1 Verbs (Multiple choice)",
        44: "German to English translation of C1 Verbs (Multiple choice)",
        45: "German to English translation of C1 Verbs (Multiple choice)",
        46: "German to English translation of C1 Verbs (Multiple choice)",
        47: "German to English translation of C1 Verbs (Multiple choice)",
        48: "German to English translation of C1 Verbs (Multiple choice)",
        49: "German to English translation of C1 Verbs (Multiple choice)",
        50: "German to English translation of C1 Verbs (Multiple choice)",
    },

    trennbare_verben: {
        1: "A1 (un)trennbare Verbs with root help",
        2: "A1 (un)trennbare Verbs with prefix help",
        3: "A1 (un)trennbare Verbs with no help",

        4: "A2 (un)trennbare Verbs with root help",
        5: "A2 (un)trennbare Verbs with prefix help",
        6: "A2 (un)trennbare Verbs with no help",

        7: "B1 (un)trennbare Verbs with root help",
        8: "B1 (un)trennbare Verbs with root help",
        9: "B1 (un)trennbare Verbs with root help",
        10: "B1 (un)trennbare Verbs with root help",
        11: "B1 (un)trennbare Verbs with prefix help",
        12: "B1 (un)trennbare Verbs with prefix help",
        13: "B1 (un)trennbare Verbs with prefix help",
        14: "B1 (un)trennbare Verbs with prefix help",
        15: "B1 (un)trennbare Verbs with no help",
        16: "B1 (un)trennbare Verbs with no help",
        17: "B1 (un)trennbare Verbs with no help",
        18: "B1 (un)trennbare Verbs with no help",

        19: "B2 (un)trennbare Verbs with root help",
        20: "B2 (un)trennbare Verbs with root help",
        21: "B2 (un)trennbare Verbs with root help",
        22: "B2 (un)trennbare Verbs with root help",
        23: "B2 (un)trennbare Verbs with prefix help",
        24: "B2 (un)trennbare Verbs with prefix help",
        25: "B2 (un)trennbare Verbs with prefix help",
        26: "B2 (un)trennbare Verbs with prefix help",
        27: "B2 (un)trennbare Verbs with no help",
        28: "B2 (un)trennbare Verbs with no help",
        29: "B2 (un)trennbare Verbs with no help",
        30: "B2 (un)trennbare Verbs with no help",

        31: "(Un)trennbare Verbs in geben",
        32: "(Un)trennbare Verbs in stellen",
        33: "(Un)trennbare Verbs in nehmen",
        34: "(Un)trennbare Verbs in halten",
        35: "(Un)trennbare Verbs in gehen",
        36: "(Un)trennbare Verbs in ziehen",
        37: "(Un)trennbare Verbs in kommen",
        38: "(Un)trennbare Verbs in weisen",
        39: "(Un)trennbare Verbs in setzen",
        40: "(Un)trennbare Verbs in führen",
        41: "(Un)trennbare Verbs in lassen",
        42: "(Un)trennbare Verbs in fassen",
        43: "(Un)trennbare Verbs in sehen",
        44: "(Un)trennbare Verbs in schreiben",
        45: "(Un)trennbare Verbs in legen",
        46: "(Un)trennbare Verbs in schließen",
        47: "C1 (un)trennbare Verbs with root help",
        48: "C1 (un)trennbare Verbs with root help",
        49: "C1 (un)trennbare Verbs with root help",
        50: "C1 (un)trennbare Verbs with root help",
        51: "C1 (un)trennbare Verbs with root help",
        52: "C1 (un)trennbare Verbs with root help",
        53: "C1 (un)trennbare Verbs with root help",
        54: "C1 (un)trennbare Verbs with root help",
        55: "C1 (un)trennbare Verbs with prefix help",
        56: "C1 (un)trennbare Verbs with prefix help",
        57: "C1 (un)trennbare Verbs with prefix help",
        58: "C1 (un)trennbare Verbs with prefix help",
        59: "C1 (un)trennbare Verbs with prefix help",
        60: "C1 (un)trennbare Verbs with prefix help",
        61: "C1 (un)trennbare Verbs with prefix help",
        62: "C1 (un)trennbare Verbs with prefix help",
        63: "C1 (un)trennbare Verbs with no help (Multiple Choice)",
        64: "C1 (un)trennbare Verbs with no help (Multiple Choice)",
        65: "C1 (un)trennbare Verbs with no help (Multiple Choice)",
        66: "C1 (un)trennbare Verbs with no help (Multiple Choice)",
        67: "C1 (un)trennbare Verbs with no help (Multiple Choice)",
        68: "C1 (un)trennbare Verbs with no help (Multiple Choice)",
        69: "C1 (un)trennbare Verbs with no help (Multiple Choice)",
        70: "C1 (un)trennbare Verbs with no help (Multiple Choice)",
    },

    nomen_verben_verbindungen: {
        1: "B1 Noun-Verb Combinations with the Noun missing, in isolation",
        2: "B1 Noun-Verb Combinations with the Verb missing, in isolation",
        3: "B1 Noun-Verb Combinations with the Noun missing, in sentences",
        4: "B1 Noun-Verb Combinations with the Verb missing, in sentences",

        5: "B2 Noun-Verb Combinations with the Noun missing, in isolation",
        6: "B2 Noun-Verb Combinations with the Verb missing, in isolation",
        7: "B2 Noun-Verb Combinations with the Noun missing, in sentences",
        8: "B2 Noun-Verb Combinations with the Verb missing, in sentences",
        9: "B2 Noun-Verb Combinations with the Noun missing, in isolation",
        10: "B2 Noun-Verb Combinations with the Verb missing, in isolation",
        11: "B2 Noun-Verb Combinations with the Noun missing, in sentences",
        12: "B2 Noun-Verb Combinations with the Verb missing, in sentences",
        13: "B2 Noun-Verb Combinations with the Noun missing, in isolation",
        14: "B2 Noun-Verb Combinations with the Verb missing, in isolation",
        15: "B2 Noun-Verb Combinations with the Noun missing, in sentences",
        16: "B2 Noun-Verb Combinations with the Verb missing, in sentences",

        17: "C1 Noun-Verb Combinations with the Noun missing, in isolation",
        18: "C1 Noun-Verb Combinations with the Verb missing, in isolation",
        19: "C1 Noun-Verb Combinations with the Noun missing, in sentences",
        20: "C1 Noun-Verb Combinations with the Verb missing, in sentences",
        21: "C1 Noun-Verb Combinations with the Noun missing, in isolation",
        22: "C1 Noun-Verb Combinations with the Verb missing, in isolation",
        23: "C1 Noun-Verb Combinations with the Noun missing, in sentences",
        24: "C1 Noun-Verb Combinations with the Verb missing, in sentences",
        25: "C1 Noun-Verb Combinations with the Noun missing, in isolation",
        26: "C1 Noun-Verb Combinations with the Verb missing, in isolation",
        27: "C1 Noun-Verb Combinations with the Noun missing, in sentences",
        28: "C1 Noun-Verb Combinations with the Verb missing, in sentences",
        29: "C1 Noun-Verb Combinations with the Noun missing, in isolation",
        30: "C1 Noun-Verb Combinations with the Verb missing, in isolation",
        31: "C1 Noun-Verb Combinations with the Noun missing, in sentences",
        32: "C1 Noun-Verb Combinations with the Verb missing, in sentences",
    },

    nomen_verben_wortstaemme: {
        1: "Verb missing in the Noun-Verb Pair",
        2: "Noun missing in the Noun-Verb Pair",

        3: "Verb missing in the Noun-Verb Pair",
        4: "Noun missing in the Noun-Verb Pair",
        5: "Verb missing in the Noun-Verb Pair",
        6: "Noun missing in the Noun-Verb Pair",
        7: "Verb missing in the Noun-Verb Pair",
        8: "Noun missing in the Noun-Verb Pair",

        9: "Verb missing in the Noun-Verb Pair",
        10: "Noun missing in the Noun-Verb Pair",
        11: "Verb missing in the Noun-Verb Pair",
        12: "Noun missing in the Noun-Verb Pair",
        13: "Verb missing in the Noun-Verb Pair",
        14: "Noun missing in the Noun-Verb Pair",
        15: "Verb missing in the Noun-Verb Pair",
        16: "Noun missing in the Noun-Verb Pair",
        17: "Verb missing in the Noun-Verb Pair",
        18: "Noun missing in the Noun-Verb Pair",

        19: "Verb missing in the Noun-Verb Pair",
        20: "Noun missing in the Noun-Verb Pair",
        21: "Verb missing in the Noun-Verb Pair",
        22: "Noun missing in the Noun-Verb Pair",
        23: "Verb missing in the Noun-Verb Pair",
        24: "Noun missing in the Noun-Verb Pair",
        25: "Verb missing in the Noun-Verb Pair",
        26: "Noun missing in the Noun-Verb Pair",
        27: "Verb missing in the Noun-Verb Pair",
        28: "Noun missing in the Noun-Verb Pair",
        29: "Verb missing in the Noun-Verb Pair",
        30: "Noun missing in the Noun-Verb Pair",
        31: "Verb missing in the Noun-Verb Pair",
        32: "Noun missing in the Noun-Verb Pair",
        33: "Verb missing in the Noun-Verb Pair",
        34: "Noun missing in the Noun-Verb Pair",
        35: "Verb missing in the Noun-Verb Pair",
        36: "Noun missing in the Noun-Verb Pair",
        37: "Verb missing in the Noun-Verb Pair",
        38: "Noun missing in the Noun-Verb Pair",
        39: "Verb missing in the Noun-Verb Pair",
        40: "Noun missing in the Noun-Verb Pair",
        41: "Verb missing in the Noun-Verb Pair",
        42: "Noun missing in the Noun-Verb Pair",
        43: "Verb missing in the Noun-Verb Pair",
        44: "Noun missing in the Noun-Verb Pair",
        45: "Verb missing in the Noun-Verb Pair",
        46: "Noun missing in the Noun-Verb Pair",
        47: "Verb missing in the Noun-Verb Pair",
        48: "Noun missing in the Noun-Verb Pair",
        49: "Verb missing in the Noun-Verb Pair",
        50: "Noun missing in the Noun-Verb Pair",
        51: "Verb missing in the Noun-Verb Pair",
        52: "Noun missing in the Noun-Verb Pair",
        53: "Verb missing in the Noun-Verb Pair",
        54: "Noun missing in the Noun-Verb Pair",
        55: "Verb missing in the Noun-Verb Pair",
        56: "Noun missing in the Noun-Verb Pair",
        57: "Verb missing in the Noun-Verb Pair",
        58: "Noun missing in the Noun-Verb Pair",
        59: "Verb missing in the Noun-Verb Pair",
        60: "Noun missing in the Noun-Verb Pair",

        61: "Verb missing in the Noun-Verb Pair",
        62: "Noun missing in the Noun-Verb Pair",
        63: "Verb missing in the Noun-Verb Pair",
        64: "Noun missing in the Noun-Verb Pair",
        65: "Verb missing in the Noun-Verb Pair",
        66: "Noun missing in the Noun-Verb Pair",
        67: "Verb missing in the Noun-Verb Pair",
        68: "Noun missing in the Noun-Verb Pair",
        69: "Verb missing in the Noun-Verb Pair",
        70: "Noun missing in the Noun-Verb Pair",
        71: "Verb missing in the Noun-Verb Pair",
        72: "Noun missing in the Noun-Verb Pair",
        73: "Verb missing in the Noun-Verb Pair",
        74: "Noun missing in the Noun-Verb Pair",
        75: "Verb missing in the Noun-Verb Pair",
        76: "Noun missing in the Noun-Verb Pair",
        77: "Verb missing in the Noun-Verb Pair",
        78: "Noun missing in the Noun-Verb Pair",
        79: "Verb missing in the Noun-Verb Pair",
        80: "Noun missing in the Noun-Verb Pair",
        81: "Verb missing in the Noun-Verb Pair",
        82: "Noun missing in the Noun-Verb Pair",
        83: "Verb missing in the Noun-Verb Pair",
        84: "Noun missing in the Noun-Verb Pair",
        85: "Verb missing in the Noun-Verb Pair",
        86: "Noun missing in the Noun-Verb Pair",
        87: "Verb missing in the Noun-Verb Pair",
        88: "Noun missing in the Noun-Verb Pair",
        89: "Verb missing in the Noun-Verb Pair",
        90: "Noun missing in the Noun-Verb Pair",
        91: "Verb missing in the Noun-Verb Pair",
        92: "Noun missing in the Noun-Verb Pair",
    },

    praesens: {
        1: "Present tense of A1 verbs, in isolation",
        2: "Present tense of A1 verbs, in isolation",
        3: "Present tense of A1 verbs, in isolation",
        4: "Present tense of A1 verbs, in isolation",
        5: "Present tense of A1 verbs, in isolation",
        6: "Present tense of A1 verbs, in isolation",
        7: "Present tense of A1 verbs, in isolation",
        8: "Present tense of A1 verbs, in isolation",
        9: "Present tense of A1 verbs, in isolation",
        10: "Present tense of A1 verbs, in isolation",
        11: "Present tense of A1 verbs, in isolation",
        12: "Present tense of A1 verbs, in isolation",
        13: "Present tense of A1 verbs, in isolation",
        14: "Present tense of A1 verbs, in isolation",
        15: "Present tense of A1 verbs, in isolation",
        16: "Present tense of A1 verbs, in isolation",
        17: "Present tense of A1 verbs, in isolation",
        18: "Present tense of A1 verbs, in isolation",
        19: "Present tense of A1 verbs, in isolation",
        20: "Present tense of A1 verbs, in isolation",

        21: "Present tense of A2 verbs, in isolation",
        22: "Present tense of A2 verbs, in isolation",
        23: "Present tense of A2 verbs, in isolation",
        24: "Present tense of A2 verbs, in isolation",
        25: "Present tense of A2 verbs, in isolation",
        26: "Present tense of A2 verbs, in isolation",
        27: "Present tense of A2 verbs, in isolation",
        28: "Present tense of A2 verbs, in isolation",
        29: "Present tense of A2 verbs, in isolation",
        30: "Present tense of A2 verbs, in isolation",
        31: "Present tense of A2 verbs, in isolation",
        32: "Present tense of A2 verbs, in isolation",
        33: "Present tense of A2 verbs, in isolation",
        34: "Present tense of A2 verbs, in isolation",
        35: "Present tense of A2 verbs, in isolation",
        36: "Present tense of A2 verbs, in isolation",
        37: "Present tense of A2 verbs, in isolation",
        38: "Present tense of A2 verbs, in isolation",
        39: "Present tense of A2 verbs, in isolation",
        40: "Present tense of A2 verbs, in isolation",
    },

    partizip_II: {
        1: "Partizip II of irregular A1 verbs",
        2: "Partizip II of irregular A1 verbs",
        3: "Partizip II of A1 verbs",
        4: "Partizip II of A1 verbs",
        5: "Partizip II of A1 verbs",
        6: "Partizip II of A1 verbs",
        7: "Partizip II of A1 verbs",

        8: "Partizip II of irregular A2 verbs",
        9: "Partizip II of irregular A2 verbs",
        10: "Partizip II of A2 verbs",
        11: "Partizip II of A2 verbs",
        12: "Partizip II of A2 verbs",
        13: "Partizip II of A2 verbs",
        14: "Partizip II of A2 verbs",

        15: "Partizip II of irregular B1 verbs",
        16: "Partizip II of irregular B1 verbs",
        17: "Partizip II of irregular B1 verbs",
        18: "Partizip II of B1 verbs",
        19: "Partizip II of B1 verbs",
        20: "Partizip II of B1 verbs",
        21: "Partizip II of B1 verbs",
        22: "Partizip II of B1 verbs",
        23: "Partizip II of B1 verbs",
        24: "Partizip II of B1 verbs",
        25: "Partizip II of B1 verbs",
        26: "Partizip II of B1 verbs",
        27: "Partizip II of B1 verbs",

        28: "Partizip II of irregular B2 verbs",
        29: "Partizip II of irregular B2 verbs",
        30: "Partizip II of irregular B2 verbs",
        31: "Partizip II of B2 verbs",
        32: "Partizip II of B2 verbs",
        33: "Partizip II of B2 verbs",
        34: "Partizip II of B2 verbs",
        35: "Partizip II of B2 verbs",
        36: "Partizip II of B2 verbs",
        37: "Partizip II of B2 verbs",
        38: "Partizip II of B2 verbs",
        39: "Partizip II of B2 verbs",
        40: "Partizip II of B2 verbs",

        41: "Partizip II of irregular C1 verbs",
        42: "Partizip II of irregular C1 verbs",
        43: "Partizip II of irregular C1 verbs",
        44: "Partizip II of irregular C1 verbs",
        45: "Partizip II of irregular C1 verbs",
        46: "Partizip II of irregular C1 verbs",
        47: "Partizip II of C1 verbs",
        48: "Partizip II of C1 verbs",
        49: "Partizip II of C1 verbs",
        50: "Partizip II of C1 verbs",
        51: "Partizip II of C1 verbs",
        52: "Partizip II of C1 verbs",
        53: "Partizip II of C1 verbs",
        54: "Partizip II of C1 verbs",
        55: "Partizip II of C1 verbs",
        56: "Partizip II of C1 verbs",
        57: "Partizip II of C1 verbs",
        58: "Partizip II of C1 verbs",
        59: "Partizip II of C1 verbs",
        60: "Partizip II of C1 verbs",
        61: "Partizip II of C1 verbs",
        62: "Partizip II of C1 verbs",
        63: "Partizip II of C1 verbs",
        64: "Partizip II of C1 verbs",
        65: "Partizip II of C1 verbs",
        66: "Partizip II of C1 verbs",
    },

    praeteritum: {
        1: "Präteritum of the most important verbs",

        2: "Präteritum (3<sup>rd</sup> Person Singular) of irregular A1 verbs",
        3: "Präteritum (3<sup>rd</sup> Person Singular) of irregular A1 verbs",
        4: "Präteritum (3<sup>rd</sup> Person Singular) of A1 verbs",
        5: "Präteritum (3<sup>rd</sup> Person Singular) of A1 verbs",
        6: "Präteritum (3<sup>rd</sup> Person Singular) of A1 verbs",
        7: "Präteritum (3<sup>rd</sup> Person Singular) of A1 verbs",
        8: "Präteritum (3<sup>rd</sup> Person Singular) of A1 verbs",
        9: "Präteritum (3<sup>rd</sup> Person Singular) of irregular A2 verbs",
        10: "Präteritum (3<sup>rd</sup> Person Singular) of irregular A2 verbs",
        11: "Präteritum (3<sup>rd</sup> Person Singular) of A2 verbs",
        12: "Präteritum (3<sup>rd</sup> Person Singular) of A2 verbs",
        13: "Präteritum (3<sup>rd</sup> Person Singular) of A2 verbs",
        14: "Präteritum (3<sup>rd</sup> Person Singular) of A2 verbs",
        15: "Präteritum (3<sup>rd</sup> Person Singular) of A2 verbs",

        16: "Präteritum (3<sup>rd</sup> Person Singular) of irregular B1 verbs",
        17: "Präteritum (3<sup>rd</sup> Person Singular) of irregular B1 verbs",
        18: "Präteritum (3<sup>rd</sup> Person Singular) of irregular B1 verbs",
        19: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        20: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        21: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        22: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        23: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        24: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        25: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        26: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        27: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        28: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",

        29: "Präteritum (3<sup>rd</sup> Person Singular) of irregular B2 verbs",
        30: "Präteritum (3<sup>rd</sup> Person Singular) of irregular B2 verbs",
        31: "Präteritum (3<sup>rd</sup> Person Singular) of irregular B2 verbs",
        32: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        33: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        34: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        35: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        36: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        37: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        38: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        39: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        40: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        41: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",

        42: "Präteritum (3<sup>rd</sup> Person Singular) of irregular C1 verbs",
        43: "Präteritum (3<sup>rd</sup> Person Singular) of irregular C1 verbs",
        44: "Präteritum (3<sup>rd</sup> Person Singular) of irregular C1 verbs",
        45: "Präteritum (3<sup>rd</sup> Person Singular) of irregular C1 verbs",
        46: "Präteritum (3<sup>rd</sup> Person Singular) of irregular C1 verbs",
        47: "Präteritum (3<sup>rd</sup> Person Singular) of irregular C1 verbs",
        48: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        49: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        50: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        51: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        52: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        53: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        54: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        55: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        56: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        57: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        58: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        59: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        60: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        61: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        62: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        63: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        64: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        65: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        66: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
        67: "Präteritum (3<sup>rd</sup> Person Singular) of C1 verbs",
    },

    praeteritum_partizip_II: {
        1: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular A1 verbs",
        2: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular A1 verbs",
        3: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A1 verbs",
        4: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A1 verbs",
        5: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A1 verbs",
        6: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A1 verbs",
        7: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A1 verbs",
        8: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular A2 verbs",
        9: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular A2 verbs",
        10: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A2 verbs",
        11: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A2 verbs",
        12: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A2 verbs",
        13: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A2 verbs",
        14: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A2 verbs",

        15: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular B1 verbs",
        16: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular B1 verbs",
        17: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular B1 verbs",
        18: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        19: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        20: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        21: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        22: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        23: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        24: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        25: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        26: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        27: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",

        28: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular B2 verbs",
        29: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular B2 verbs",
        30: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular B2 verbs",
        31: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        32: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        33: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        34: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        35: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        36: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        37: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        38: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        39: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        40: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",

        41: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular C1 verbs",
        42: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular C1 verbs",
        43: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular C1 verbs",
        44: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular C1 verbs",
        45: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular C1 verbs",
        46: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of irregular C1 verbs",
        47: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        48: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        49: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        50: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        51: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        52: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        53: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        54: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        55: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        56: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        57: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        58: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        59: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        60: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        61: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        62: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        63: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        64: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        65: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
        66: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of C1 verbs",
    },

    imperativ: {
        1: "Imperative of A1 verbs",
        2: "Imperative of A1 verbs",
        3: "Imperative of A1 verbs",
        4: "Imperative of A1 verbs",
        5: "Imperative of A1 verbs",
        6: "Imperative of A1 verbs",

        7: "Imperative of A2 verbs",
        8: "Imperative of A2 verbs",
        9: "Imperative of A2 verbs",
        10: "Imperative of A2 verbs",
        11: "Imperative of A2 verbs",
        12: "Imperative of A2 verbs",
    },

    konjunktiv_II: {
        1: "Konjunktiv II of the most common verbs",
    },

    konjunktiv_I: {
        1: "Konjunktiv I of A1 verbs",
        2: "Konjunktiv I of A1 verbs",
        3: "Konjunktiv I of A1 verbs",
        4: "Konjunktiv I of A1 verbs",
        5: "Konjunktiv I of A1 verbs",
        6: "Konjunktiv I of A1 verbs",
    },

    partizip_I: {
        1: "Partizip I of A1 verbs",
        2: "Partizip I of A1 verbs",
        3: "Partizip I of A1 verbs",
        4: "Partizip I of A1 verbs",
        5: "Partizip I of A1 verbs",
    },

    genus_regeln: {
        1: "Definite Articles following level A1 rules, in isolation",
        2: "Definite Articles following level A1 rules, in isolation",
        3: "Definite Articles following level A1 rules, in isolation",
        4: "Definite Articles following level A1 rules, in isolation",
        5: "Definite Articles being exceptions to rules, in isolation",

        6: "Definite Articles following level A2 rules, in isolation",
        7: "Definite Articles following level A2 rules, in isolation",
        8: "Definite Articles following level A2 rules, in isolation",
        9: "Definite Articles following level A2 rules, in isolation",
        10: "Definite Articles being exceptions to rules, in isolation",

        11: "Definite Articles following level B1 rules, in isolation",
        12: "Definite Articles following level B1 rules, in isolation",
        13: "Definite Articles following level B1 rules, in isolation",
        14: "Definite Articles following level B1 rules, in isolation",
        15: "Definite Articles being exceptions to rules, in isolation",

        16: "Definite Articles following level B2 rules, in isolation",
        17: "Definite Articles following level B2 rules, in isolation",
        18: "Definite Articles following level B2 rules, in isolation",
        19: "Definite Articles following level B2 rules, in isolation",
        20: "Definite Articles being exceptions to rules, in isolation",

        21: "Definite Articles following level C1 rules, in isolation",
        22: "Definite Articles following level C1 rules, in isolation",
        23: "Definite Articles following level C1 rules, in isolation",
        24: "Definite Articles following level C1 rules, in isolation",
        25: "Definite Articles following level C1 rules, in isolation",
        26: "Definite Articles following level C1 rules, in isolation",
        27: "Definite Articles being exceptions to rules, in isolation",
    },

    genus_routledge: {
        1: "Definite Articles, in isolation",
        2: "Definite Articles, in isolation",
        3: "Definite Articles, in isolation",
        4: "Definite Articles, in isolation",
        5: "Definite Articles, in isolation",
        6: "Definite Articles, in isolation",
        7: "Definite Articles, in isolation",
        8: "Definite Articles, in isolation",
        9: "Definite Articles, in isolation",
        10: "Definite Articles, in isolation",
        11: "Definite Articles, in isolation",
        12: "Definite Articles, in isolation",
        13: "Definite Articles, in isolation",
        14: "Definite Articles, in isolation",
        15: "Definite Articles, in isolation",
        16: "Definite Articles, in isolation",
        17: "Definite Articles, in isolation",
        18: "Definite Articles, in isolation",
        19: "Definite Articles, in isolation",
        20: "Definite Articles, in isolation",
        21: "Definite Articles, in isolation",
        22: "Definite Articles, in isolation",
        23: "Definite Articles, in isolation",
        24: "Definite Articles, in isolation",
        25: "Definite Articles, in isolation",

        26: "Definite Articles, in isolation",
        27: "Definite Articles, in isolation",
        28: "Definite Articles, in isolation",
        29: "Definite Articles, in isolation",
        30: "Definite Articles, in isolation",
        31: "Definite Articles, in isolation",
        32: "Definite Articles, in isolation",
        33: "Definite Articles, in isolation",
        34: "Definite Articles, in isolation",
        35: "Definite Articles, in isolation",
        36: "Definite Articles, in isolation",
        37: "Definite Articles, in isolation",
        38: "Definite Articles, in isolation",
        39: "Definite Articles, in isolation",
        40: "Definite Articles, in isolation",
        41: "Definite Articles, in isolation",
        42: "Definite Articles, in isolation",
        43: "Definite Articles, in isolation",
        44: "Definite Articles, in isolation",
        45: "Definite Articles, in isolation",
        46: "Definite Articles, in isolation",
        47: "Definite Articles, in isolation",
        48: "Definite Articles, in isolation",
        49: "Definite Articles, in isolation",
        50: "Definite Articles, in isolation",

        51: "Definite Articles, in isolation",
        52: "Definite Articles, in isolation",
        53: "Definite Articles, in isolation",
        54: "Definite Articles, in isolation",
        55: "Definite Articles, in isolation",
        56: "Definite Articles, in isolation",
        57: "Definite Articles, in isolation",
        58: "Definite Articles, in isolation",
        59: "Definite Articles, in isolation",
        60: "Definite Articles, in isolation",
        61: "Definite Articles, in isolation",
        62: "Definite Articles, in isolation",
        63: "Definite Articles, in isolation",
        64: "Definite Articles, in isolation",
        65: "Definite Articles, in isolation",
        66: "Definite Articles, in isolation",
        67: "Definite Articles, in isolation",
        68: "Definite Articles, in isolation",
        69: "Definite Articles, in isolation",
        70: "Definite Articles, in isolation",
        71: "Definite Articles, in isolation",
        72: "Definite Articles, in isolation",
        73: "Definite Articles, in isolation",
        74: "Definite Articles, in isolation",
        75: "Definite Articles, in isolation",
        76: "Definite Articles, in isolation",
        77: "Definite Articles, in isolation",
        78: "Definite Articles, in isolation",
        79: "Definite Articles, in isolation",
        80: "Definite Articles, in isolation",
        81: "Definite Articles, in isolation",
        82: "Definite Articles, in isolation",
        83: "Definite Articles, in isolation",
        84: "Definite Articles, in isolation",
        85: "Definite Articles, in isolation",
        86: "Definite Articles, in isolation",
        87: "Definite Articles, in isolation",
        88: "Definite Articles, in isolation",
        89: "Definite Articles, in isolation",
    },

    genus_goethe: {
        1: "Definite Articles, in isolation",
        2: "Definite Articles, in isolation",
        3: "Definite Articles, in isolation",
        4: "Definite Articles, in isolation",
        5: "Definite Articles, in isolation",
        6: "Definite Articles, in isolation",
        7: "Definite Articles, in isolation",
        8: "Definite Articles, in isolation",
        9: "Definite Articles, in isolation",
        10: "Definite Articles, in isolation",
        11: "Definite Articles, in isolation",
        12: "Definite Articles, in isolation",
        13: "Definite Articles, in isolation",
        14: "Definite Articles, in isolation",
        15: "Definite Articles, in isolation",
        16: "Definite Articles, in isolation",
        17: "Definite Articles, in isolation",
        18: "Definite Articles, in isolation",
        19: "Definite Articles, in isolation",
        20: "Definite Articles, in isolation",

        21: "Definite Articles, in isolation",
        22: "Definite Articles, in isolation",
        23: "Definite Articles, in isolation",
        24: "Definite Articles, in isolation",
        25: "Definite Articles, in isolation",
        26: "Definite Articles, in isolation",
        27: "Definite Articles, in isolation",
        28: "Definite Articles, in isolation",
        29: "Definite Articles, in isolation",
        30: "Definite Articles, in isolation",
        31: "Definite Articles, in isolation",
        32: "Definite Articles, in isolation",
        33: "Definite Articles, in isolation",
        34: "Definite Articles, in isolation",
        35: "Definite Articles, in isolation",

        36: "Definite Articles, in isolation",
        37: "Definite Articles, in isolation",
        38: "Definite Articles, in isolation",
        39: "Definite Articles, in isolation",
        40: "Definite Articles, in isolation",
        41: "Definite Articles, in isolation",
        42: "Definite Articles, in isolation",
        43: "Definite Articles, in isolation",
        44: "Definite Articles, in isolation",
        45: "Definite Articles, in isolation",
        46: "Definite Articles, in isolation",
        47: "Definite Articles, in isolation",
        48: "Definite Articles, in isolation",
        49: "Definite Articles, in isolation",
        50: "Definite Articles, in isolation",
        51: "Definite Articles, in isolation",
        52: "Definite Articles, in isolation",
        53: "Definite Articles, in isolation",
        54: "Definite Articles, in isolation",
        55: "Definite Articles, in isolation",
        56: "Definite Articles, in isolation",
        57: "Definite Articles, in isolation",
        58: "Definite Articles, in isolation",
        59: "Definite Articles, in isolation",
        60: "Definite Articles, in isolation",
        61: "Definite Articles, in isolation",
        62: "Definite Articles, in isolation",
        63: "Definite Articles, in isolation",
        64: "Definite Articles, in isolation",
        65: "Definite Articles, in isolation",
        66: "Definite Articles, in isolation",
        67: "Definite Articles, in isolation",
        68: "Definite Articles, in isolation",
        69: "Definite Articles, in isolation",
        70: "Definite Articles, in isolation",
        71: "Definite Articles, in isolation",
        72: "Definite Articles, in isolation",
        73: "Definite Articles, in isolation",
        74: "Definite Articles, in isolation",
        75: "Definite Articles, in isolation",
        76: "Definite Articles, in isolation",
        77: "Definite Articles, in isolation",
        78: "Definite Articles, in isolation",
        79: "Definite Articles, in isolation",
        80: "Definite Articles, in isolation",
        81: "Definite Articles, in isolation",
        82: "Definite Articles, in isolation",
        83: "Definite Articles, in isolation",
        84: "Definite Articles, in isolation",
        85: "Definite Articles, in isolation",
        86: "Definite Articles, in isolation",
        87: "Definite Articles, in isolation",
    },

}
