from data.data_processing.units import (
    praepositionen_grammatik, praepositionen_verben, praepositionen_adjektive, praepositionen_nomen, praepositionen_kasus,
    artikel, pronomen, konnektoren, fragen, adverbien,
    praesens, imperativ, partizip_II, praeteritum, praeteritum_partizip_II, konjunktiv_II, konjunktiv_I, partizip_I,
    adjektive, adjektivdeklinationen,
    trennbare_verben, verben,
    deverbale_nomen
)

DESCRIPTION = {

    praepositionen_grammatik: {
        1: "Temporal Prepositions in sentences",
        2: "Local (Position) Prepositions in sentences",
        3: "Local (Direction) Prepositions in sentences",
        4: "Modal and Causal Prepositions in sentences",

        5: "A1 prepositions at A2 level in Temporal context in sentences",
        6: "A1 prepositions at A2 level in Local (Position) context in sentences",
        7: "A1 prepositions at A2 level in Local (Direction) context in sentences",

        8: "A1 Prepositions at B1 level in sentences",
        9: "A1 Prepositions at B1 level in sentences",
        10: "B1 Prepositions in isolation",
        11: "B1 Prepositions in sentences",

        12: "A1 Prepositions at B2 level in sentences",
        13: "A1 Prepositions at B2 level in sentences",
        14: "B2 Prepositions in isolation",
        15: "B2 Prepositions in sentences",

        16: "C1 prepositions in isolation",
        17: "C1 prepositions in sentences",
        18: "C1 prepositions in isolation",
        19: "C1 prepositions in sentences",
    },

    praepositionen_verben: {
        1: "A1 Verb-Preposition pairs in isolation",
        2: "A1 Verb-Preposition pairs in sentences",
        3: "A1 Verb-Preposition pairs in isolation",
        4: "A1 Verb-Preposition pairs in sentences",

        5: "A2 Verb-Preposition pairs in isolation",
        6: "A2 Verb-Preposition pairs in sentences",
        7: "A2 Verb-Preposition pairs in isolation",
        8: "A2 Verb-Preposition pairs in sentences",
        9: "Da-Words in sentences",
        10: "Wo-Words in sentences",

        11: "B1 Verb-Preposition pairs in isolation",
        12: "B1 Verb-Preposition pairs in sentences",
        13: "B1 Verb-Preposition pairs in isolation",
        14: "B1 Verb-Preposition pairs in sentences",
        15: "B1 Verb-Preposition pairs in isolation",
        16: "B1 Verb-Preposition pairs in sentences",
        17: "B1 Verb-Preposition pairs in isolation",
        18: "B1 Verb-Preposition pairs in sentences",

        19: "B2 Verb-Preposition pairs in isolation",
        20: "B2 Verb-Preposition pairs in sentences",
        21: "B2 Verb-Preposition pairs in isolation",
        22: "B2 Verb-Preposition pairs in sentences",
        23: "B2 Verb-Preposition pairs in isolation",
        24: "B2 Verb-Preposition pairs in sentences",
        25: "B2 Verb-Preposition pairs in isolation",
        26: "B2 Verb-Preposition pairs in sentences",

        27: "C1 Verb-Preposition pairs in isolation",
        28: "C1 Verb-Preposition pairs in sentences",
        29: "C1 Verb-Preposition pairs in isolation",
        30: "C1 Verb-Preposition pairs in sentences",
        31: "C1 Verb-Preposition pairs in isolation",
        32: "C1 Verb-Preposition pairs in sentences",
    },

    praepositionen_adjektive: {
        1: "Up to B1 Adjective-Preposition pairs in isolation",
        2: "Up to B1 Adjective-Preposition pairs in sentences",

        3: "B2 Adjective-Preposition pairs in isolation",
        4: "B2 Adjective-Preposition pairs in sentences",

        5: "C1 Adjective-Preposition pairs in isolation",
        6: "C1 Adjective-Preposition pairs in sentences",
    },

    praepositionen_nomen: {
        1: "Up to B1 Noun-Preposition pairs in isolation",
        2: "Up to B1 Noun-Preposition pairs in sentences",
        3: "Up to B1 Noun-Preposition pairs in isolation",
        4: "Up to B1 Noun-Preposition pairs in sentences",

        5: "B2 Noun-Preposition pairs in isolation",
        6: "B2 Noun-Preposition pairs in sentences",
        7: "B2 Noun-Preposition pairs in isolation",
        8: "B2 Noun-Preposition pairs in sentences",
        9: "B2 Noun-Preposition pairs in isolation",
        10: "B2 Noun-Preposition pairs in sentences",

        11: "C1 Noun-Preposition pairs in isolation",
        12: "C1 Noun-Preposition pairs in sentences",
        13: "C1 Noun-Preposition pairs in isolation",
        14: "C1 Noun-Preposition pairs in sentences",
        15: "C1 Noun-Preposition pairs in isolation",
        16: "C1 Noun-Preposition pairs in sentences",
    },

    praepositionen_kasus: {
        1: "Articles and Pronouns from Präpositionen in sentences",
        2: "Articles and Pronouns from Präpositionen in sentences",
        3: "Articles and Pronouns from Präpositionen in sentences",
        4: "Articles and Pronouns from Präpositionen – Verben in sentences",
        5: "Articles and Pronouns from Präpositionen – Verben in sentences",
        6: "Articles and Pronouns from Präpositionen in sentences",
        7: "Articles and Pronouns from Präpositionen in sentences",
        8: "Articles and Pronouns from Präpositionen – Verben in sentences",
        9: "Articles and Pronouns from Präpositionen – Verben in sentences",
    },

    artikel: {
        1: "Definite articles <i>Der Die Das</i> in isolation",
        2: "Definite articles in the Nominative case in sentences",
        3: "Definite articles in the Accusative case in sentences",
        4: "Definite articles in the Dative case in sentences",
        5: "Definite Feminine articles in sentences",
        6: "Definite Masculine articles in sentences",
        7: "Definite Neuter articles in sentences",
        8: "Definite Plural articles in sentences",
        9: "Mix of Definite articles in the Nominative, Accusative and Dative cases in sentences",
        10: "Mix of Definite articles in the Nominative, Accusative and Dative cases in sentences",
        11: "Indefinite articles <i>Ein</i> in isolation",
        12: "Indefinite articles in the Nominative case in sentences",
        13: "Indefinite articles in the Accusative case in sentences",
        14: "Indefinite articles in the Dative case in sentences",
        15: "Indefinite Feminine articles in the Nominative case in sentences",
        16: "Indefinite Masculine articles in the Accusative case in sentences",
        17: "Indefinite Neuter articles in the Dative case in sentences",
        18: "Mix of Indefinite articles in the Nominative, Accusative and Dative cases in sentences",
        19: "Mix of Indefinite articles in the Nominative, Accusative and Dative cases in sentences",
        20: "Negative articles <i>Kein</i> in isolation",
        21: "Negative articles <i>Kein</i> in sentences",
        22: "Possessive articles linked to Singular pronouns (Ich, Du, Er, Sie, Es) in isolation",
        23: "Possessive articles linked to Singular pronouns (Ich, Du, Er, Sie, Es) in sentences",
        24: "Possessive articles linked to Plural (Wir, Ihr, Sie) and Formal pronouns in isolation",
        25: "Possessive articles linked to Plural (Wir, Ihr, Sie) and Formal pronouns in sentences",

        26: "Demonstrative articles <em>Diese</em> in isolation",
        27: "Demonstrative articles <em>Diese</em> in sentences",
        28: "Articles <em>Jede</em> in isolation",
        29: "Articles <em>Jede</em> in sentences",
        30: "Definite articles with prepositions in the Accusative and Dative cases in sentences",
        31: "Definite articles with prepositions in the Accusative and Dative cases in sentences",
        32: "A2 articles in isolation",
        33: "A2 articles in sentences",

        34: "Definite, Indefinite and Negative articles in the Genitive case in isolation",
        35: "Definite, Indefinite and Negative articles in the Genitive case in sentences",
        36: "<em>Diese</em> and <em>Jede</em> in the Genitive case in isolation",
        37: "<em>Diese</em> and <em>Jede</em> in the Genitive case in sentences",
        38: "Possessive articles in the Genitive case in isolation",
        39: "Possessive articles in the Genitive case in sentences",

        40: "<em>Jene</em>, <em>Eine der</em> and <em>Irgendeine</em> articles in isolation",
        41: "<em>Jene</em>, <em>Eine der</em> and <em>Irgendeine</em> articles in sentences",

        42: "<em>Diejenige</em> and <em>Dieselbe</em> articles in isolation",
        43: "<em>Diejenige</em> and <em>Dieselbe</em> articles in sentences",
    },

    pronomen: {
        1: "Nominative, Accusative and Dative Pronouns in isolation",
        2: "Nominative Pronouns in sentences",
        3: "Accusative Pronouns in sentences",
        4: "Dative Pronouns in sentences",
        5: "Mix of Accusative and Dative Pronouns in sentences",
        6: "Mix of Accusative and Dative Pronouns in sentences",

        7: "Reflexive Pronouns in isolation",
        8: "Reflexive Pronouns in sentences",
        9: "Mix of Accusative, Dative, and Reflexive Pronouns in sentences",
        10: "Mix of Accusative, Dative, and Reflexive Pronouns in sentences",
        11: "Possessive Pronouns linked to Singular pronouns (Ich, Du, Er, Sie, Es) in isolation",
        12: "Possessive Pronouns linked to Singular pronouns (Ich, Du, Er, Sie, Es) in sentences",
        13: "Possessive Pronouns linked to Plural (Wir, Ihr, Sie) and Formal pronouns in isolation",
        14: "Possessive Pronouns linked to Plural (Wir, Ihr, Sie) and Formal pronouns in sentences",

        15: "B1 Pronouns <em>Nichts</em>, <em>Man</em>, <em>Jemand</em> etc. in isolation",
        16: "B1 Pronouns <em>Nichts</em>, <em>Man</em>, <em>Jemand</em> etc. in sentences",
        17: "Relative Nominative Pronouns in sentences",
        18: "Relative Accusative Pronouns in sentences",
        19: "Relative Dative Pronouns in sentences",
        20: "Relative Genitive Pronouns in sentences",
        21: "Mix of Relative Pronouns in sentences",
        22: "Mix of Relative Pronouns in sentences",

        23: "Mix of Relative Pronouns in sentences",
        24: "Mix of Relative Pronouns in sentences",
        25: "Relative Pronouns for locations and directions in sentences",
    },

    konnektoren: {
        1: "A1 Connectors in isolation",
        2: "A1 Connectors in sentences",

        3: "A2 Connectors in isolation",
        4: "A2 Connectors in sentences",

        5: "B1 Connectors in isolation",
        6: "B1 Connectors in sentences",
        7: "Synonyms of Connectors at B1 level",

        8: "B2 Connectors in isolation",
        9: "B2 Connectors in sentences",
        10: "B2 Connectors in isolation",
        11: "B2 Connectors in sentences",
        12: "Synonyms of Connectors at B2 level",

        13: "C1 Connectors in isolation",
        14: "C1 Connectors in sentences",
        15: "Synonyms of Connectors at C1 level",
    },

    fragen: {
        1: 'A1 Question Words in isolation',
        2: 'A1 Question Words in sentences',

        3: 'A2 Question Words in isolation',
        4: 'A2 Question Words in sentences',

        5: 'B1 Question Words in isolation',
        6: 'B1 Question Words in sentences',

        7: 'B2 Question Words in isolation',
        8: 'B2 Question Words in sentences',
        9: 'B2 Question Words in isolation (Welch-Party)',
        10: 'B2 Question Words in sentences (Welch-Party)',

        11: 'C1 Question Words in isolation',
        12: 'C1 Question Words in sentences',
    },

    adverbien: {
        1: "A1 Adverbs in isolation",
        2: "A1 Adverbs in sentences",
        3: "A1 Adverbs in isolation",
        4: "A1 Adverbs in sentences",

        5: "A2 Adverbs in isolation",
        6: "A2 Adverbs in sentences",
        7: "A2 Adverbs in isolation",
        8: "A2 Adverbs in sentences",
        9: "A2 Adverbs in isolation",
        10: "A2 Adverbs in sentences",

        11: "B1 Adverbs in isolation",
        12: "B1 Adverbs in sentences",
        13: "B1 Adverbs in isolation",
        14: "B1 Adverbs in sentences",
        15: "B1 Adverbs in isolation",
        16: "B1 Adverbs in sentences",
        17: "B1 Adverbs in isolation",
        18: "B1 Adverbs in sentences",

        19: "B2 Adverbs in isolation",
        20: "B2 Adverbs in sentences",
        21: "B2 Adverbs in isolation",
        22: "B2 Adverbs in sentences",
        23: "B2 Adverbs in isolation",
        24: "B2 Adverbs in sentences",
        25: "B2 Adverbs in isolation",
        26: "B2 Adverbs in sentences",
        27: "B2 Adverbs in isolation",
        28: "B2 Adverbs in sentences",

        29: "C1 Adverbs in isolation",
        30: "C1 Adverbs in sentences",
        31: "C1 Adverbs in isolation",
        32: "C1 Adverbs in sentences",
        33: "Her and Hin Adverbs in isolation",
        34: "Her and Hin Adverbs in sentences",
        35: "C1 Adverbs in isolation",
        36: "C1 Adverbs in sentences",
        37: "C1 Adverbs in isolation",
        38: "C1 Adverbs in sentences",
        39: "C1 Adverbs in isolation",
        40: "C1 Adverbs in sentences",
        41: "C1 Adverbs in isolation",
        42: "C1 Adverbs in sentences",
        43: "C1 Adverbs in isolation",
        44: "C1 Adverbs in sentences",
    },

    praesens: {
        1: "Present tense of A1 verbs in isolation",
        2: "Present tense of A1 verbs in isolation",
        3: "Present tense of A1 verbs in isolation",
        4: "Present tense of A1 verbs in isolation",
        5: "Present tense of A1 verbs in isolation",
        6: "Present tense of A1 verbs in isolation",
        7: "Present tense of A1 verbs in isolation",
        8: "Present tense of A1 verbs in isolation",
        9: "Present tense of A1 verbs in isolation",
        10: "Present tense of A1 verbs in isolation",
        11: "Present tense of A1 verbs in isolation",
        12: "Present tense of A1 verbs in isolation",
        13: "Present tense of A1 verbs in isolation",
        14: "Present tense of A1 verbs in isolation",
        15: "Present tense of A1 verbs in isolation",
        16: "Present tense of A1 verbs in isolation",
        17: "Present tense of A1 verbs in isolation",
        18: "Present tense of A1 verbs in isolation",
        19: "Present tense of A1 verbs in isolation",
        20: "Present tense of A1 verbs in isolation",

        21: "Present tense of A2 verbs in isolation",
        22: "Present tense of A2 verbs in isolation",
        23: "Present tense of A2 verbs in isolation",
        24: "Present tense of A2 verbs in isolation",
        25: "Present tense of A2 verbs in isolation",
        26: "Present tense of A2 verbs in isolation",
        27: "Present tense of A2 verbs in isolation",
        28: "Present tense of A2 verbs in isolation",
        29: "Present tense of A2 verbs in isolation",
        30: "Present tense of A2 verbs in isolation",
        31: "Present tense of A2 verbs in isolation",
        32: "Present tense of A2 verbs in isolation",
        33: "Present tense of A2 verbs in isolation",
        34: "Present tense of A2 verbs in isolation",
        35: "Present tense of A2 verbs in isolation",
        36: "Present tense of A2 verbs in isolation",
        37: "Present tense of A2 verbs in isolation",
        38: "Present tense of A2 verbs in isolation",
        39: "Present tense of A2 verbs in isolation",
        40: "Present tense of A2 verbs in isolation",
    },

    partizip_II: {
        1: "Partizip II of A1 verbs",
        2: "Partizip II of A1 verbs",
        3: "Partizip II of A1 verbs",
        4: "Partizip II of A1 verbs",
        5: "Partizip II of A1 verbs",

        6: "Partizip II of A2 verbs",
        7: "Partizip II of A2 verbs",
        8: "Partizip II of A2 verbs",
        9: "Partizip II of A2 verbs",
        10: "Partizip II of A2 verbs",

        11: "Partizip II of B1 verbs",
        12: "Partizip II of B1 verbs",
        13: "Partizip II of B1 verbs",
        14: "Partizip II of B1 verbs",
        15: "Partizip II of B1 verbs",
        16: "Partizip II of B1 verbs",
        17: "Partizip II of B1 verbs",
        18: "Partizip II of B1 verbs",
        19: "Partizip II of B1 verbs",
        20: "Partizip II of B1 verbs",

        21: "Partizip II of B2 verbs",
        22: "Partizip II of B2 verbs",
        23: "Partizip II of B2 verbs",
        24: "Partizip II of B2 verbs",
        25: "Partizip II of B2 verbs",
        26: "Partizip II of B2 verbs",
        27: "Partizip II of B2 verbs",
        28: "Partizip II of B2 verbs",
        29: "Partizip II of B2 verbs",
        30: "Partizip II of B2 verbs",
    },

    praeteritum: {
        1: "Präteritum of the most important verbs",

        2: "Präteritum (3<sup>rd</sup> Person Singular) of A1 verbs",
        3: "Präteritum (3<sup>rd</sup> Person Singular) of A1 verbs",
        4: "Präteritum (3<sup>rd</sup> Person Singular) of A1 verbs",
        5: "Präteritum (3<sup>rd</sup> Person Singular) of A1 verbs",
        6: "Präteritum (3<sup>rd</sup> Person Singular) of A1 verbs",
        7: "Präteritum (3<sup>rd</sup> Person Singular) of A2 verbs",
        8: "Präteritum (3<sup>rd</sup> Person Singular) of A2 verbs",
        9: "Präteritum (3<sup>rd</sup> Person Singular) of A2 verbs",
        10: "Präteritum (3<sup>rd</sup> Person Singular) of A2 verbs",
        11: "Präteritum (3<sup>rd</sup> Person Singular) of A2 verbs",

        12: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        13: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        14: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        15: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        16: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        17: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        18: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        19: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        20: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",
        21: "Präteritum (3<sup>rd</sup> Person Singular) of B1 verbs",

        22: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        23: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        24: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        25: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        26: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        27: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        28: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        29: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        30: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
        31: "Präteritum (3<sup>rd</sup> Person Singular) of B2 verbs",
    },

    praeteritum_partizip_II: {
        1: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of the most important verbs",

        2: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A1 verbs",
        3: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A1 verbs",
        4: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A1 verbs",
        5: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A1 verbs",
        6: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A1 verbs",
        7: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A2 verbs",
        8: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A2 verbs",
        9: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A2 verbs",
        10: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A2 verbs",
        11: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of A2 verbs",

        12: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        13: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        14: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        15: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        16: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        17: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        18: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        19: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        20: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",
        21: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B1 verbs",

        22: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        23: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        24: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        25: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        26: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        27: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        28: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        29: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        30: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
        31: "Präteritum (3<sup>rd</sup> Person Singular) and Partizip II of B2 verbs",
    },

    imperativ: {
        1: "Imperative of A1 verbs",
        2: "Imperative of A1 verbs",
        3: "Imperative of A1 verbs",
        4: "Imperative of A1 verbs",
        5: "Imperative of A1 verbs",
        6: "Imperative of A1 verbs",

        7: "Imperative of A2 verbs",
        8: "Imperative of A2 verbs",
        9: "Imperative of A2 verbs",
        10: "Imperative of A2 verbs",
        11: "Imperative of A2 verbs",
        12: "Imperative of A2 verbs",
    },

    konjunktiv_II: {
        1: "Konjunktiv II of the most common verbs",
    },

    konjunktiv_I: {
        1: "Konjunktiv I of A1 verbs",
        2: "Konjunktiv I of A1 verbs",
        3: "Konjunktiv I of A1 verbs",
        4: "Konjunktiv I of A1 verbs",
        5: "Konjunktiv I of A1 verbs",
        6: "Konjunktiv I of A1 verbs",
    },

    partizip_I: {
        1: "Partizip I of A1 verbs",
        2: "Partizip I of A1 verbs",
        3: "Partizip I of A1 verbs",
        4: "Partizip I of A1 verbs",
        5: "Partizip I of A1 verbs",
    },

    adjektive: {
        1: "A1 Adjectives in isolation",
        2: "A1 Adjectives in isolation",
        3: "Opposites of A1 Adjectives in isolation",
        4: "A1 Comparatives in isolation",
        5: "A1 Comparatives in isolation",
        6: "Comparative Conjunctions in sentences",
        7: "A1 Superlatives in isolation",
        8: "A1 Superlatives in isolation",
    },

    adjektivdeklinationen: {
        1: "Nominative Adjective Declensions in isolation",
        2: "Nominative Adjective Declensions in sentences",
        3: "Accusative Adjective Declensions in isolation",
        4: "Accusative Adjective Declensions in sentences",
        5: "Dative Adjective Declensions in isolation",
        6: "Dative Adjective Declensions in sentences",
        7: "Definite Articles' Adjective Declensions in sentences",
        8: "Indefinite Articles' Adjective Declensions in sentences",
        9: "No Article's Adjective Declensions in sentences",
        10: "Mix of Nominative, Accusative, and Dative Adjective Declensions in sentences",
        11: "Mix of Nominative, Accusative, and Dative Adjective Declensions in sentences",
        12: "Mix of Nominative, Accusative, and Dative Adjective Declensions in sentences",

        13: "Genitive Adjective Declensions in isolation",
        14: "Genitive Adjective Declensions in sentences",
        15: "Negative Adjective Declensions in isolation",
        16: "Negative Adjective Declensions in sentences",

        17: "Possessive Adjective Declensions in isolation",
        18: "Possessive Adjective Declensions in sentences",
        19: "Demonstrative Adjective Declensions in isolation",
        20: "Demonstrative Adjective Declensions in sentences",

        21: "Adjective Declensions of Singular Articles \"etwas\", \"viel\", \"mehr\" in isolation",
        22: "Adjective Declensions of Singular Articles \"etwas\", \"viel\", \"mehr\" in sentences",
        23: "Adjective Declensions of Plural Articles \"alle\", \"viele\" in isolation",
        24: "Adjective Declensions of Plural Articles \"alle\", \"viele\" in sentences",
    },

    trennbare_verben: {
        1: "A1 (un)trennbare Verbs with root help",
        2: "A1 (un)trennbare Verbs with prefix help",
        3: "A1 (un)trennbare Verbs with no help",

        4: "A2 (un)trennbare Verbs with root help",
        5: "A2 (un)trennbare Verbs with prefix help",
        6: "A2 (un)trennbare Verbs with no help",

        7: "B1 (un)trennbare Verbs with root help",
        8: "B1 (un)trennbare Verbs with root help",
        9: "B1 (un)trennbare Verbs with root help",
        10: "B1 (un)trennbare Verbs with root help",
        11: "B1 (un)trennbare Verbs with prefix help",
        12: "B1 (un)trennbare Verbs with prefix help",
        13: "B1 (un)trennbare Verbs with prefix help",
        14: "B1 (un)trennbare Verbs with prefix help",
        15: "B1 (un)trennbare Verbs with no help",
        16: "B1 (un)trennbare Verbs with no help",
        17: "B1 (un)trennbare Verbs with no help",
        18: "B1 (un)trennbare Verbs with no help",

        19: "B2 (un)trennbare Verbs with root help",
        20: "B2 (un)trennbare Verbs with root help",
        21: "B2 (un)trennbare Verbs with root help",
        22: "B2 (un)trennbare Verbs with root help",
        23: "B2 (un)trennbare Verbs with prefix help",
        24: "B2 (un)trennbare Verbs with prefix help",
        25: "B2 (un)trennbare Verbs with prefix help",
        26: "B2 (un)trennbare Verbs with prefix help",
        27: "B2 (un)trennbare Verbs with no help",
        28: "B2 (un)trennbare Verbs with no help",
        29: "B2 (un)trennbare Verbs with no help",
        30: "B2 (un)trennbare Verbs with no help",
    },

    verben: {
        1: "A1 Verbs",
        2: "A1 Verbs",
        3: "A1 Verbs",
        4: "A1 Verbs",
        5: "A1 Verbs",

        6: "A2 Verbs",
        7: "A2 Verbs",
        8: "A2 Verbs",
        9: "A2 Verbs",
        10: "A2 Verbs",

        11: "B1 Verbs",
        12: "B1 Verbs",
        13: "B1 Verbs",
        14: "B1 Verbs",
        15: "B1 Verbs",
        16: "B1 Verbs",
        17: "B1 Verbs",
        18: "B1 Verbs",
        19: "B1 Verbs",
        20: "B1 Verbs",

        21: "B2 Verbs",
        22: "B2 Verbs",
        23: "B2 Verbs",
        24: "B2 Verbs",
        25: "B2 Verbs",
        26: "B2 Verbs",
        27: "B2 Verbs",
        28: "B2 Verbs",
        29: "B2 Verbs",
        30: "B2 Verbs",
    },

    deverbale_nomen: {
        1: "Main Deverbal Nouns (nouns derived verbs)",
        2: "Main Deverbal Nouns (nouns derived verbs)",
        3: "Deverbal Nouns derived from A1 Verbs",
        4: "Deverbal Nouns derived from A1 Verbs",
        5: "Deverbal Nouns derived from A2 Verbs",
        6: "Deverbal Nouns derived from A2 Verbs",
        7: "Deverbal Nouns derived from B1 Verbs",
        8: "Deverbal Nouns derived from B1 Verbs",
        9: "Deverbal Nouns derived from B1 Verbs",
        10: "Deverbal Nouns derived from B2 Verbs",
        11: "Deverbal Nouns derived from B2 Verbs",
        12: "Deverbal Nouns derived from B2 Verbs",
        13: "Deverbal Nouns derived from C1 Verbs",
        14: "Deverbal Nouns derived from C1 Verbs",
        15: "Deverbal Nouns derived from C1 Verbs",
        16: "Deverbal Nouns derived from C1 Verbs",
    },

}
