from data.data_processing.exercises import prompt
from data.data_processing.units import (
    praepositionen, praepositionen_verben, praepositionen_adjektive, praepositionen_nomen, pronominaladverbien,
    artikel, pronomen, praepositionen_artikel, verben_artikel,
    konnektoren, fragen, adverbien, wortstellung,
    genus_regeln, genus, plural,
    adjektive, komparativ_superlativ, adjektivdeklinationen, adjektive_konjunktionen,
    verben, trennbare_verben, nomen_verben_verbindungen,
    praesens, imperativ, partizip_II, praeteritum, konjunktiv_II, konjunktiv_I, partizip_I,
    nomen_verben_wortstaemme, adjektive_verben_wortstaemme, adjektive_nomen_wortstaemme,
    zahlen, alpha,
)

information_prompt = (
    "Feedback for this exercise is generated by a large language model (LLM). LLMs can make mistakes,"
    " including incorrectly grading an answer or providing inaccurate feedback. Please verify any important information."
    "\n\nDo not provide personal information such as your name, date of birth, precise address, or ID number."
)

INFORMATION_UNIT_EN = {

}

INFORMATION_EXERCISE_EN = {
    praepositionen: {
        33: "Postpositions are prepositions that are placed after their noun or pronoun complement.",
        34: "Postpositions are prepositions that are placed after their noun or pronoun complement.",
    }
}

INFORMATION_SUBCATEGORY_EN = {

}

INFORMATION_CATEGORY_EN = {
    alpha: {
        prompt: information_prompt
    },

    konnektoren: {
        prompt: information_prompt
    },

    fragen: {
        prompt: information_prompt
    },

    adverbien: {
        prompt: information_prompt
    },
}