from data_processing.exercises import (artikel, pronomen, konnektoren, praepositionen_grammatik, adjektivdeklinationen,
                                       praesens, praepositionen_konjugation, imperativ, perfekt, praeteritum, konjunktiv,
                                       partizip_I,
                                       adverbien, verben, trennbare_verben, adjektive, deverbale_substantive)

DESCRIPTION_TEMPLATES = {
artikel: {
        1: "Accusative and Dative Definite Articles with prepositions in sentences",
        2: "Simple (A2) Articles in isolation",
        3: "Simple (A2) Articles in sentences",
        4: "Common (B2) Articles in isolation",
        5: "Common (B2) Articles in sentences",
    },

    pronomen: {
        1: "Nominative Pronouns in sentences",
        2: "Accusative Pronouns in sentences",
        3: "Dative Pronouns in sentences",
        4: "Accusative and Dative Pronouns in sentences",
        5: "Reflexive Pronouns in sentences",
        6: "Accusative, Dative, and Reflexive Pronouns in sentences",
        7: "Familiar (B1) Pronouns in isolation",
        8: "Familiar (B1) Pronouns in sentences",
        9: "Relative Nominative Pronouns in sentences",
        10: "Relative Accusative Pronouns in sentences",
        11: "Relative Dative Pronouns in sentences",
        12: "Relative Genitive Pronouns in sentences",
        13: "Relative Pronouns in sentences",
        14: "Relative Pronouns in sentences",
    },

    konnektoren: {
        1: "Basic (A1) Connectors in isolation",
        2: "Basic (A1) Connectors in sentences",
        3: "Simple (A2) Connectors in isolation",
        4: "Simple (A2) Connectors in sentences",
        5: "Familiar (B1) Connectors in isolation",
        6: "Familiar (B1) Connectors in sentences",
        7: "Common (B2) Connectors in isolation",
        8: "Common (B2) Connectors in sentences",
    },

    praepositionen_grammatik: {
        1: "Basic (A1) Prepositions in isolation",
        2: "Temporal Prepositions in sentences",
        3: "Local (Place) Prepositions in sentences",
        4: "Local (Direction) Prepositions in sentences",
        5: "Modal and Causal Prepositions in sentences",
        6: "Comparative Prepositions in sentences",
        7: "Review of Basic (A1) prepositions in sentences",
        8: "Review of Basic (A1) prepositions in sentences",
        9: "Familiar (B1) prepositions in isolation",
        10: "Familiar (B1) prepositions in sentences",
        11: "Common (B2) prepositions in isolation",
        12: "Common (B2) prepositions in sentences",
        13: "Durch vs. Von in sentences",
        14: "Aus vs. Vor in sentences",
        15: "Zu vs. Für in sentences",
        16: "Prevalent (C1) prepositions in isolation",
        17: "Prevalent (C1) prepositions in sentences",
    },

    adjektivdeklinationen: {
        1: "Nominative, Accusative, and Dative Adjective Declinations in isolation",
        2: "Nominative Adjective Declinations in sentences",
        3: "Accusative Adjective Declinations in sentences",
        4: "Dative Adjective Declinations in sentences",
        5: "Definite Articles' Adjective Declinations in sentences",
        6: "Indefinite Articles' Adjective Declinations in sentences",
        7: "No Article's Adjective Declinations in sentences",
        8: "Nominative, Accusative, and Dative Adjective Declinations in sentences",
        9: "Genitive, Possessive, Negative, and Demonstrative Adjective Declinations in isolation",
        10: "Genitive Adjective Declinations in sentences",
        11: "Possessive Articles' Adjective Declinations in sentences",
        12: "Demonstrative Articles' Adjective Declinations in sentences",
        13: "Negative Articles' Adjective Declinations in sentences",
        14: "Genitive, Possessive, Negative, and Demonstrative Adjective Declinations in sentences",
        15: "Neutral and Plural Article's Adjective Declinations in isolation",
        16: "Neutral and Plural Article's Adjective Declinations in sentences",
    },

    praesens: {
        1: "Present tense of A1 verbs in isolation",
        2: "Present tense of A1 verbs in isolation",
        3: "Present tense of A1 verbs in isolation",
        4: "Present tense of A1 verbs in isolation",
        5: "Present tense of A1 verbs in isolation",
        6: "Present tense of A1 verbs in isolation",
        7: "Present tense of A1 verbs in isolation",
        8: "Present tense of A1 verbs in isolation",
        9: "Present tense of A1 verbs in isolation",
        10: "Present tense of A1 verbs in isolation",
        11: "Present tense of A1 verbs in isolation",
        12: "Present tense of A1 verbs in isolation",
        13: "Present tense of A2 verbs in isolation",
        14: "Present tense of A2 verbs in isolation",
        15: "Present tense of A2 verbs in isolation",
        16: "Present tense of A2 verbs in isolation",
        17: "Present tense of A2 verbs in isolation",
        18: "Present tense of A2 verbs in isolation",
        19: "Present tense of A2 verbs in isolation",
        20: "Present tense of A2 verbs in isolation",
        21: "Present tense of A2 verbs in isolation",
        22: "Present tense of A2 verbs in isolation",
        23: "Present tense of A2 verbs in isolation",
        24: "Present tense of A2 verbs in isolation",
    },

    praepositionen_konjugation: {
        1: "A1 Verb-Preposition pairs in isolation",
        2: "A1 Verb-Preposition pairs in sentences",
        3: "A1 Verb-Preposition pairs in isolation",
        4: "A1 Verb-Preposition pairs in sentences",
        5: "A2 Verb-Preposition pairs in isolation",
        6: "A2 Verb-Preposition pairs in sentences",
        7: "A2 Verb-Preposition pairs in isolation",
        8: "A2 Verb-Preposition pairs in sentences",
        9: "B1 Verb-Preposition pairs in isolation",
        10: "B1 Verb-Preposition pairs in sentences",
        11: "B1 Verb-Preposition pairs in isolation",
        12: "B1 Verb-Preposition pairs in sentences",
        13: "Da-Words in sentences",
        14: "Da-Words in sentences",
        15: "Wo-Words in sentences",
        16: "B2 Verb-Preposition pairs in isolation",
        17: "B2 Verb-Preposition pairs in sentences",
        18: "Up to B2 Noun-Preposition pairs in isolation",
        19: "Up to B2 Noun-Preposition pairs in sentences",
        20: "Up to B2 Noun-Preposition pairs in isolation",
        21: "Up to B2 Noun-Preposition pairs in sentences",
        22: "Up to B2 Noun-Preposition pairs in isolation",
        23: "Up to B2 Noun-Preposition pairs in sentences",
        24: "Up to B2 Adjective-Preposition pairs in isolation",
        25: "Up to B2 Adjective-Preposition pairs in sentences",
        26: "C1 Verb-Preposition pairs in isolation",
        27: "C1 Verb-Preposition pairs in sentences",
        28: "C1 Verb-Preposition pairs in isolation",
        29: "C1 Verb-Preposition pairs in sentences",
        30: "C1 Noun-Preposition pairs in isolation",
        31: "C1 Noun-Preposition pairs in sentences",
        32: "C1 Noun-Preposition pairs in isolation",
        33: "C1 Noun-Preposition pairs in sentences",
        34: "C1 Adjective-Preposition pairs in isolation",
        35: "C1 Adjective-Preposition pairs in sentences",
    },

    perfekt: {
        1: "Partizip II of A1 verbs",
        2: "Partizip II of A1 verbs",
        3: "Partizip II of A1 verbs",
        4: "Partizip II of A2 verbs",
        5: "Partizip II of A2 verbs",
        6: "Partizip II of A2 verbs",
        7: "Partizip II of B1 verbs",
        8: "Partizip II of B1 verbs",
        9: "Partizip II of B1 verbs",
        10: "Partizip II of B1 verbs",
        11: "Partizip II of B1 verbs",
        12: "Partizip II of B2 verbs",
        13: "Partizip II of B2 verbs",
        14: "Partizip II of B2 verbs",
        15: "Partizip II of B2 verbs",
        16: "Partizip II of B2 verbs",
    },

    praeteritum: {
        1: "Präteritum of the most common verbs",
        2: "Präteritum (3rd. Per. Singular) of A1 verbs",
        3: "Präteritum (3rd. Per. Singular) of A1 verbs",
        4: "Präteritum (3rd. Per. Singular) of A1 verbs",
        5: "Präteritum (3rd. Per. Singular) of A2 verbs",
        6: "Präteritum (3rd. Per. Singular) of A2 verbs",
        7: "Präteritum (3rd. Per. Singular) of A2 verbs",
        8: "Präteritum (3rd. Per. Singular) of B1 verbs",
        9: "Präteritum (3rd. Per. Singular) of B1 verbs",
        10: "Präteritum (3rd. Per. Singular) of B1 verbs",
        11: "Präteritum (3rd. Per. Singular) of B1 verbs",
        12: "Präteritum (3rd. Per. Singular) of B1 verbs",
        13: "Präteritum (3rd. Per. Singular) of B2 verbs",
        14: "Präteritum (3rd. Per. Singular) of B2 verbs",
        15: "Präteritum (3rd. Per. Singular) of B2 verbs",
        16: "Präteritum (3rd. Per. Singular) of B2 verbs",
        17: "Präteritum (3rd. Per. Singular) of B2 verbs",
    },

    imperativ: {
        1: "Imperative of A1 verbs",
        2: "Imperative of A1 verbs",
        3: "Imperative of A1 verbs",
        4: "Imperative of A2 verbs",
        5: "Imperative of A2 verbs",
        6: "Imperative of A2 verbs",
    },

    konjunktiv: {
        1: "Konjunktiv II of the most common verbs",
    },

    partizip_I: {
        1: "Partizip I of A1 verbs",
        2: "Partizip I of A1 verbs",
        3: "Partizip I of A1 verbs",
    },

    adverbien: {
        1: "Basic (A1) Adverbs in isolation",
        2: "Basic (A1) Adverbs in sentences",
        3: "Simple (A2) Adverbs in isolation",
        4: "Simple (A2) Adverbs in sentences",
        5: "Familiar (B1) Adverbs in isolation",
        6: "Familiar (B1) Adverbs in sentences",
        7: "Familiar (B1) Adverbs in isolation",
        8: "Familiar (B1) Adverbs in sentences",
        9: "Common (B2) Adverbs in isolation",
        10: "Common (B2) Adverbs in sentences",
        11: "Common (B2) Adverbs in isolation",
        12: "Common (B2) Adverbs in sentences",
        13: "Her and Hin Adverbs in isolation",
        14: "Her and Hin Adverbs in sentences",
    },

    verben: {
        1: "A1 Verbs",
        2: "A1 Verbs",
        3: "A1 Verbs",
        4: "A2 Verbs",
        5: "A2 Verbs",
        6: "A2 Verbs",
        7: "B1 Verbs",
        8: "B1 Verbs",
        9: "B1 Verbs",
        10: "B1 Verbs",
        11: "B1 Verbs",
        12: "B2 Verbs",
        13: "B2 Verbs",
        14: "B2 Verbs",
        15: "B2 Verbs",
        16: "B2 Verbs",
        17: "B2 Verbs",
        18: "B2 Verbs",
        19: "B2 Verbs",
        20: "B2 Verbs",
    },

    trennbare_verben: {
        1: "A1 and A2 (un)trennbare Verbs with root help",
        2: "A1 and A2 (un)trennbare Verbs with prefix help",
        3: "B1 (un)trennbare Verbs with root help",
        4: "B1 (un)trennbare Verbs with root help",
        5: "B1 (un)trennbare Verbs with prefix help",
        6: "B1 (un)trennbare Verbs with prefix help",
        7: "B2 (un)trennbare Verbs with root help",
        8: "B2 (un)trennbare Verbs with root help",
        9: "B2 (un)trennbare Verbs with prefix help",
        10: "B2 (un)trennbare Verbs with prefix help",

    },

    deverbale_substantive: {
        1: "Main Deverbal Nouns (nouns derived verbs)",
        2: "Deverbal Nouns derived from A1 Verbs",
        3: "Deverbal Nouns derived from A2 Verbs",
        4: "Deverbal Nouns derived from B1 Verbs",
        5: "Deverbal Nouns derived from B1 Verbs",
        6: "Deverbal Nouns derived from B2 Verbs",
        7: "Deverbal Nouns derived from B2 Verbs",
        8: "Deverbal Nouns derived from B2 Verbs",
        9: "Deverbal Nouns derived from C1 Verbs",
        10: "Deverbal Nouns derived from C1 Verbs",
        11: "Deverbal Nouns derived from C1 Verbs",
        12: "Deverbal Nouns derived from C1 Verbs",
    },

}
