from data.data_processing.exercises import (
    praepositionen_grammatik, praepositionen_verben, praepositionen_adjektive, praepositionen_nomen,
    artikel, pronomen, konnektoren, fragen, adjektivdeklinationen,
    praesens, imperativ, partizip_II, praeteritum, praeteritum_partizip_II, konjunktiv_II, konjunktiv_I, partizip_I,
    adverbien, verben, trennbare_verben, deverbale_nomen
)

DESCRIPTION_TEMPLATES = {

    praepositionen_grammatik: {
        1: "Temporal Prepositions in sentences",
        2: "Local (Place) Prepositions in sentences",
        3: "Local (Direction) Prepositions in sentences",
        4: "Modal and Causal Prepositions in sentences",
        5: "A1 Prepositions in sentences",
        6: "A1 Prepositions in sentences",
        7: "A1 Prepositions in sentences",
        8: "Reviewing A1 Prepositions at A2 level in sentences",
        9: "Reviewing A1 Prepositions at A2 level in sentences",
        10: "Reviewing A1 Prepositions at A2 level in sentences",
        11: "Reviewing A1 Prepositions at A2 level in sentences",
        12: "A1 Prepositions at B1 level in sentences",
        13: "B1 Prepositions in isolation",
        14: "B1 Prepositions in sentences",
        15: "A1 Prepositions at B2 level in sentences",
        16: "B2 Prepositions in isolation",
        17: "B2 Prepositions in sentences",
        18: "C1 prepositions in isolation",
        19: "C1 prepositions in sentences",
        20: "C1 prepositions in isolation",
        21: "C1 prepositions in sentences",
    },

    praepositionen_verben: {
        1: "A1 Verb-Preposition pairs in isolation",
        2: "A1 Verb-Preposition pairs in sentences",
        3: "A1 Verb-Preposition pairs in isolation",
        4: "A1 Verb-Preposition pairs in sentences",
        5: "A2 Verb-Preposition pairs in isolation",
        6: "A2 Verb-Preposition pairs in sentences",
        7: "A2 Verb-Preposition pairs in isolation",
        8: "A2 Verb-Preposition pairs in sentences",
        9: "Da-Words in sentences",
        10: "Wo-Words in sentences",
        11: "B1 Verb-Preposition pairs in isolation",
        12: "B1 Verb-Preposition pairs in sentences",
        13: "B1 Verb-Preposition pairs in isolation",
        14: "B1 Verb-Preposition pairs in sentences",
        15: "B2 Verb-Preposition pairs in isolation",
        16: "B2 Verb-Preposition pairs in sentences",
        17: "B2 Verb-Preposition pairs in isolation",
        18: "B2 Verb-Preposition pairs in sentences",
        19: "C1 Verb-Preposition pairs in isolation",
        20: "C1 Verb-Preposition pairs in sentences",
        21: "C1 Verb-Preposition pairs in isolation",
        22: "C1 Verb-Preposition pairs in sentences",
    },

    praepositionen_adjektive: {
        1: "Up to B1 Adjective-Preposition pairs in isolation",
        2: "Up to B1 Adjective-Preposition pairs in sentences",
        3: "B2 Adjective-Preposition pairs in isolation",
        4: "B2 Adjective-Preposition pairs in sentences",
        5: "C1 Adjective-Preposition pairs in isolation",
        6: "C1 Adjective-Preposition pairs in sentences",
    },

    praepositionen_nomen: {
        1: "Up to B1 Noun-Preposition pairs in isolation",
        2: "Up to B1 Noun-Preposition pairs in sentences",
        3: "B2 Noun-Preposition pairs in isolation",
        4: "B2 Noun-Preposition pairs in sentences",
        5: "B2 Noun-Preposition pairs in isolation",
        6: "B2 Noun-Preposition pairs in sentences",
        7: "C1 Noun-Preposition pairs in isolation",
        8: "C1 Noun-Preposition pairs in sentences",
        9: "C1 Noun-Preposition pairs in isolation",
        10: "C1 Noun-Preposition pairs in sentences",
    },

    artikel: {
        1: "Definite articles in the Nominative case in sentences",
        2: "Definite articles in the Accusative case in sentences",
        3: "Definite articles in the Dative case in sentences",
        4: "Definite articles in the Nominative, Accusative and Dative cases in sentences",
        5: "Definite articles in the Nominative, Accusative and Dative cases in sentences",
        6: "Indefinite articles in the Nominative case in sentences",
        7: "Indefinite articles in the Accusative case in sentences",
        8: "Indefinite articles in the Dative case in sentences",
        9: "Indefinite articles in the Nominative, Accusative and Dative cases in sentences",
        10: "Indefinite articles in the Nominative, Accusative and Dative cases in sentences",
        11: "Negative articles Kein in isolation",
        12: "Negative articles Kein in sentences",
        13: "Singular Possessive articles in isolation",
        14: "Singular Possessive articles in sentences",
        15: "Plural Possessive articles in isolation",
        16: "Plural Possessive articles in sentences",

        17: "Demonstrative articles Diese in isolation",
        18: "Demonstrative articles Diese in sentences",
        19: "Articles Jede in isolation",
        20: "Articles Jede in sentences",
        21: "Definite Articles with prepositions in the Accusative and Dative cases in sentences",
        22: "Definite Articles with prepositions in the Accusative and Dative cases in sentences",
        23: "A2 Articles in isolation",
        24: "A2 Articles in sentences",

        25: "Definite, Indefinite and Negative Articles in the Genitive case in isolation",
        26: "Definite, Indefinite and Negative Articles in the Genitive case in sentences",
        27: "Diese and Jede in the Genitive case in isolation",
        28: "Diese and Jede in the Genitive case in sentences",
        29: "Possessive Articles in the Genitive case in isolation",
        30: "Possessive Articles in the Genitive case in sentences",
        31: "C1 Articles in isolation",
        32: "C1 Articles in sentences",
    },

    pronomen: {
        1: "Nominative Pronouns in sentences",
        2: "Accusative Pronouns in sentences",
        3: "Dative Pronouns in sentences",
        4: "Accusative and Dative Pronouns in sentences",
        5: "Reflexive Pronouns in sentences",
        6: "Accusative, Dative, and Reflexive Pronouns in sentences",
        7: "B1 Pronouns in isolation",
        8: "B1 Pronouns in sentences",
        9: "Relative Nominative Pronouns in sentences",
        10: "Relative Accusative Pronouns in sentences",
        11: "Relative Dative Pronouns in sentences",
        12: "Relative Genitive Pronouns in sentences",
        13: "Relative Pronouns in sentences",
        14: "Relative Pronouns in sentences",
        15: "Relative Pronouns for locations and directions in sentences",
    },

    konnektoren: {
        1: "A1 Connectors in isolation",
        2: "A1 Connectors in sentences",
        3: "A2 Connectors in isolation",
        4: "A2 Connectors in sentences",
        5: "B1 Connectors in isolation",
        6: "B1 Connectors in sentences",
        7: "B1 Connectors' synonyms",
        8: "B2 Connectors in isolation",
        9: "B2 Connectors in sentences",
        10: "B2 Connectors' synonyms",
        11: "C1 Connectors in isolation",
        12: "C1 Connectors in sentences",
        13: "C1 Connectors' synonyms",
    },

    fragen: {
        1: 'A1 Question Words in isolation',
        2: 'A1 Question Words in sentences',
        3: 'A2 Question Words in isolation',
        4: 'A2 Question Words in sentences',
        5: 'B1 Question Words in isolation',
        6: 'B1 Question Words in sentences',
    },

    adjektivdeklinationen: {
        1: "Nominative, Accusative, and Dative Adjective Declinations in isolation",
        2: "Nominative Adjective Declinations in sentences",
        3: "Accusative Adjective Declinations in sentences",
        4: "Dative Adjective Declinations in sentences",
        5: "Definite Articles' Adjective Declinations in sentences",
        6: "Indefinite Articles' Adjective Declinations in sentences",
        7: "No Article's Adjective Declinations in sentences",
        8: "Nominative, Accusative, and Dative Adjective Declinations in sentences",
        9: "Genitive, Possessive, Negative, and Demonstrative Adjective Declinations in isolation",
        10: "Genitive Adjective Declinations in sentences",
        11: "Possessive Articles' Adjective Declinations in sentences",
        12: "Demonstrative Articles' Adjective Declinations in sentences",
        13: "Negative Articles' Adjective Declinations in sentences",
        14: "Genitive, Possessive, Negative, and Demonstrative Adjective Declinations in sentences",
        15: "Neuter and Plural Article's Adjective Declinations in isolation",
        16: "Neuter and Plural Article's Adjective Declinations in sentences",
    },

    praesens: {
        1: "Present tense of A1 verbs in isolation",
        2: "Present tense of A1 verbs in isolation",
        3: "Present tense of A1 verbs in isolation",
        4: "Present tense of A1 verbs in isolation",
        5: "Present tense of A1 verbs in isolation",
        6: "Present tense of A1 verbs in isolation",
        7: "Present tense of A1 verbs in isolation",
        8: "Present tense of A1 verbs in isolation",
        9: "Present tense of A1 verbs in isolation",
        10: "Present tense of A1 verbs in isolation",
        11: "Present tense of A1 verbs in isolation",
        12: "Present tense of A1 verbs in isolation",
        13: "Present tense of A2 verbs in isolation",
        14: "Present tense of A2 verbs in isolation",
        15: "Present tense of A2 verbs in isolation",
        16: "Present tense of A2 verbs in isolation",
        17: "Present tense of A2 verbs in isolation",
        18: "Present tense of A2 verbs in isolation",
        19: "Present tense of A2 verbs in isolation",
        20: "Present tense of A2 verbs in isolation",
        21: "Present tense of A2 verbs in isolation",
        22: "Present tense of A2 verbs in isolation",
        23: "Present tense of A2 verbs in isolation",
        24: "Present tense of A2 verbs in isolation",
    },

    partizip_II: {
        1: "Partizip II of A1 verbs",
        2: "Partizip II of A1 verbs",
        3: "Partizip II of A1 verbs",
        4: "Partizip II of A2 verbs",
        5: "Partizip II of A2 verbs",
        6: "Partizip II of A2 verbs",
        7: "Partizip II of B1 verbs",
        8: "Partizip II of B1 verbs",
        9: "Partizip II of B1 verbs",
        10: "Partizip II of B1 verbs",
        11: "Partizip II of B1 verbs",
        12: "Partizip II of B1 verbs",
        13: "Partizip II of B2 verbs",
        14: "Partizip II of B2 verbs",
        15: "Partizip II of B2 verbs",
        16: "Partizip II of B2 verbs",
        17: "Partizip II of B2 verbs",
        18: "Partizip II of B2 verbs",
        19: "Partizip II of B2 verbs",
        20: "Partizip II of B2 verbs",
    },

    praeteritum: {
        1: "Präteritum of the most important verbs",
        2: "Präteritum (3rd. Per. Singular) of A1 verbs",
        3: "Präteritum (3rd. Per. Singular) of A1 verbs",
        4: "Präteritum (3rd. Per. Singular) of A1 verbs",
        5: "Präteritum (3rd. Per. Singular) of A2 verbs",
        6: "Präteritum (3rd. Per. Singular) of A2 verbs",
        7: "Präteritum (3rd. Per. Singular) of A2 verbs",
        8: "Präteritum (3rd. Per. Singular) of B1 verbs",
        9: "Präteritum (3rd. Per. Singular) of B1 verbs",
        10: "Präteritum (3rd. Per. Singular) of B1 verbs",
        11: "Präteritum (3rd. Per. Singular) of B1 verbs",
        12: "Präteritum (3rd. Per. Singular) of B1 verbs",
        13: "Präteritum (3rd. Per. Singular) of B1 verbs",
        14: "Präteritum (3rd. Per. Singular) of B2 verbs",
        15: "Präteritum (3rd. Per. Singular) of B2 verbs",
        16: "Präteritum (3rd. Per. Singular) of B2 verbs",
        17: "Präteritum (3rd. Per. Singular) of B2 verbs",
        18: "Präteritum (3rd. Per. Singular) of B2 verbs",
        19: "Präteritum (3rd. Per. Singular) of B2 verbs",
        20: "Präteritum (3rd. Per. Singular) of B2 verbs",
        21: "Präteritum (3rd. Per. Singular) of B2 verbs",
    },

    praeteritum_partizip_II: {
        1: "Präteritum (3rd. Per. Singular) and Partizip II of the most important verbs",
        2: "Präteritum (3rd. Per. Singular) and Partizip II of A1 verbs",
        3: "Präteritum (3rd. Per. Singular) and Partizip II of A1 verbs",
        4: "Präteritum (3rd. Per. Singular) and Partizip II of A1 verbs",
        5: "Präteritum (3rd. Per. Singular) and Partizip II of A2 verbs",
        6: "Präteritum (3rd. Per. Singular) and Partizip II of A2 verbs",
        7: "Präteritum (3rd. Per. Singular) and Partizip II of A2 verbs",
        8: "Präteritum (3rd. Per. Singular) and Partizip II of B1 verbs",
        9: "Präteritum (3rd. Per. Singular) and Partizip II of B1 verbs",
        10: "Präteritum (3rd. Per. Singular) and Partizip II of B1 verbs",
        11: "Präteritum (3rd. Per. Singular) and Partizip II of B1 verbs",
        12: "Präteritum (3rd. Per. Singular) and Partizip II of B1 verbs",
        13: "Präteritum (3rd. Per. Singular) and Partizip II of B1 verbs",
        14: "Präteritum (3rd. Per. Singular) and Partizip II of B2 verbs",
        15: "Präteritum (3rd. Per. Singular) and Partizip II of B2 verbs",
        16: "Präteritum (3rd. Per. Singular) and Partizip II of B2 verbs",
        17: "Präteritum (3rd. Per. Singular) and Partizip II of B2 verbs",
        18: "Präteritum (3rd. Per. Singular) and Partizip II of B2 verbs",
        19: "Präteritum (3rd. Per. Singular) and Partizip II of B2 verbs",
        20: "Präteritum (3rd. Per. Singular) and Partizip II of B2 verbs",
        21: "Präteritum (3rd. Per. Singular) and Partizip II of B2 verbs",
    },

    imperativ: {
        1: "Imperative of A1 verbs",
        2: "Imperative of A1 verbs",
        3: "Imperative of A1 verbs",
        4: "Imperative of A2 verbs",
        5: "Imperative of A2 verbs",
        6: "Imperative of A2 verbs",
    },

    konjunktiv_II: {
        1: "Konjunktiv II of the most common verbs",
    },

    konjunktiv_I: {
        1: "Konjunktiv I of A1 verbs",
        2: "Konjunktiv I of A1 verbs",
        3: "Konjunktiv I of A1 verbs",
        4: "Konjunktiv I of A1 verbs",
        5: "Konjunktiv I of A1 verbs",
        6: "Konjunktiv I of A1 verbs",
    },

    partizip_I: {
        1: "Partizip I of A1 verbs",
        2: "Partizip I of A1 verbs",
        3: "Partizip I of A1 verbs",
    },

    adverbien: {
        1: "A1 Adverbs in isolation",
        2: "A1 Adverbs in sentences",
        3: "A1 Adverbs in isolation",
        4: "A1 Adverbs in sentences",
        5: "A2 Adverbs in isolation",
        6: "A2 Adverbs in sentences",
        7: "A2 Adverbs in isolation",
        8: "A2 Adverbs in sentences",
        9: "B1 Adverbs in isolation",
        10: "B1 Adverbs in sentences",
        11: "B1 Adverbs in isolation",
        12: "B1 Adverbs in sentences",
        13: "B1 Adverbs in isolation",
        14: "B1 Adverbs in sentences",
        15: "B1 Adverbs in isolation",
        16: "B1 Adverbs in sentences",
        17: "B2 Adverbs in isolation",
        18: "B2 Adverbs in sentences",
        19: "B2 Adverbs in isolation",
        20: "B2 Adverbs in sentences",
        21: "B2 Adverbs in isolation",
        22: "B2 Adverbs in sentences",
        23: "B2 Adverbs in isolation",
        24: "B2 Adverbs in sentences",
        25: "C1 Adverbs in isolation",
        26: "C1 Adverbs in sentences",
        27: "C1 Adverbs in isolation",
        28: "C1 Adverbs in sentences",
        29: "C1 Adverbs in isolation",
        30: "C1 Adverbs in sentences",
        31: "C1 Adverbs in isolation",
        32: "C1 Adverbs in sentences",
    },

    verben: {
        1: "A1 Verbs",
        2: "A1 Verbs",
        3: "A1 Verbs",
        4: "A2 Verbs",
        5: "A2 Verbs",
        6: "A2 Verbs",
        7: "B1 Verbs",
        8: "B1 Verbs",
        9: "B1 Verbs",
        10: "B1 Verbs",
        11: "B1 Verbs",
        12: "B2 Verbs",
        13: "B2 Verbs",
        14: "B2 Verbs",
        15: "B2 Verbs",
        16: "B2 Verbs",
        17: "B2 Verbs",
        18: "B2 Verbs",
        19: "B2 Verbs",
        20: "B2 Verbs",
    },

    trennbare_verben: {
        1: "A1 and A2 (un)trennbare Verbs with root help",
        2: "A1 and A2 (un)trennbare Verbs with prefix help",
        3: "B1 (un)trennbare Verbs with root help",
        4: "B1 (un)trennbare Verbs with root help",
        5: "B1 (un)trennbare Verbs with prefix help",
        6: "B1 (un)trennbare Verbs with prefix help",
        7: "B2 (un)trennbare Verbs with root help",
        8: "B2 (un)trennbare Verbs with root help",
        9: "B2 (un)trennbare Verbs with root help",
        10: "B2 (un)trennbare Verbs with prefix help",
        11: "B2 (un)trennbare Verbs with prefix help",
        12: "B2 (un)trennbare Verbs with prefix help",
    },

    deverbale_nomen: {
        1: "Main Deverbal Nouns (nouns derived verbs)",
        2: "Main Deverbal Nouns (nouns derived verbs)",
        3: "Deverbal Nouns derived from A1 Verbs",
        4: "Deverbal Nouns derived from A1 Verbs",
        5: "Deverbal Nouns derived from A2 Verbs",
        6: "Deverbal Nouns derived from A2 Verbs",
        7: "Deverbal Nouns derived from B1 Verbs",
        8: "Deverbal Nouns derived from B1 Verbs",
        9: "Deverbal Nouns derived from B1 Verbs",
        10: "Deverbal Nouns derived from B2 Verbs",
        11: "Deverbal Nouns derived from B2 Verbs",
        12: "Deverbal Nouns derived from B2 Verbs",
        13: "Deverbal Nouns derived from C1 Verbs",
        14: "Deverbal Nouns derived from C1 Verbs",
        15: "Deverbal Nouns derived from C1 Verbs",
        16: "Deverbal Nouns derived from C1 Verbs",
    },

}
